### ISSUE TITLE
Hex editor improperly displays the values of addresses when a cheat size smaller than the data size is applied to one of the addresses

### ISSUE THREAD

**Issue by danne2** [TASVideos/BizHawk#1026]
If you apply a cheat that's smaller than the displayed data size of the memory domain, the hex editor will mis-report the values in memory.

![j3cnb6](https://user-images.githubusercontent.com/3047793/31701360-df454b32-b39d-11e7-9409-1d265fe7b8f5.png)

If you swap to 1-byte mode, you'll see the actual values.

![aszrmh](https://user-images.githubusercontent.com/3047793/31701389-0f7116e2-b39e-11e7-8a92-9fe241403d74.png)

**Comment by alyosha-tas** [comment]
This one is trickier to solve then the other one. 

For reference, the problem lies in GenerateMemoryViewString, line 512 of HexEditor.cs

The code pulls in the displayed number of bytes even if a cheat only effects one byte. I'm not sure when I'll sort this out but that's the place to start if anyone is interested.
