### ISSUE TITLE
Hex Editor ignores the "Big-Endian" toggle

### ISSUE THREAD

**Issue by NarryG** [TASVideos/BizHawk#1050]
Reversion occurred with commit https://github.com/TASVideos/BizHawk/commit/745e42a753e0190ed36d4461e5ded21d1c13ff86

The memory is being displayed in the correct order and it's just the toggle that's broken.

2.20 (intended): 
![2kbp9m](https://user-images.githubusercontent.com/3047793/32531463-d4d9b7f8-c411-11e7-952f-f2d8a6c859bb.gif)  

2.21: 
![vybab4](https://user-images.githubusercontent.com/3047793/32531445-c1366b4c-c411-11e7-8002-d84fa1b49613.gif)

**Comment by alyosha-tas** [comment]
Hmmm, I'm not sure about this one. Maybe that shouldn't be a toggle at all and just an indicator of the endianness of the domain. I think there should be a seperate option called 'swap byte order' that should be the toggle. Then there is permanent information about both how the CPU interprets the memory and how you happen to be viewing it.

Anyone else have thoughts on this?

**Comment by zeromus** [comment]
There's not even anything to debate here. The hex editor should default to the advisory endianness for the memorydomain and the user's choices to change it should affect only that hex editing session.

**Comment by alyosha-tas** [comment]
Well, here's what I find strange about this. The HexEditor doesn't read in word sized data when you change data size, it just reads in sequential bytes, as many as it needs. If it did read in word sized data, then the Endianness flag would be needed in order to display the data correctly.

But, it doesn't. What it's really doing is just swapping the byte order of the incoming stream of sequential bytes. When it's set, the byte order is preserved, when it's not set, the order is swapped.

So consider a core that stores data in 2 byte, little endian format. Counter-intuitively, in order for Hex Editor to display the data correctly, you want the Big Endian flag **set** so that it doesn't swap the byte order on you. The core already put them in the correct order to begin with.

This behaviour has nothing to do with the Endianness of the incoming data.

**Comment by zeromus** [comment]
I'm sorry you find it strange. That's how it should work. The byte stream is the correct approach for a hex editor. You have to break things down into the tiniest units before you can build them back up--otherwise you have an insurmountable problem of changing large units into different large units. 

For practical reasons, the byte units of a word-at-a-time system are returned in whatever format is most convenient. We do not have sufficient richness in the memorydomain system to describe how this would be. An emulator core could store the words either way--and then just return a pointer to the memory block for accessing bytes.

So, this problem CANNOT BE SOLVED without a revolution in memorydomain metadata.

In the meantime you live with your counterintuitiveness, or change "Big Endian" visual option to read "Byte Swap"

**Comment by alyosha-tas** [comment]
Okay, so I basically did what I proposed in my first post.

Big Endian is now a a flag that indicates the Endianness of the current memory domain. It cannot be checked or unchecked by the user, it is simply displaying information.

I also added a 'Swap Bytes' check box that lets you display the data in swapped order. I'm not sure what the use case for this is, but it's there. 

Other things that rely on Endianness, like adding Freezes / Watches, still follow the endianness of the domain. So basically, the Swap Bytes option is purely cosmetic.

Please test / comment.

**Comment by zeromus** [comment]
it should always default to the same thing regardless of the endianness of the memorydomain IMO, but at least what you described isnt broken anymore

**Comment by NarryG** [comment]
I didn't actually have a use case for it. I just noticed the reversion when testing something else.

Anyways, that fix seems to work so I'm closing this issue.
