### ISSUE TITLE
SG-1000: Implement SK-1100 keyboard

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1059]
Needed for some games.

I'm not sure how best to do this one. 

It might be worth it to seperate SG-1000 into it's own core so this can be integrated more naturally. It would be easier to do this after the graphics and sound chips are made into independent components though.

**Comment by Tastyfish** [comment]
You can technically plug an SK-1100 into a Master System, so I'll just add it to SMSHawk in general. For example, supposedly, _F-16 Fighting Falcon_ supports it despite being a Mark III game. This doesn't really make sense since the documentation suggests a DE input port is necessary but this gen of Sega input hardware is bizarre so I'll see.

If someone wants to improve SG-1000 emulation in general, that's probably another issue. (I think the palette might actually be different on that system, among probably other things).
