### ISSUE TITLE
Linux Build Failure MSB3554

### ISSUE THREAD

**Issue by Nopey** [TASVideos/BizHawk#1079]
On Ubuntu, when I run a build in monodevelop after fixing the case-mismatch on several files, it fails with this error:
```
/app/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Error MSB3554: Cannot write to the output file "/home/magnus/BizHawk/BizHawk.Client.EmuHawk/obj/Debug/BizHawk.Client.EmuHawk.Properties.Resources.resources". A null reference or invalid value was found [GDI+ status: InvalidParameter] (MSB3554) (BizHawk.Client.EmuHawk)
```
The path is not over 260 characters, so that isn't the problem.
Full Build Log:
https://pastebin.com/rks0s4XQ
Misc info:
`4.10.0-40-generic #44-Ubuntu SMP Thu Nov 9 14:49:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Nopey** [comment]
Just checked out the mono-portable branch, after fixing the case on just one file (`Version/version.csproj`) and undef'ing the WINDOWS define, it failed the same way.

**Comment by Sappharad** [comment]
What you're reporting is a bug in some of the Linux builds of the Mono compilers where PNG's in RESX files are not handled correctly; it has been discussed before and it's not BizHawk's fault. I'm going to close this because the dev tools issue is not fixable on this end.

The best fork to look at for linux is this one:
https://github.com/FelipeLopes/BizHawk

Also check out some of the posts in this thread from p4wn3r:
http://tasvideos.org/forum/viewtopic.php?p=456878#456878
He mentions the issue you ran into and how to fix it.

As far as I know, there hasn't been any Mono related activity recently. I stopped updating the mono-portable branch after BizHawk 2.0 came out due to complications that prevent that from moving forward on macOS. I created a new fork of master on my Github account with a new multi-platform UI built in Eto, but it's been over a month since I last worked on it and it's not really at a point where someone would actually want to use it yet.
