### ISSUE TITLE
Explain C64 sync settings in the dialog

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1091]
@SaxxonPike provided a detailed explanation here:
http://tasvideos.org/forum/viewtopic.php?p=464065#464065
> NTSC vs NTSCOld: Between these two, avoid using the 'old' setting. There are some very, very old demos and software that will display visual weirdness with the new timing, but it's all pretty much written in 1982- the standard NTSC setting is the vast majority of NTSC systems and most interrupt tricks rely on there being 65x263 clocks per frame as opposed to 64x262 (old). In addition, the regular NTSC setting is also very slightly faster. 
> 
>  Drean: A C64 system was manufactured for Argentina and actually has the fastest clock available, and also has 65x312 clocks per frame - essentially some kind of hybrid between NTSC and PAL timing to the video chip. This will mess with PAL/NTSC autodetection routines (most of them don't account for this kind of system) but it may be possible for some games to actually perform better on this kind of system. It's pretty rare to obtain one of these for real though. 
> 
>  SID type doesn't matter, ideally there would be different filter settings for them all, but really the only difference it will make to the system is Old vs New (6581 vs 8580) because the way the envelopes work is very slightly different and, since envelopes can be read by the system, have the potential to affect any games that rely on reading that register. I suspect this is *really rare* but I recall stumbling across one game that used one of the SID oscillators to generate a wave form which was used to derive vertical sprite positions. 
> 
>  Commodore 1541(II): These just change the kind of disk drive ROM to expect. Almost every fast loader works with the original 1541 ROM, but the 1541-II ROM fixes some bugs (and might as a result conflict with certain fast loaders). Try both with your game, but if you want something free of hassle, the safe bet is the plain 1541.

I wouldn't have problems with putting it there as is, but for the sake of sanity it might be rephrased.

**Comment by SaxxonPike** [comment]
I agree. It needs some better explanation and organization. I can write something up that would be more suitable for being described in a UI. A lot of this information is just incidental and doesn't mean a whole lot to people who just want to play games.

VIC types:

PAL: ~50hz. All PAL games will expect this configuration.
NTSC: ~60hz. This is the most common NTSC configuration. Every NTSC game should work with this configuration.
NTSCOld: ~60hz. This was used in the very earliest systems and will exhibit problems on most modern games. For the sake of completion.
Drean: ~60hz. This was manufactured for a very specific market and is not very compatible with timing sensitive games. For the sake of completion.

The differences between all of these types are significant enough that autodetection code exists- some games are compatible with both NTSC and PAL.

SID types:

OldR2, OldR3, OldR4AR: Original 6581 SID chip. (I don't think we account for the differences...yet. These all fundamentally operate the same so changing between these actually should have no effect on games.)
NewR5: Updated 8580 SID chip.

The differences between the 6581 (old) and 8580 (new) are significant enough that autodetection code exists. However, revisions among Old and New can't be autodetected because all revisions of the same type of SID all behave identically. So the revision becomes a personal preference on how the filters sound.

Some good info about the SID revisions, some recordings: http://kompjut0r.blogspot.com/2015/12/c64-sid-shootout.html

Cassette port types:

1531: Original Datasette device.

Not much to say, there weren't a whole lot of devices made for this port, but it was the primary game distribution media outside of the USA.

Disk drive types:

1541: Original disk drive and ROM.
1541-II: Improved model with some ROM bugfixes.

No one's really broken down the ROM differences, perhaps that'll be a task someday... Floppies were the primary game distribution media in the USA.
