### ISSUE TITLE
Palettes brokened in Developer build

### ISSUE THREAD

**Issue by RetroGameIntros** [TASVideos/BizHawk#1096]
Probably this is happened after commit e5ded9b

This issue on the both cores, Gambatte and GBHawk.

Note: I'm using "BGB (lcd green)" palette. Changing palettes gives no result.

1. Open any gameboy game (not gameboy color)
2. Go to GB -> Palette... and load any palette. Colors should change. 

![bizhawk dev build broken palette](https://user-images.githubusercontent.com/28905475/34988460-7947a2dc-fac7-11e7-93ee-acbf20e2ae84.PNG)

**Comment by alyosha-tas** [comment]
In GBHawk you can select the palette by going to Settings -> Color Mode. Perhaps I will add more palette options similar to gambatte later. 

For gambatte core, not sure what the solution will be there yet.

**Comment by RetroGameIntros** [comment]
You can do a commit, it thats commit fix and nothing broke than this is good solution. If commit some broke, revert it back

**Comment by nattthebear** [comment]
What is the point of the TRUE_COLOR changes in `e5ded9b139`?  Unless I'm misunderstanding something, this just exposes the exact same color mode that was already available as "VBA Vivid" through a different codepath.  Even if it's not the same, for GB you could already set any colors you wanted through our UI, and for GBC we could easily have exposed another preset along side of the 6 we already support.

And why is the true color setting saved in the savestate?  With some of the waterbox cores, things like that end up in the savestate because it can be difficult to separate them.  But everything that goes into a savestate is specifically enumerated in this core...

I don't understand at all what need was being addressed by all of these code changes to how the gambatte core renders color.  We already had the most flexible color selection preferences I've seen in any GB/GBC emulator.

**Comment by alyosha-tas** [comment]
The code changes made accuracy improvements as well as native BIOS support (way better then my glitchy implementation.) The BIOS support made picking the GBC palette possible through inputs at start up just like on a real GBC. My understanding is that this is what is being saved. For the GB side, yeah it got messed up, I'll need to figure out something for that.

**Comment by gifvex** [comment]
https://github.com/TASVideos/BizHawk/blob/e5ded9b139fd5a8cb785cdab8ca8c4efec78033c/libgambatte/src/cinterface.cpp#L73-L76

Wrapper color palettes were commented out in an early revision. On console, palettes can only be changed by the GBC bios, and doing so causes the bios to exit in one of several different states which affects movies for cycle-sensitive games. Real-time Pokemon speedruns use different palettes for different manipulations so the color of the game is important information.

There shouldn't be any issue restoring it for GB only if that's something desired.

**Comment by alyosha-tas** [comment]
Restoring it for GB I think is the goal here, since GBC is taken care of by default now.
Is uncommenting that line all that is needed without effecting the GBC related code?

**Comment by gifvex** [comment]
I think the best solution is to uncomment that line then prevent the BizHawk wrapper from calling that function unless the console mode is GB. Otherwise any settings updates will change the palette on GBC.

**Comment by alyosha-tas** [comment]
Ok, I fixed this. For GB, you can now change palette as before.

I also fixed the definition of what constitutes Cgb mode since it was inconsistent within Gambatte for some reason.
