### ISSUE TITLE
Devil's Crush PACE TG-16 bug

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#1100]
Bizhawk 2.2.1 Window Devils Crush PCE good dump for sure.

When using shake command only part of the screen shakes, on real hardware and other emulators full screen shakes

**Comment by alyosha-tas** [comment]
Looks like its doing some funny stuff with register $C in the VDC. I'll try to take a look at it since it looks relatively simple. Although I routinely underestimate PCE issues.

**Comment by alyosha-tas** [comment]
What's happeneing here is that to draw the screen the game is changing the initial number of blank scanlines during the shaking. BizHawk is mistakenly updating the screen as soon as the values are changed, which shouldn't be the case as they only take effect when the vertical refresh is actually occuring. That part is simple to fix.

The problem is that BizHawk is also displaying the screen relative to this value, so the immediate result of fixing the above is that there is no shaking at all. I don't know what I'm going to do to fix that. 

The relevent code involes the variable ActiveDisplayStartLine in VDC.Render.cs

**Comment by jjfmz42015** [comment]
I noticed if I change overscan settings on other emulators that emulate the shake correctly they get the same problem. Also noticed the earth on title screen final soldier shakes all the time. I'm mentioning all this in case it can help.

**Comment by alyosha-tas** [comment]
The problem with Final Soldier is known but unrelated.

I actually managed to fix this one so it now correctly captures screen shaking.

The downside is that there will be some extra blank scanlines, we'll need to add a cropping option.

But that already has an open issue, this one is closed.
