### ISSUE TITLE
GBA LEGO Bionicle (U) does not have sound play regardless of core

### ISSUE THREAD

**Issue by MemoryTAS** [TASVideos/BizHawk#1144]
I checked various settings and the last release I have where sound will play for this game is Bizhawk 1.12.0. I tried other GBA games they work fine. It also works fine on mGBA 0.6.1 standalone so this is a Bizhawk issue.

**Comment by ThunderAxe31** [comment]
Have you tried the latest dev build? It uses mGBA 0.6.1, differently from BizHawk 2.2.1

**Comment by ThunderAxe31** [comment]
Ok I did just check... Indeed, the audio plays fine up to BizHawk 1.12.0, and on any standalone mGBA version.
The interesting thing is that the audio is actually working on the later version of BizHawk too: it's just that you have to turn it on in the game options... Yes, the options in-game. This is very weird.

**Comment by zeromus** [comment]
This may have to do with the save ram initialization options. Some games will occasionally read uninitialized values to determine whether unimportant options are set, and if theyre net preset to the right garbage values, the settings can be strange. This may even be a problem in the retail version of the game. Not likely, just possible.

So: check if alternate options in mgba for save data can create the bizhawk behavior.

Then we would need @nattthebear to check if we changed those options in bizhawk's use of the mgba core on that release version. Finally, we may need to expose an option to control this.

**Comment by MemoryTAS** [comment]
If you mean the save data options given by Tools>Game Overrides in standalone mGBA... I have tried each of those and none of them reproduced the behavior by Bizhawk.

**Comment by zeromus** [comment]
I dont know what I mean. I meant, try every possible thing. If there's other save data options, try those.

**Comment by MemoryTAS** [comment]
There aren't other save data options.

**Comment by ThunderAxe31** [comment]
Looks like the problem is due to bad SRAM initializations. BizHawk is initializing the SRAM as 0x00 bytes, but the correct behaviour would be to initialize it as 0xFF bytes, in fact 1.12.0 has the correct behaviour. Please fix this as soon as possible, because it generates problems in other GBA games too.

**Comment by zeromus** [comment]
would it be so hard to write list of "other GBA games" here for recordkeeping purposes

**Comment by ThunderAxe31** [comment]
There is only another game that I'm aware of: Super Mario Advance 4. This game is currently in the submissions queue. This is what happens when you play the game in BizHawk: https://imgur.com/85ZyIiB
In the submission thread, Alyosha mentioned that a similar problem has been encountered in NES emulation: http://tasvideos.org/forum/viewtopic.php?p=468213&sid=96c654d0f4fe9cc3422ffdb485b3d530#468213

Now, I'm no emulation expert, but if two GBA games are both expecting to find the SRAM initialized with 0xFF bytes, and mGBA is initilizing the SRAM as 0xFF regardless of the game (I did check for some different games), then it's likely that all GBA games are also expecting to find a 0xFF padded SRAM on the first power-on. And if that's the case, then virtually all GBA games may feature emulation inconsistences.

**Comment by nattthebear** [comment]
The most reasonable default for persistent memory in GBA is probably 0xff.  That being said, any well written game would never rely on that, so I doubt the damage is that bad.
