### ISSUE TITLE
C64 state sizes

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#1193]
They vary a bit, but are sometimes outright ridiculous. Hopefully their size can be reasonably reduced. Here's the breakdown:
http://tasvideos.org/forum/viewtopic.php?p=466578#466578

Loading a C64 game:
http://tasvideos.org/forum/viewtopic.php?p=458426#458426

State size is shown in tastudio's state history settings dialog. Behold: sometimes it changes mid-game.

**Comment by vadosnaprimer** [comment]
More breakdown.

```
Double Dragon 1 (1989)(Melbourne House).d64

Unit        Pos     Size
Start       19      19
Cia0        153     134
Cia1        287     134
ColorRam    4387    4100
Cpu         4441    54
Pla         4455    14
Ram         266603  262148
Sid         267050  447
Vic         268085  1035
Cassette    268086  1
Serial      676654  408568
User        676655  1
DiskDrive   1085222 408567
Remainders  1085324 102
Total               1085324

Double Dragon (1991)(Ocean Software).crt

Unit        Pos     Size
Start       19      19
Cia0        153     134
Cia1        287     134
ColorRam    4387    4100
Cpu         4441    54
Pla         4455    14
Ram         266603  262148
Sid         267050  447
Vic         268085  1035
CartPort    268093  8
Cassette    268094  1
Serial      268095  1
User        268096  1
Remainders  268198  102
Total               268198
```

**Comment by vadosnaprimer** [comment]
Fixed via https://github.com/TASVideos/BizHawk/commit/aeca800c627feb4902e9917fbc5c92d0309620ce

**Comment by vadosnaprimer** [comment]
@SaxxonPike can you help us?

**Comment by vadosnaprimer** [comment]
@SaxxonPike please!

**Comment by SaxxonPike** [comment]
Disk states get pretty large because it's storing a delta between the image and the current state. We can't store the disk image directly, that'd just be like storing a ROM in there. It could be compressed by some kind of RLE, perhaps. After all, changes to a disk (especially for games) are almost always going to be smaller than the data on the image itself.

A disk image that has been unmodified will store all zeroes.

Serial and Disk Drive are connected, pretty sure you're right; that's a case of something getting written twice.
