### ISSUE TITLE
Atari 2600 games that crash the entire emulator (Atari 2600)

### ISSUE THREAD

**Issue by Glitcholog** [TASVideos/BizHawk#1211]
When you select 3D Tic-Tac-Toe for the Atari 2600 and you are about to do a move after the CPU, bizhawk complety crash. For now It only happen on that game, but it might happen on other as well when ill start testing them

The second one happen on Burgertime as soon as you press a button

<img width="670" alt="crash" src="https://user-images.githubusercontent.com/24578279/41192629-c55398e8-6bce-11e8-8273-d1a443465b1c.PNG">
<img width="521" alt="33333333333333" src="https://user-images.githubusercontent.com/24578279/41196858-eee6a99e-6c18-11e8-8b65-032df5ede71a.PNG">

**Comment by alyosha-tas** [comment]
These games turn off the screen to do calculations. I added a special category for them.

Please post back if you find other examples.

**Comment by alyosha-tas** [comment]
Actually amidar and burgertime were doing something else. They turn off the screen and pollthe reset button until it is released. But since BizHawk counts this as one video frame, it didn't have a mechanism to release the reset button since it was in the same 'frame.'

That is now fixed as well.

**Comment by Glitcholog** [comment]
Thank you for the quick answer and fix! It is true to say that any game that encounter that error (on screenshot 2) like amidar and burgertime will be fixed as well for future release?

**Comment by NarryG** [comment]
Based on the commit, it looks like it's a game-specific hack so if you find any more games that do it, you'll need to mention them and the hack can be added

**Comment by alyosha-tas** [comment]
Yeah it's as NarryG says. I only fixed those 3 specific games, so if you find any others please report them.

Things like burgertime are just a fluke combination of how BizHawk does things, but I was surprised to see what 3D tic tac toe was doing. It makes sense though, since a pretty signifcant chunk of processing time on A2600 is used drawing the screen, turning it off when you have to do a lot of math for an AI opponent is a good idea.
