### ISSUE TITLE
Invalid SaveRAM Path disallows closing of game/core/BizHawk

### ISSUE THREAD

**Issue by raekuul** [TASVideos/BizHawk#1241]
Importing config files with invalid saveram paths (usually by transferring the folder from an old system to a new system with new path topology) will allow games to start, but you get caught in an exception continue loop until you fix the saveram path if you try to close the game, core, or program

**Comment by Asnivor** [comment]
@adelikat @nattthebear @zeromus 

Whats the preferred outcome in this situation? Do we want to be handling the exception before it happens and prompt the user? Set the path to config default? Something else?

**Comment by zeromus** [comment]
Keep in mind I dont think we should be automatically saving saveram in the first place. Then we would not have this problem. But since we do, I think it would be ideal to try saving the saveram as soon as possible when closing and handling a failure with a "Failed flushing the game's Save RAM to your disk. Close without flushing Save RAM? yes/no" kind of box. Flush is the terminology we use in the file menu right now.

**Comment by Asnivor** [comment]
Merged to master
