### ISSUE TITLE
Temporary directory of savestates (Use disk for buffer instead of RAM option of Rewind options)

### ISSUE THREAD

**Issue by QuakerRUS** [TASVideos/BizHawk#1252]
Can you add option for set path? Now it uses %TMP% path and I can make batch file with set TMP instruction, but it will be good if you will add this option. Thanks.

**Comment by zeromus** [comment]
Would it be OK with you if I just made a global option to change the temp directory for all purposes? That may be more useful in more cases, while only being a minor nuisance at worst in most of those cases.

**Comment by QuakerRUS** [comment]
Global you mean change OS %TMP% variable or add program setting "for all purposes"? If program, why not? I think it sounds good.

**Comment by zeromus** [comment]
I did this in a funny way (sets the environment for the process).
The idea is that any code which sloppily used Path.GetTempDirectory (etc.) would now have its pathing changed.
It is a little dangerous to allow this to be changed on the fly (I do allow it) since something may expect it to be stable, but I think it's OK.
So anyway. keep your eyes peeled for problems. It's possible I could do this differently and only affect a subset of safely managed things.
