### ISSUE TITLE
Frequency option of recording video (Config and Record AVI/WAV options)

### ISSUE THREAD

**Issue by QuakerRUS** [TASVideos/BizHawk#1255]
Can you add option for change frequency of recording video? I want to record 60 Hz videos. Example: 50 Hz up to 60 Hz or 75 Hz down to 60 Hz. Thanks.

**Comment by vadosnaprimer** [comment]
Why do you need this? If for youtube, it properly processes 50Hz video, and for 75Hz it drops the frames to make it 60. I don't think this is feasible to do on the emulator side.

**Comment by QuakerRUS** [comment]
I have 60 Hz monitor and I don't see any reason to store video for me with more than 60 fps. But if it's too hard for implement, it's not so important, just more flexible option.

**Comment by vadosnaprimer** [comment]
It's not about storing, CPUs emulated work frame by frame, and they generate picture at the rate they run at, unless you use Vsync. Skipping frames during dumping is very low priority because it's not used in TASing at all, but it might make sense for regular users. Probably there is a setting to send to ffmpeg dumper command to do this for you? I don't have experience in that field. But I think it makes sense to also leave this ticket open.

**Comment by nattthebear** [comment]
Video post-processing is a deep dark hole to go down, as there are many things you could do and we'd never be able to implement anything near as good as 3rd party editing tools.  Experimenting with the ffmpeg settings sounds like a good idea.

It wouldn't be too hard codewise to target a specific framerate when dumping but it would be a simple dup/drop as needed, and I'm not convinced it's a useful thing to add.  There's only the one 75hz core anyway, right?

**Comment by QuakerRUS** [comment]
I use TASEncodingPackage now, so it's not so important for me. Just a flexible option.

**Comment by YoshiRulz** [comment]
[first DDG result for "ffmpeg change framerate"](https://stackoverflow.com/questions/45462731/using-ffmpeg-to-change-framerate)
