### ISSUE TITLE
SNES9x Code Converter is completely broken for GameShark

### ISSUE THREAD

**Issue by Kippykip** [TASVideos/BizHawk#1293]
Using GameShark codes with the Code Converter throws a **system.nullreferenceexception** if SNES9X is the selected core.

Changing to bSNES solves the problem.
![capture](https://user-images.githubusercontent.com/33023808/44449793-79646b80-a632-11e8-89de-6f2f8bf5e161.png)

**Comment by NarryG** [comment]
Snes9X doesn't expose the System Bus. The code converter is supposed to not even open under Snes9X if I'm not mistaken.
Cheats are already pretty hit or miss in bizhawk due to various domains being write protected.

**Comment by Asnivor** [comment]
The CodeConverter is either greyed out (on the tools menu) or hidden (in the cheats dialog) if _GlobalWin.Tools.IsAvailable`<GameShark`>();_ returns false.

This is based on the SupportedSystems ToolAttribute:

```
[Tool(released: true, supportedSystems: new[] { "GB", "GBA", "GEN", "N64", "NES", "PSX", "SAT", "SMS", "SNES" })]
	public partial class GameShark : Form, IToolForm, IToolFormAutoConfig
```

This check only looks at stuff based on the SystemID rather than the core itself.

I suspect that introducing an **_UnsupportedCores_** ToolAttribute would possibly be a way to solve this without too much adhoc messing around all over the place. I'll have a look and see if it looks doable.

**Comment by Asnivor** [comment]
Fix merged to master a while ago.
