### ISSUE TITLE
N64 Avi Recorder - Tsumi to Batsu - Hoshi no Keishousha Audio issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#133]
```
What steps will reproduce the problem?
1. Play N64 Tsumi to Batsu - Hoshi no Keishousha
2. Enable Audio throttle (So sound plays ok)
3. Record Avi.

What is the expected output? What do you see instead?

I expect to see A perfect game recording but instead the audio is glitch with 
gaps in the audio as the avi recorder doesn't care about the throttle setting.

What version of the product are you using? On what operating system?

Windows 7 64bit - Bizhawk 1.5.2 and various SVN bizhawk versions.

Please provide any additional information below.

The issue is probably more a Mupen64 core issue, but so far its the only 
effected game ive noticed.  I have completed a movie recording and it does 
playback fine, but when recording to avi, the audio is glitch like its running 
at a different framerate to the video.  The sync is absolutely fine however.   
All I really want is to have the avi recorder save the audio like its in Audio 
throttle mode.
```

Original issue reported on code.google.com by `MThompso...@gmail.com` on 19 Nov 2013 at 10:39

**Comment by hegyak** [comment]
I am unsure if this is corrected or not.  Please open a new bug report if it is not.

**Comment by thecoreyburton** [comment]
Thought I'd add this just in case someone's having similar problems: I had this issue with Banjo-Tooie and Chameleon Twist 2 back quite a number of revisions (it was over a year ago). The issue was solved not long after I mentioned it with the "Alternate Sync" checkbox being added to the video dumping window, allowing video dumping to not have crackling or audio gaps.

From what I can tell, if the issue is the same (which I believe it is, based on the description), it is indeed solved.
