### ISSUE TITLE
TAStudio crashes BizHawk when using MacOS

### ISSUE THREAD

**Issue by camden7306** [TASVideos/BizHawk#1336]
Whenever I try to open TAStudio when using BizHawk with mono, the entire application just crashes. Not even an error message appears, the program just quits as soon as I open TAStudio.

Version: BizHawk_mac_1.13.1.dmg
MacOS version: 10.13.6
How to recreate problem:
1. open BizHawk
2. select a rom
3. try to open TAStudio

**Comment by Sappharad** [comment]
TASStudio is not supported on macOS. A lot of non-emulation features are unsupported.
I did not attempt to go through everything and block off stuff that doesn't work, because in some cases there is a lot of untested stuff that does work.

If I recall correctly, TASStudio uses a lot of native Windows calls for custom controls like the hex editor that would need to be re-written to be multi-platform.

It is unlikely this will be ever fixed, as BizHawk 2.0 doesn't support macOS anymore and most of my experiments to get around that have been flawed. I don't have a path forward that I'm satisfied on taking yet.

Should I close this report due to the unlikeliness that it will be fixed in the near/distant future?
