### ISSUE TITLE
"DNA Warrior" game border bug - Commodore 64

### ISSUE THREAD

**Issue by QuakerRUS** [TASVideos/BizHawk#1341]
In "DNA Warrior" game there is border bug - progressing wrong picture offset (with all border modes). I see same bug with WinVICE emulator with "none" border mode, but it works properly with other border modes. Maby it's a reason of bug?

And a little offtop: why Commodore 64 core works so slow? It works less than 100% emulation speed on my not so old computer. ZX Spectrum core with higher CPU frequency works more than 100% speed for my computer.

**Comment by Asnivor** [comment]
Not really sure about the border bug. Maybe its a game that is updating the border at very specific times but the emulation isnt handling it properly? If the C64 is anything like the Spectrum you actually have to be updating specific border pixels are very specific T-States within the frame in order to get proper accuracy. However, I really know very little about the C64 in general so probably can't help with this.

Regarding the core speed, don't know I'm afraid. The emulated hardware is completely different, so probably the component implementations are not as performant (and/or there are more components emulated). 

I mean, compared to other cores the ZXHawk core is actually pretty slow. It has quite a bit going on with video generation in order to accurately generate border effects. The screen buffer is pretty much writen to every CPU cycle (so in the case of the 48k spectrum, 69888 times per frame - or 3494400 times per second). I can only guess that the C64 core is doing something similar (or the MOS implementations are slow).

**Comment by QuakerRUS** [comment]
> Maybe its a game that is updating the border at very specific times but the emulation isnt handling it properly?
Maybe. I don't know.

**Comment by SaxxonPike** [comment]
So, normally the visible area is a maximum of 320x200 pixels. However, the border logic in the C64's video processor can be messed with by very carefully writing registers at specific times. This enabled some game developers to put sprites outside of the usual visible area. I-Xera, for example, puts the score in the bottom border by actually tricking the video processor into not enabling the border at all.

The solution is not to use small borders for games like this. Unfortunately, for most games, leaving full borders on is a waste of screen space. The solution is to choose the border you like for any particular game, or leave full borders on at all times.

**Comment by QuakerRUS** [comment]
It don't work properly even in Full border mode.

**Comment by Asnivor** [comment]
Full border mode was throwing exceptions a while ago. My recent 'fix' to this may or may not have something to do with the issue you are seeing.

**Comment by QuakerRUS** [comment]
If you about this
https://github.com/TASVideos/BizHawk/issues/1272
then I tried with this fix.

**Comment by Asnivor** [comment]
So i've re-enabled the full border mode in the latest dev build.

Unfortunately it looks like the same issue occurs in this mode.

So either the issue is not as @SaxxonPike mentioned, or I made a mistake ages ago in getting Full Border working (rather than just throwing an exception).

**Comment by SaxxonPike** [comment]
I'll have a look.

**Comment by SaxxonPike** [comment]
I have just tested "D.N.A. Warrior" with PAL setup, with latest changes, in full border mode. Seems like things are working as they should.

@Asnivor @QuakerRUS Can you verify? There have been a lot of improvements to the C64 core since this issue was opened.

**Comment by QuakerRUS** [comment]
@SaxxonPike Yeah, bug was gone. Thanks!
