### ISSUE TITLE
Graphics problems in PCE Hawk

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#1348]
Final Soldier (Japan) Title Screen jumps around. Jackie Chan's Action Kung Fu (USA) has a line that blinks. This was not a problem in Version 2.3.0 After I updated to BizHawk_Developer-2018-10-11-214506-#0c2c2dcb7c0ceaa096c04b48c58f165730d14d15. I see the problem. there maybe more games with problems I just tried those to games. Here is a video of the problems.. 

https://www.youtube.com/watch?v=bM1fzlfkHpA&feature=youtu.be

**Comment by synnae** [comment]
To be honest, I just think PCEhawk is broken beyond repair. Fixing some bugs ends up introducing others, and the core is still running into basic emulation issues similar to those from old emulators, which is just embarrassing. The way things are now, it's not much better than Yabause-rr back when it was our only option for Saturn.

I opened issue #960 over a year ago and those bugs still remain unfixed. If a universal fix still has not showed up, I doubt it will in the future. At this point, It'd be better to simply give up on this core and port mednafen's much superior one over. There's not even a need to remove the former from the emulator, we can keep it as an extra in the same fashion as NESHawk/QuickNES, BSNES/Snes9x, mGBA/vba-next, etc.

Personally I don't even use PCEhawk for TASing anymore due to its unreliability.

**Comment by Cibomatto2002** [comment]
What about using the Ootake  emulator? It's updates often. http://www.ouma.jp/ootake/

**Comment by jjfmz42015** [comment]
mednaffen today is SUPER ACCURATE PCE

**Comment by jjfmz42015** [comment]
well I saw 2.4.1 is out, notes improvements on PCE. Tested Final Soldier. Issue still there.


Just pointing out.

**Comment by Spikestuff** [comment]
You should be mentioning that to the mednafen devs over there then.

**Comment by jjfmz42015** [comment]
> You should be mentioning that to the mednafen devs over there then.
> Also the last PCE update mednafen gave was back on the 24th of August 2019, Release: 1.23.0-UNSTABLE.
> 
> You'd know this if you read their [Change Log](https://mednafen.github.io/documentation/ChangeLog.txt) that they provide on the same page as their downloads.

Wors flawless in mednafen

**Comment by EZGames69** [comment]
Tested both of these games in the Waterboxed core and they are fixed.

**Comment by nattthebear** [comment]
> 
> 
> Tested both of these games in the Waterboxed core and they are fixed.

Thanks.  I'm just going to close this then; no one is ever going to fix the old one, realistically speaking.
