### ISSUE TITLE
CDL Save / Load files path problem

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1351]
Used previously https://github.com/TASVideos/BizHawk/commit/fb5ba1476 revision which able to memorize the latest directory where I save/load files with any of emulator's tools (CDL save/load files obviously). I'm used bizhawk from usb removable drive here.

in latest dev build, I have emu sitting on the drive C where the system is. But whenever I try to save/load file it put me at the root of the C drive. no matter where I save/load last files... annoying

**Comment by g0me3** [comment]
actually this option is for roms path only. and it works as intended. in both older and new revisions.
but for cdl files loaded from cdl logger (append as) the initial path is always now "bizhawk base dir/tools" for some reason.
previously it wasn exactly the last rom directory but any last directory where I did save/load operation from any save load dialog.

I always thought that this is an automatic option of the save/load dialog and handled by the system, but not sure now...

**Comment by g0me3** [comment]
it seems I found an actual problem here lol
75f3ef9b4e246d03a2b79db3bb9a2cc59a13b2fc this revision fixed some path issues by putting additional get full path filter to the path name.

for some reason, the path generators converts "." filenames in options to ".\\." then append this to the base directory like this "D:\\Dev\\BizHawk\\output\\.\\." and this then passed as InitialDir to the open dialog.

WIth this fix wrong directory trimmed and got normal, so the CDL file always will be loaded from default LogTempDirectory as set in the Path settings... 

So it seems, the behavior I need were caused by older bug and then fixed to the intended behavior which is not my preference lol... 

Why do we need to use LotTempDir to CDL files after all? why not just leave initial dir null and then make the windows adjust to the current directory automaticly?

**Comment by g0me3** [comment]
ok I can deal with this by setting the default Tool directory to rom directory by now...

**Comment by vadosnaprimer** [comment]
If you have enough interest, please consider contributing improvements to such things. CDL is used very rarely by gamers and tasers, but whenever we can, we also want to offer some tools for rom hackers. The problem is, we're basically out of developers, so any help is encouraged.

And if you feel like contributing, please discuss original intentions of the current code with zeromus at #tasvideos. A lot of things are still unfinished or roughly drafted, but the infrastructure is so complicated that fixing one thing easily breaks others.

**Comment by zeromus** [comment]
Any time something remembers the last directory used, it's by accident. We have never worked out what is the proper behaviour for directory memory. I remember having some long thread on it maybe here or maybe in desmume issue tracker, but I dont think it came to any kind of sensible conclusion. 

> Why do we need to use LotTempDir to CDL files after all? why not just leave initial dir null and then make the windows adjust to the current directory automaticly?

You can't do this; then people have no way to set the default path.

I think what needs to happen is that the standard OpenFileDialog handler needs to receive an enum saying what `OpenType` it is, where separate code forcibly chooses the default location for OpenType (it would be set to the path manager's value), but also remembers it when the user changes it via the browser (for the duration of the process) and possibly also changes it (in the ini file for the future; but that would have to be optional). I think someone could make a bug for this and then do it without it being too controversial, since our current policy is nonexistent. It would be pretty easy to do, for anyone who cares enough.

**Comment by g0me3** [comment]
ok. there is the special option to use the last recent rom file directory as a current load directory for other roms… i'd like to have the same option for other files that emulator saves/loads. why not to load cdl files also from last loaded rom directory then?

**Comment by zeromus** [comment]
I am not going to change a tool's auto load to use "last loaded rom directory". That's insane. Stuff that's automatically loaded has to come from a consistent location, or else it will act differently all the time depending on what you did just a minute before. 

"Always use recent paths for ROMs" makes some sense because that directory isn't ever automatically used for anything. You're wanting CDL to automatically use it for loading. That's what isn't going to happen.

All we could do is add an option "Always use recent path for Open File dialog" which would not reset the Open File Dialog so often, but it isn't going to affect what any of the 1000 "auto" options in CDL do

**Comment by g0me3** [comment]
the easiest way to handle this is just get the current loaded rom directory and add it to the cdl file name. so whenever I open the rom, cdl must be in the same directory. it is easier than rewriting all my scripts to look for cdl files in fixed directory rather than the current directory where rom is loaded... also I have different directories for different kind of roms - gb, gbc, done gb, done gbc, etc and they all have its cdl files with roms there... how can I assign a single directory for all these files?

**Comment by zeromus** [comment]
See "special commands" in the path manager dialog. I should add %rom% to that which uses the directory with the rom. Then you can set CDL path to %rom% and when opening c:\nes\mario.nes it will open c:\nes\mario.cdl

**Comment by vadosnaprimer** [comment]
If you use autoload recent in bizhawk roms, CDL dialog to autoopen, and autoload recent in CDL files, does it not magically work? I have this for tastudio and once I launch the emu, everything is ready to resume my work.

**Comment by zeromus** [comment]
He likes to switch between games every 5 seconds. The recent CDL is for the game he was working on 5 seconds before

**Comment by g0me3** [comment]
work like a charm, thanks
