### ISSUE TITLE
LUA gameinfo.getromname() behavior does not match documentation (BSNES core)

### ISSUE THREAD

**Issue by KatDevsGames** [TASVideos/BizHawk#1389]
Documentation states as follows:
`gameinfo.getromname
string gameinfo.getromname()
returns the path of the currently loaded rom, if a rom is loaded`

The gameinfo.getromname() function does not return this (at least not in BSNES core). It appears to return the ROM title from the header.

Suggested fix: Split gameinfo.getromname into gameinfo.getromtitle to get the ROM title and gameinfo.getrompath to get the ROM path.

**Comment by Asnivor** [comment]
Do you *actually* need the full path to the current ROM? Because it looks like the Lua function description is just incorrect.

The function accesses the Global.Game object which only contains the following fields:

![image](https://user-images.githubusercontent.com/7911038/49503743-0cd34c80-f870-11e8-9f64-48339be25822.png)

I've had a quick look, but obtaining the full path to the ROM looks surprisingly difficult. Its possible we can use PathManager.GetGameBasePath() to get the path to the rom folder, and we know the game name. But we dont know the file extension at this point and we dont know whether the ROM came from inside an archive or not (so may be in an archive with a different name). Basically all this processing has happened as soon as the ROM is opened, so not entirely sure where the data you want would be stored (and if it is accessible).

The quick 'fix' would be to rename the lua function description so that it is accurate and decide we don't ever need to return the path to the rom on disk through a lua function....

**Comment by mmxbass** [comment]
Do I personally need it? Yes. That obviously doesn't mean that anyone should bother adding it though. As you mentioned, a cursory glance at the source seems to not have this information readily available to the Lua handler.

It is a little bit unfortunate since it makes scripts that unload a ROM, patch it, and reload it effectively impossible to write but we can't have everything I guess. I don't seem to be able to write to CARTROM and restart either. I'm actually quite shocked that patching the current game is actually much much easier on sd2snes than on an emulator.

Barring knowing the ROM path or being able to write to CARTROM space (as with sd2snes), I'm unfortunately out of luck.

As I say though, it's certainly true that there is no real easy way to get the path from what I can see.

**Comment by Asnivor** [comment]
Yeah, I don't really know much about the Lua side to be honest. 

I guess you could open the ROM yourself through Lua using `client.openrom` (rather than through bizhawk UI). This way you wouldn't need Lua to report back the ROM location (as you already have it). 

At this point I guess you could either modify the ROM file directly before reloading, or use the various Lua memory functions to modify the ROM MemoryDomain as soon as the core loads (if this is even possible - I don't know).

Either way, all rom loads and core restarts will re-load the ROM file from disk into a byte array, which then gets passed into the core proper, so either the file on disk will have to have been modified, or you will have to have code in place to change the ROM domain values at the start of frame 0 (again, if this is even possible).

**Comment by zeromus** [comment]
easiest fix is to modify the documentation to say name instead of path. I know you want it, but returning the path to the opened rom will be fraught with peril. could be an archive. could be complicated. I wouldn't stop anyone from doing it, but if anyone does, it's likely to get broken repeatedly in the future.

Don't be surprised that patching a game is hard on bizhawk--bizhawk is not optimized for debugging. Lsnes is optimized for debugging.

**Comment by KatDevsGames** [comment]
That was sort of the expectation but at least we'll get the documentation matching (which is unquestionably the actual bug). I realize things can be complicated but it never hurts to ask. Getting my program to work with sd2snes was "fun" to say the least. I'll get there with BizHawk too eventually.

Thanks for the quick response on the documentation.

Side question: Is there any available method to write to CARTROM and immediately call VECTOR_RESET afterwards via Lua? (This is how I do it on sd2snes but it doesn't seem to be writable on  BizHawk.)

**Comment by zeromus** [comment]
cartrom is not expected to be writeable right now.
