### ISSUE TITLE
Slingshot/First Person Control Issues with Ocarina of Time

### ISSUE THREAD

**Issue by MDS-95** [TASVideos/BizHawk#1402]
I've been playing Ocarina of Time randomizers with Bizhawk for a while, mostly to do the co-op seeds with friends. While initially the only issues I had control-wise were sensitivity related and were just fixed by tweaking those settings, now I have a different problem. When I used the Slingshot in the Slingshot Gallery, I would need to push B to get the slingshot "loaded", but then B did nothing, and instead what I had mapped for the C-Stick would fire the slingshot occasionally, not consistently. I was only able to fix this issue by switching to a different controller (I was using a Nintendo Switch Pro Wired controller, and a friend of mine who had the same problem was using a PS4 controller), but that presented a new issue.
The new controller, just a standard wireless Xbone controller, had no such issues and could fire in the minigame with the B button as normal, but the vertical axis for first person had been reversed. Occasionally flipping the axis in sensitivity settings fixed this, though this caused an occasional problem where for a split second it would reverse again. This had no effect on my walking controls.

**Comment by YoshiRulz** [comment]
Randomizer as in romhack? If it happens with a "known good rom" (checkmark in left of status bar) then we'll talk. Also check you're using version 2.3 in case it's been fixed already.

**Comment by NarryG** [comment]
The flipped Y axis on xinput is a known issue #1200 but I can see absolutely no way it'd flip back on the fly. That issue is simply because dinput and xinput read the Y value in the opposite direction and Bizhawk doesn't account for this.  Flipping on the fly would require a much larger underlying issue. I'd go as far as trying the latest dev build as even 2.3 is getting out of date.
Are you using a specific adapter to connect the controller or are you using the stock drivers?

**Comment by MDS-95** [comment]
I've just been using the stock drivers.

**Comment by YoshiRulz** [comment]
@MDS-95, have you played OoT since December? If you're still having issues on 2.3.1, please try this [dev build](https://ci.appveyor.com/project/zeromus/bizhawk-udexo/builds/24195742/artifacts).
