### ISSUE TITLE
Stop being lazy about writing files

### ISSUE THREAD

**Issue by disastranagant** [TASVideos/BizHawk#1407]
i'm getting sick of losing saved progress to crashes and the odd power failure due to Bizhawk on Windows waiting til the program exits normally to actually write any files (save states, config files, srm, etc).  When I save I want it on disk now, not at some undefined future time that may not actually happen..

**Comment by zeromus** [comment]
The only files it doesn't write which it should are config files. save ram can't generally be written immediately when modified and in fact I frequently threaten to create an uproar in the future by making it _manually_ written. Config files are difficult to write immediately when changed because we dont have an infrastructure to track writes to the config file; it would need to be a CPU heavy waste of time serializing the config structures just to see if they're changed. If you want us to do that, open a new ticket for that case and dont expect it to be prioritized. Closing this ticket, since I just wrote the only possible happy ending and you may need a chance to re-evaluate the world after the truth bomb I just dropped on you

**Comment by vadosnaprimer** [comment]
Savestates are always written to disk instantly. Config can be written from the menu. SRAM - dunno how it works.

**Comment by NarryG** [comment]
Out of sheer curiosity, is there anything preventing just adding a save call when you press "ok" on the config panels @zeromus ? Taking a look, they all appear to inherit from the same few base classes. It's not like it takes more than a few hundred ms to save the config file (most of which is probably the actual disk IO).

**Comment by zeromus** [comment]
yes, you could go add plumbing to save the settings every time someone OK's a config dialog. They can still change settings from hotkeys and maybe the "tray" area and clicking other menu options that arent in config dialogs, so now we'd have a situation where people's saves were half saved some of the time instead of not saved at all some of the time. I don't know that that's an improvement.

**Comment by Flux3on** [comment]
This is why I use FCEUX and SNES9x
