### ISSUE TITLE
[WATERBOX] can't compile

### ISSUE THREAD

**Issue by g0me3** [TASVideos/BizHawk#1412]
fix it please or return back to non-waterbox cores unless latter were able to compiled by anyone. this is awful, gosh...

**Comment by g0me3** [comment]
why not to keep this issue unless it happen to be fixed one way or another...

**Comment by zeromus** [comment]
no. i'll deal with it. he insists I leave this bug open.

**Comment by g0me3** [comment]
> Put in some detail of what you tried and where you got stuck. Maybe it can help improve the process.

i tried to recompile the cores. and stuck because there is no vc project to do that ;)

**Comment by NarryG** [comment]
As of right now, I don't think it's even possible to generate a VC project.
I looked into setting up an environment a while back and as far as I could tell, it required obtaining and setting up an obscure build toolchain named Midipix (Linux only and has to be built from scratch) then bringing Natt's custom changes on top of that, with the only documentation being "use this version of mmglue"

**Comment by g0me3** [comment]
so why im asking about return cores to the root until they get properly copilable as waterbox
even if I'd set up all linux toolchains (hypothetical) how could I debug this stuff after?

**Comment by nattthebear** [comment]
> return back to non-waterbox cores

The only existing cores that were moved to waterbox were cores that major flaws in them that were fixed by waterbox:  Snes had the "determinism hack" issue which caused greatly decreased speeds and bugs in some games, and genesis had bad savestates that caused determinism issues in some games.  All other waterbox cores were new additions that would never have been ported without waterbox, so there's nothing to take away there.

> even if I'd set up all linux toolchains (hypothetical) how could I debug this stuff after?

Same way I did:  Attach mingw's gdb to Bizhawk.  The build process can create wbxes with symbol information on them and mingw's gdb can read it.

**Comment by vadosnaprimer** [comment]
This implies the build process is available.

**Comment by nattthebear** [comment]
> This implies the build process is available.

He said "hypothetical" so yes of course it does.

**Comment by nattthebear** [comment]
@zeromus 

To build midipix:
1. Start with a standard linux machine with all the normal devtools installed.  I used debian.  AMD64 is required.
2. Install and build midipix with https://github.com/lalbornoz/midipix_build
3. Surgically replace the mmglue in your midipix checkout (wherever the midipix_build script put it) with https://github.com/nattthebear/mmglue (use the bizhawk branch)
4. Build midipix again.
5. You now have two different toolchains: (built in steps 2 and 4).  The cross (compile on linux to run on nt64/midipix) and the native (compile on nt64/midipix to run on nt64/midipix)
6. The native toolchain you built is worthless to actually use, since step 4 hosed it.  But you want to take the libc.so, libstdc++.so.6, from this build and put them in Bizhawk/output/dll
7. The cross toolchain can now be used to build cores.  to build a core:
	a. Set up path bullshit so that `x86_64-nt64-midipix-gcc` and friends are in path
	b. Go to the folder of a core
	c. run `make`
	d. Take the output wbx or so file and put it in Bizhawk/output/dll

NB: wbx and so files can optionally be gzipped and then given a .gz extension.  It makes no difference to the loader, except that if both foo.so and foo.so.gz exist, the latter will be chosen silently.

**Comment by zeromus** [comment]
FYI for all concerned, I am working on this now. It is an elaborate process, and "helpers" will only slow it down by sapping resources from midipix developers who are already overtaxed. So thank you all for not helping me at all. I will get this done for all of us.

**Comment by vadosnaprimer** [comment]
https://github.com/TASVideos/waterboxdev
