### ISSUE TITLE
[FEATURE REQUEST] Crop & Auto Center the Emulation

### ISSUE THREAD

**Issue by Sekkei** [TASVideos/BizHawk#1440]
A general cropping feature would be nice to have. (e.g. SML2, left screen garbage tiles, needs already to be 240x224) 

Would it be possible to center/crop a game that has boarders? Problems:
There a different borders per game and hardware.
Boarders in one game could have multiple sizes per menu/screen.
What is a boarder and what is game content.

What I thought:
A min resolution per hardware (use min tiles e.g. 8x8 tiles | e.g. 320x240 > 304x224)
A max boarder hight/witdh e.g. 8px
(Set a max resolution to avoid jumping scaling if one resolution fit pixel perfect in hight with the display)

**Comment by zeromus** [comment]
this could be done in the display configuration dialog pretty straightforwardly. It would work by having you specify how many pixels to crop from each edge. Anything besides that (per game or per system) is beyond the scope of bizhawk's configuration flexibility right now. Is there any other multi-system emulator which does this to your liking?

**Comment by YoshiRulz** [comment]
Imagine BizHawk does all the cropping for you. What would it look like when games do [this](https://youtu.be/Q3RZNTC7p3s)? At best we can autocrop all but those games.

**Comment by Sekkei** [comment]
> is beyond the scope of bizhawk's configuration flexibility right now
Will there be a change, for atleast, a per game config file?

> You should be using a frontend anyway if..
I love BizHawk aiming for accuracy
 
> Is there any other multi-system emulator which does this to your liking?
Rhetorical? Idk any better solution


> Imagine BizHawk does all the cropping for you. What would it look like when games do this? At best we can autocrop all but those games.
Shouldn't be a problem. The minmal resolution and auto center should be fast enough to ouput always a perfect result. This game "feature" would not work though


>  we're not going to autocrop. defining black is hard, computationally expensive, troublesome in some edge cases, and in the case of 8bit games, not even RELEVANT since we want to cut graphics off the edge, not blackness
I dont think searching and finding blackbars would be hard, also this could be done post; there are many video filter scripts which are working at atleast at 60fps, and 2D games itself are not to demanding to emulate
adding another crop script or use an advanced cropping script would allow to crop always a certain amount in H/V 

(e.g. even games like Finfal Fantasy are off center in the default resolution)

**Comment by zeromus** [comment]
No; then use a frontend with bizhawk; not rhetorical--was looking for precedent. 

Finally, your original question was about cropping garbage, not cropping black. Auto-cropping black is at least sensible.. barely.

Regarding the varying game modes.. you may not have used bizhawk before while the resolution is varying. It isn't pleasant. In fact I suspect most if not all users would prefer auto-black-ADDING in order to make sure the resolution never changes. 

This is not really the best emulator to be asking for "frontend features" like this in. Go ask retroarch. But, like I said, we can do it in the current display framework pretty easily. I think we could also add a value in the game database and then add an option to use the gamedb-recommended display cropping options automatically, but the gamedb format is overtaxed already and I am wary of adding this to it. That's a separate, deeper task, anyway, once the basic logic is added as a manual setting. And much lower priority--things that are impossible for you to achieve without programmer help are a higher priority than making it so you can have pleasant gaming results automatically for all games while avoiding having to manually change a few settings for eachgame.

**Comment by zeromus** [comment]
If you're just making videos, then this task is poop priority. Anything that can be done in post should be.

**Comment by Sekkei** [comment]
> Regarding the varying game modes.. you may not have used bizhawk before while the resolution is varying. It isn't pleasant. In fact I suspect most if not all users would prefer auto-black-ADDING in order to make sure the resolution never changes.

That's what I meant with:

> (Set a max resolution to avoid jumping scaling if one resolution fit pixel perfect in hight with the display)


> I said, we can do it in the current display framework pretty easily. 

Maybe this could be added to the roadmap?


> If you're just making videos, then this task is poop priority. Anything that can be done in post should be.
I don't make videos, I'm no Streamer / Speedrunner

**Comment by zeromus** [comment]
"set a max and min" is too complex.
There's no roadmap. Open a new issue for "manually crop and center the emulation" though and it will get done eventually.
