### ISSUE TITLE
[PSX] "Dual Analog" option crashes BizHawk 2.3.1

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#1442]
1. Open a PSX game
2. Go on menu PSX > Controller / Memcard Settings
3. Set "Dual Analog"
4. Press OK and reboot core.

**Comment by YoshiRulz** [comment]
Could not reproduce on 2.3.0, 2.3.1, or dev build at cc532a2. The game I tested was Crash Bandicoot (US region) and the BIOS was US "Version 2.2".

OS: Win10 x86_64 1709

**Comment by ThunderAxe31** [comment]
I used Harry Potter and the Sorcerer's Stone (USA) (En,Fr,Es).
OS: Win7 Home Premium 64-bit

**Comment by ThunderAxe31** [comment]
Hash is 4B747FAA and I already tried removing the config.ini file. I also tried downloading 2.3.1 again.
It does still crash in the moment I reboot the core.

**Comment by YoshiRulz** [comment]
You can have Windows record stdout, which might be helpful, by [opening Command Prompt](https://www.sevenforums.com/tutorials/27778-open-command-window-here.html) in the BizHawk folder and typing `.\EmuHawk.exe >emuhawk_log.txt` (then crash it again when it opens). It'll write to `emuhawk_log.txt` in the same folder. Someone more familiar with the PSX core can help you from there, @zeromus?

**Comment by zeromus** [comment]
Couldn't repro. repro instructions are plainly incomplete--there are two options (two ports) where one might change the default dual shock to dual analog, and you didn't specify which one. Crash at the moment of rebooted core doesnt even sound like it would have anything to do with the game, since the bios is running at that time. I suspect you've modified your saveram files while trying to import mcr from another emulator. Either that or they've become corrupted somehow on their own. Suggestion: delete corrupted saveram files, and if you've done something sneaky and then forgotten about it, stop doing that. Also test more than one game--maybe your disc image is broken or corrupted.

**Comment by Spikestuff** [comment]
I only had this occur to me once (in 2.3.1) but the difference to the steps is that I had TAStudio open up before then did the controller switch. But when attempting to repeat the same steps it never reoccurred.

A fresh Hawk and copying Thunder's post to the tee I was also unable to reproduce it.

**Comment by ThunderAxe31** [comment]
I've deleted the SRAM files and I'm unable to reproduce the crash. It was probably the cause, though I remember I tried using a fresh 2.3.1 folder as well... In any case, I'll now close this issue unless I'm able to reproduce and record a log. Sorry for the inconvenient.
