### ISSUE TITLE
Audio source name uses focused window's title

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#1499]
Title ([demo vid](https://youtu.be/pRTmyT1QGg0)).

Seems to only happen when I open the Volume Mixer *after* EmuHawk, which makes me think this is a bug in Windows and not our problem. I'm using 2.3.1 and have EmuHawk set to use DirectSound.

I didn't really show it in the video, but if you switch windows without closing them it still changes, hence "focused window" and not "newest window". I also didn't show the icon changing because I couldn't reproduce it; the first time I encountered this it had the Lua Console text *and* icon.

See also #334?

**Comment by vadosnaprimer** [comment]
LOL this is so silly. Though I don't feel like we should care about inconsistencies in the OS itself. I don't think it's even possible for our tools to generate sound, so it's some broken detection somewhere.

**Comment by nattthebear** [comment]
> I don't think it's even possible for our tools to generate sound, so it's some broken detection somewhere.
The sound APIs don't involve a HWND, so it's not that.

**Comment by zeromus** [comment]
This is just windows trying to be too helpful. Windows doesn't know what the application's main window is. We didn't subscribe to the mixer interface, windows attempts to guess what to show. This probably happens because around the time this mixer was created, microsoft was telling people to create multiple top-level windows and pretend that the same process wasn't operating them all behind the scenes.
