### ISSUE TITLE
snes BSX support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#159]
```
i'm not sure BSX roms can be detected. if so, detect it.
we may need to put them in the gamedb.
otherwise, we need a special rom load option.
bsnes 0.87 requires specially selected load options.
```

Original issue reported on code.google.com by `zero...@zeromus.org` on 20 Apr 2014 at 11:15

**Comment by hegyak** [comment]
This is also known as the Satellaview.  This may require an updated BSNES Core.

I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen. They are impractical to sit around in queue.

Plus it goes without saying. The goal of bizhawk is to emulate all platforms. A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request. Cores are added based on the time/effort/practicality of doing so. And it is on everyone's mind to add all platform support. So these tickets are kind of pointless.
