### ISSUE TITLE
GBA 2.3.1 savegame-anchored movie will "forget" its savegame when loadstating

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#1593]
I'm playing Super Mario Ball (J).gba on Bizhawk 2.3.1, mGBA-core. EDIT: It seems to be a different behavior for VBA-Next. Will update here with information soon.

If the game is started anew, then pressing on the title screen will start the game immediately. But if you unlocked Time Attack mode (by obtaining 2 star keys), pressing on the title screen will bring up a selection between "new game" and "time attack".

I wanted to TAS Time Attack mode and started a new movie, starting from SaveRAM.
When letting it run through to the title screen, I can select the mode and everything will work normally from then on.

But if I save and load a state at any point before the cutscene before the titlescreen (BIOS screen to "Fuse Games" screen), then the Time Attack mode will be gone, and the game acts as if it had no savegame.

**Comment by vadosnaprimer** [comment]
What about previous releases?

**Comment by mugg91** [comment]
Results from my brief testing:

- 2.3.1	
MGBA said problem
VBA properly doesn't forget its savegame.

- 2.3.0	
MGBA same problem(?)
VBA properly doesn't forget its savegame.

- 2.2.2	
MGBA same problem
VBA "forgets" it even when letting it run through without loading/saving states	

- 2.2	
MGBA same problem
VBA "forgets" it even when letting it run through without loading/saving states

**Comment by RetroEdit** [comment]
This issue persists into BizHawk 2.4 and the latest developer build at time of writing (`2020-04-07-134352-#ce17df2b6abcd6784d15c8f45889fb4e6d9b678d`). It appears to be GBA-specific; I did not have this issue when I created a bsnes movie. Currently, I have only tested mGBA.

To begin with, a .bk2 movie will still load properly with the SaveRAM as expected. The issue occurs when loading a savestate while a SaveRAM-anchored movie is being played back. If a savestate is loaded before the SaveRAM would be used (e.g. before the file select screen in most games), then BizHawk will act as if the SaveRAM in question does not exist and the game will play as if there is no existing save file. The movie remains unmodified (containing the proper original SaveRAM). Thus even if the saved movie is overwritten by modified inputs after loading a savestate, the saved movie will act as if starting from the original SaveRAM when newly loaded from the beginning.

The way I originally discovered this issue is documented [here](https://github.com/TASVideos/BizHawk/issues/1913#issue-595422629). I originally discovered it using TAStudio, but the issue is more fundamental than that.

**Comment by zeromus** [comment]
Here's my thoughts on this (testing shrek 2). mgba can't save the save ram right at startup because it's still autodetecting. I think the way mgba works is once the autodetection is complete, it kind of "resolves" things using the save data that's provided. But until that happens, the save data is in a messed up state. I solved this problem in desmume long ago by saving the state of the autodetection in the file format. I don't see how MGBA can possibly work without that. So I think it must be broken, even in official frontend. 

I would prefer for endrift to figure this out, but first we need to prove that official mgba frontend or other frontends have a similar problem. If not, then we need to figure out how theyre using the core->api functions so theyre not vulnerable to this problem.

**Comment by endrift** [comment]
The savestates store what the configured save type is, so loading a savestate *should* fix that.

**Comment by zeromus** [comment]
Shrek 2 is fixed due to endrift's work (thanks!) 
You guys need to verify the tas scenarios. There could be still more bugs in our end (due to the vba-next involvement? I didn't even look at that)

**Comment by endrift** [comment]
This is pending @mugg91 testing an interim build, correct?

**Comment by RetroEdit** [comment]
Or I can test, as I'm the one who actually brought it to developer's attention; before I commented and talked about it in IRC, it was sadly forgotten.

And done: Shrek 2, tested with my general procedure.

Of course, if devs want mugg for double-confirmation, they're more than free to. Also, I know issues are sometimes kept open until the release that fixes them.

And @adelikat this is definitely an issue I would bring up in the next release notes, as I consider it a significant if low-profile because apparently no one has noticed it in all these years (anyone doing SaveRAM-anchored movies has a potential to notice it).

----

As for VBA-Next, that's being removed anyway. So... I can see your point about there being something else potentially off with BizHawk, but it seems just as likely to me that VBA-Next had similar holes in its savestate implementation. And I have no desire to wade through VBA-Next problems just because it potentially relates to BizHawk; others are free to do so if they feel it's important.

**Comment by endrift** [comment]
Erm, we'd already confirmed that Shrek 2 was fixed. We wanted to make sure the bug in Super Monkey Ball was also fixed by this before we closed it.

**Comment by RetroEdit** [comment]
Sorry about that. Now I've tested Super Mario Ball and had no issues with newest BizHawk (not to be confused with Super *Monkey* Ball, which apparently wasn't a GBA game, only Super Monkey Ball Jr. was). I also confirmed that it previously had an issue as late as 2.4.2, exactly as expected.
