### ISSUE TITLE
Savestate.loadslot() function under TAStudio won't load branches > 9

### ISSUE THREAD

**Issue by nlburgin** [TASVideos/BizHawk#1649]
When TAStudio is open, the `savestate.loadslot()` Lua function changes its behavior to operate on TAStudio's branches rather than the conventional savestate slots (though IIRC it seems to retain the 0-9 limit of the original save slots, not operating on branch numbers >= 10)

I consider this behavior useful, as it can be combined with the tastudio-specific API to make botting scripts that operate directly on the input list. I've used this functionality extensively for Mario Golf [(example)](https://github.com/nlburgin/MarioGolf-TAS-Junk/blob/master/GolfLevel2PermutatorFormatted1-3.lua)

However I want to know if this behavior is intentional and API-stable, or if it's unintentional and subject to change/breakage later on.

If it's unintentional, I at least hope that if it gets "fixed" it would at that point be replaced with an explicit `tastudio.loadbranch()` function that could give this functionality.

And if it's already supposed to work that way, it would be nice if this behavior was documented somewhere (and in that case this issue would probably tie in with #1604 )

**Comment by vadosnaprimer** [comment]
It's intended.

What if you try to use slots beyond 9 from lua (with tastudio open)?

**Comment by YoshiRulz** [comment]
It's intended.
https://github.com/TASVideos/BizHawk/blob/e6374ef4771ff0f0b973bd5f671675269e3f7a96/BizHawk.Client.EmuHawk/tools/Lua/Libraries/EmuLuaLibrary.Savestate.cs#L55-L58

**Comment by vadosnaprimer** [comment]
We could enable other slots for lua when tastudio is open, but I personally think 10 slots is enough for any automation.

**Comment by YoshiRulz** [comment]
https://github.com/TASVideos/BizHawk/blob/432abb27f63a7ce116402eb1b056cacc37c0613f/BizHawk.Client.EmuHawk/MainForm.cs#L4193-L4197
If the main window has been told to defer savestates, it'll enter this block and return (skipping the bit that writes savestate files). The property `Master` is of type `IControlMainform`, an interface added to `TAStudio` for presumably this purpose. It really should be documented *and* print an error for `slotNum` outside `0..9`. I'll look into that tomorrow.

If you think giving Lua greater control over branches would be helpful, you should change this issue's title to reflect that. Otherwise, I'll close it when the docs are updated.

**Comment by YoshiRulz** [comment]
BTW TAStudio (or any `IControlMainform`) actually receives the *last digit* of the slot number (though, as noted, Lua can't trigger this behaviour). The whole interface could be better designed really.
