### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by anishvundela** [TASVideos/BizHawk#1658]
On all of the n64 whenever I load a rom it just gives me a black screen but the sound still plays

**Comment by nlburgin** [comment]
I've seen a problem like this, but IIRC it wasn't for all consoles, it was only for N64 when using the GLideN64 video plugin _(Note: This is not the same issue I described in #1646, but something that happened even with builds not affected by that. I never reported it because I assumed it was just an issue with my own system.)_

I eventually resolved it by setting it up so I could force my OpenGL driver to run in "3.3 core profile" mode, at which point the graphics started to behave normally.

I was under the impression that this problem was internal to that specific graphics plugin for that specific core, not all of Bizhawk. But now you say that it happens "for all the consoles", which I find interesting and surprising. Still, I'd recommend you check your graphics drivers.

**Comment by YoshiRulz** [comment]
This sounds like a similar but unrelated issue with your drivers. Try each of the three display methods in `Config` > `Display...` > `Display Method` (restart EmuHawk after each change).

**Comment by anishvundela** [comment]
This is not working

**Comment by YoshiRulz** [comment]
@anishvundela Was it a driver issue?

**Comment by zeromus** [comment]
And did you try using a system besides n64?
