### ISSUE TITLE
Incorporate Lsnes Savestate System and Potential NESHawk Accuracy Issues

### ISSUE THREAD

**Issue by Maru370** [TASVideos/BizHawk#1676]
Incorporate Lsnes Savestate System:

One of the advantages that Lsnes has over BizHawk is that it treats each savestate as a movie. This is beneficial to several TASers, as it helps for efficiently testing routes and makes it harder to lose work. For routing-centered games like Super Metroid, this will greatly help. It would be good to see this option of a savestate system incorporated into BizHawk someday.

Potential NESHawk Accuracy Issues:

The current Mega Man 2 TAS, which was made on FCEUX, console verifies, but it did not sync when the movie was played on the NESHawk core. @vadosnaprimer recommended bringing this to the developers' attention.

TAS: http://tasvideos.org/4006M.html
Console verification stream by dwangoAC: https://www.twitch.tv/videos/480684418

**Comment by nlburgin** [comment]
>One of the advantages that Lsnes has over BizHawk is that it treats each savestate as a movie.

Don't the savestates already include input logs if you make them while recording? I thought that was already a thing.

I'm not 100% sure since I've mostly been using TAStudio and that handles a lot of things differently than movies made without it, but I *thought* the regular savestates could already do that.

>Potential NESHawk Accuracy Issues:
>
>The current Mega Man 2 TAS, which was made on FCEUX, console verifies, but it did not sync when the movie was played on the NESHawk core. @vadosnaprimer recommended bringing this to the developers' attention.

This sounds like a completely separate issue from the first one you mentioned. I'm not in charge here but I'm pretty sure you're not supposed to lump unrelated issues into one post like that.

**Comment by adelikat** [comment]
Savestates made when a movie is loaded, store the entire input log of the movie in them.

Savestates, like .bk2 and .tasproj files are simply zip files with things in them, so you can easily open them and see that there is an input log.

**Comment by adelikat** [comment]
Closing this, savestate behavior was never an issue.
And the desync report is insufficient.  When a console verification is done, lag differences between fceux and the console are accounted for.  You can't say a neshawk movie wouldn't sync, unless the converted movie was then converted to a console movie, accounting for its lag differences as well.
