### ISSUE TITLE
Port BizHawk to more platforms

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#1678]
Hello dear Friends bizhawk is a great emu font end for TAS slowly adding more cores but think about support android and raspaberry Pi 4  to expand TAS Features to more plataforms and get more users

**Comment by Spikestuff** [comment]
> Android
> Raspberry Pi 4

Ok.
Android is not worth porting Hawk to mainly due to the tons of devices having each of their own problems and the fact that doing all these inputs as touch controls is definitely going to cramp the screen.
RP4 isn't strong enough for Hawk, also considering that RP4 is Linux based (most of the time) have you attempted running lsnes on it?

**Comment by YoshiRulz** [comment]
I disagree that an Android port isn't feasible, my ancient phone can run Mupen at full speed (touch controls do suck though, gamepad recommended). The reason there is no "EmuHawk Lite" on mobile is because it needs .NET Core / Xamarin: see #1415.

Raspbian would work if it were running on a modern PC, but the Pi has an ARM64 CPU and BizHawk will only compile for x86_64.

**Comment by Unounited** [comment]
So are you saying bizhawk will work with android and a pi?

**Comment by YoshiRulz** [comment]
Maybe one day.
