### ISSUE TITLE
firmware organize

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#1736]
firmware organize function I believe used to rename use & move unused files into a sub folder.

Current builds it does rename but doesnt seem to move.,

Having it move unused could be nice if its a simple fix.

**Comment by Asnivor** [comment]
Looking at the git blame, if this behaviour was true in the past, it was well over 6 years ago.
The Import method was updated some time ago however so that it only imports recognised firmwares (unless you have the checkbox next to it ticked).

Assuming your aim is to separate out BizHawk-recognised firmware and non-recognised firmware, move all the firmware out of you firmware folder to somewhere else, then import from that location using the bizhawk firmware dialog. This should only copy the recognised firmwares into the firmware folder.

As to whether 'moving unrecognised firmwares to a sub folder when using organize' is something we want - someone else should say whether this is a good idea or not. Its an easy implementation though.

**Comment by hegyak** [comment]
I, personally liked the idea of putting unknown firmware files into a sub-folder inside the Firmware Folder so I could quickly identify what Files were bad or invalid when I dropped in a bunch of random Files.  But with the addition of the "Do not import unrecognized" Firmware Files the odds of this happening should be less common now because users can ask BizHawk to identify the good and bad firmware files.

Would re-implimentating this issue be a major problem or issue or hassle?  I don't recall why it was removed in the first place.
