### ISSUE TITLE
Desync Issue in 2.3.3

### ISSUE THREAD

**Issue by The8bitbeast** [TASVideos/BizHawk#1790]
I was TASing Fantasy Zone (Sunsoft, NES) and got some pretty frequent desyncing with TAStudio on 2.3.3. Attached are 2 tasproj files with desyncs. It seems to have something to do with enemy spawn RNG which is causing the desync.

I did start this project from a bk2 started on 2.3.2, but since then I've also recreated a desync from a fresh tasproj from power on.

[NES Fantasy Zone.zip](https://github.com/TASVideos/BizHawk/files/4052457/NES.Fantasy.Zone.zip)
[Desync 2.zip](https://github.com/TASVideos/BizHawk/files/4052458/Desync.2.zip)

**Comment by The8bitbeast** [comment]
Video of the desync reproduced on N64:

[2.3.3 Desync on N64.mp4.zip](https://github.com/TASVideos/BizHawk/files/4053085/2.3.3.Desync.on.N64.mp4.zip)

**Comment by alyosha-tas** [comment]
Did you have any desync issues with 2.3.2?

**Comment by EZGames69** [comment]
I have yet to test this, but I believe the issue is from how “drawing inputs while drawing” is done now.

Before, whenever emulation was active and you drew inputs by dragging, a savestate would load every time a new input was made, now it only loads the savestate as soon as you let go of the mouse button.

The issue I believe stems from which savestate is loaded once the mouse button is let go.  Instead of loading the savestate from where dragging started, it loads the state near where the button was let go.

The reason why I believe this is the case is because i noticed a state that was loaded where the char would jump, yet I had just removed the jumping button in an earlier frame.  I cant think of any other explanation for this.

**Comment by EZGames69** [comment]
Update: so my theory was correct, however only sometimes it's the case.

so when you make an input, all the savestates below it should go away, and if you drag and draw inputs, there should be no savestates that get made over your inputs.  however sometimes it does happen, and that's where it loads the incorrect savestate.

**Comment by adelikat** [comment]
Fixed! in release branch
