### ISSUE TITLE
An empty (or nearly-empty) while true loop crashes the emulator

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1795]
If you have code like this in a Lua console script, the emulator stops responding and crashes:

```
while true do
    -- Do basically nothing (i.e. no frame advance)
end
```

This is not the only options for waiting (and perhaps an ill-advised one), but it does prevent script-local variables from going out of scope.

**Comment by YoshiRulz** [comment]
`emu.yield()`? Of course an infinite loop is going to crash without some way of jumping out of the loop.

**Comment by zeromus** [comment]
It doesn't crash the emulator. If it did, that would be worth addressing, because bizhawk doesnt know the difference between a loop forever in lua that does nothing and a loop forever in lua that does something. However, it correctly does exactly what you told it to do which is stick inside lua and never leave. Lua is powerful enough to hang itself.

**Comment by RetroEdit** [comment]
Ah, okay, I was not aware of `emu.yield()`, and I'll try that out. Sorry for wasting your time.
