### ISSUE TITLE
Bizhawk won't detect Visual C++ 2015? [wine]

### ISSUE THREAD

**Issue by BILLPC2684** [TASVideos/BizHawk#1803]
i know this is a stretch i'm running the lattest version of wine with supports DirectX/3D and have installed Visual C++ for 2010, 2012 and 2015 but for some reason i get:
> [ OK ] .NET CLR (You wouldn't even get here without it)
> [ OK ] Direct3d 9
> [ OK ] Visual C++ 2010 SP1 Runtime
> [ OK ] Visual C++ 2012 Runtime
> [FAIL] Visual C++ 2015 Runtime

is there a reason why it's failing when i have C++ 2015 installed? (and the reason i'm not compiling for linux is cause i'm lazy and i belive wine can run it... minus this problem :| )
![Screenshot from 2020-01-20 04-54-25](https://user-images.githubusercontent.com/16583502/72716947-205b7880-3b41-11ea-95e5-7a3c5c624136.png)

**Comment by YoshiRulz** [comment]
That is weird. If you want to keep trying WINE, it's looking for this assembly (from MSVC 14.0) in the GAC:
https://github.com/TASVideos/BizHawk/blob/b80b3678318203ea39ec0c97d14ec13d4530460b/BizHawk.Client.EmuHawk/Program.cs#L39

I can't really help you beyond that as I don't use WINE outside Steam, but I can tell you that there are [automated builds](https://gitlab.com/TASVideos/BizHawk/pipelines) on GitLab.

---

Closing because WINE is unsupported (please come back and post the solution if you find it).

**Comment by zeromus** [comment]
Did you install the x64 version?
