### ISSUE TITLE
System Bus memory domain does not appear to be implemented correctly for GBA

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#1809]
I'm looking for [`KEYINPUT`](https://problemkaputt.de/gbatek.htm#gbakeypadinput) in the hex editor, and `0x4000130` does not appear to correspond to it. More strikingly, there is modified memory in `0x3FFFFFF` going backwards, but that shouldn't be the case because that falls within undefined memory locations. Do I not understand the System Bus memory domain, or is it not implemented properly for GBA in Bizhawk?

I'm using Bizhawk 2.3.3 with the mGBA core.

**Comment by zeromus** [comment]
1. You do not understand the system bus memory domain. There's always something at every address, even if it's nonsense. Or more likely, it's mirrors of what's at the beginning of the address range

2. keyinput is strange. for some reason MGBA is returning buffered memory for "peeking" the IO regs instead of generating the data the same way as it would be fed to the CPU. In general it's dangerous or impossible to read an IO register through tools because reads can be destructive or difficult to manage for the emulator. The latter would be the case here, although it's possible these can be implemented via specialized peeks for special cases which avoid the destructive effects. Consider that in the case of this emulator, reading KEYINPUT causes callbacks which feed the input (perhaps from a movie) to immediately fire.

Don't assume IO registers work, and especially don't assume this one works. Don't use it--find another way to do what you need to do.

We can't really call this a bug because it's bugged in virtually every core to some extent or another. If you have a compelling reason (you dont) to need KEYINPUT then reopen a ticket to ask for it specifically

**Comment by RetroEdit** [comment]
Fair enough, I sort of knew those two things already (memory mirroring in particular was annoying me after I remembered it after I filed the issue, but didn't have the opportunity to modify it again), but clearly didn't consider them enough before filing this issue. Thanks for the detailed explanations.

I guess I can always fallback on something like:

```
key_order = {'L', 'R', 'Down', 'Up', 'Left', 'Right', 'Start', 'Select', 'B', 'A'}
current_keys = joypad.get()
result = 0
for i = 1, 10 do
    result = result * 2
    result = result + (current_keys[key_order[i]] and 1 or 0)
end
```

Less efficient than a theoretical `KEYINPUT` read would be, but it was really the concept that mattered anyway (I could always translate everything else to use LUA tables for processing, too). I could imagine other IO registers potentially being useful in certain specific cases, but I'd imagine there's almost always a workaround.
