### ISSUE TITLE
Building has become slow

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#1813]
Building Bizhawk, especially BizHawk.Emulation.Cores where I do most of my work, has become very slow, taking several times longer to build then it did two days ago. It's really slowing me down.

**Comment by Sappharad** [comment]
@YoshiRulz 
If this was caused by your switch to .NET Standard and you want a work-around, adding multi-targeting might help:
https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks

**Comment by YoshiRulz** [comment]
Cores is still [targeting net48 in master](https://github.com/TASVideos/BizHawk/blob/3ae58fd9d624d722207d0d65cb91e611a0f3f1ae/BizHawk.Emulation.Cores/BizHawk.Emulation.Cores.csproj#L5), the slowdown is probably because of the Roslyn Analyzer. A temporary solution is commenting that out [here](https://github.com/TASVideos/BizHawk/blob/14d088f9075bd28ee0031903bd2bda9239a8b39c/Common.props#L24). A permanent solution is splitting the Cores project into many and compiling them in parallel.

**Comment by alyosha-tas** [comment]
That worked, thank you!

**Comment by zeromus** [comment]
I've seen this tool using all CPU cores, so for a full rebuild so it should be largely the same workload no matter what. However for the case of iterating on a single core splitting it would be a big help. But--adding dozens of csprojs is going to bog everything down. I would rather us not have this slow analyzing auto-enabled. Can you please find a way to enable that as a user preference only? Can add a new configuration for analysis? Can add a condition in msbuild that checks for some other mechanism to opt-in?
