### ISSUE TITLE
32X Emulation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#183]
```
What steps will reproduce the problem?
1. Attempt to open any 32X game.  There's no Core for it.

What is the expected output? What do you see instead?
Bizhawk eventually running 32X games.

What version of the product are you using? On what operating system?
Any version that has Gens-Plus.

```

Original issue reported on code.google.com by `hegyak` on 8 Jun 2014 at 1:23

**Comment by adelikat** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen.  They are impractical to sit around in queue.

Plus it goes without saying.  The goal of bizhawk is to emulate all platforms.  A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request.  Cores are added based on the time/effort/practicality of doing so.  And it is on everyone's mind to add all platform support.  So these tickets are kind of pointless.
