### ISSUE TITLE
PCEHawk: can't load PCE-CD games with 16-bit PCE firmware

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#1894]
Some PCE-CD games have funny messages and secrets that appear when you try to start the game using the wrong system card. But I tried to load Akumajou Dracula X with a CD-ROM System (Japan) (v2.1) BIOS, and Bizhawk gave me an error message saying that the game requires a Super CD BIOS, and did not allow me to play the secret stage. Also, I don't know if this is related, but when I tried doing the same with a fan-translated version of the same game, Bizhawk did start the game, but instead of showing the new title screen and then starting the secret stage, it just played the new title screen forever.

**Comment by zeromus** [comment]
I can't even get the pcecd core to start with the 2.1 bios selected.
Bios is designed to operate from the software side, specific hardware revisions.
pcehawk emulates a specific hardware revision.
We don't warrant what happens when you use the software that mismatches the hardware we emulate.
This isn't supported (but I have no idea how you did it anyway)
Use the Info function in the firmwares manager to see which firmware versions are supported, in the future.
