### ISSUE TITLE
Can't load GB rom in SGB

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#1899]
This is only in Dev build. Go to GB -> Load GB in SGB and then reboot core. This can be reproduced also by going to "Config -> Cores -> GB in SGB" and then load GB rom

![Снимок](https://user-images.githubusercontent.com/21311432/77762400-250d4300-7042-11ea-8410-b59fcd49c0c2.PNG)

**Comment by EZGames69** [comment]
What game are you using?

**Comment by medigi** [comment]
Tested on Animaniacs, Bugs Bunny Collection and Donkey Kong

**Comment by alyosha-tas** [comment]
I tried to figure this out. Apparently what's happening is the Sameboy bios file resources (which are .bin) are copied to a different file then other resources (which are .rom)

Specifically, they go to \bin\BizHawk.Emulation.Cores.resources.dll

Where as the other resources get directly embedded in BizHawk.Emulation.Cores.dll

How/why does this happen? I don't know. But since the resource file loader only searches in one place, it can't find them.

I could just rename the files to be .rom, or make a new reader to search in the correct location, but is there another way to just override it making a new directory? @YoshiRulz any ideas? Google didn't tell me.

**Comment by YoshiRulz** [comment]
Is [this](https://github.com/TASVideos/BizHawk/commit/5196b97459719ca5b2bc1e6e52d7e69ea9f2841d#diff-ebcb0b43f53e1cf35a985336cd80a6d3) helpful? I recently fixed the Cores project's resource generation to work with .NET Core. All `<EmbeddedResources/>` should have a corresponding `Lazy<byte[]>` in `BizHawk.Emulation.Cores.Properties.Resources`.

**Comment by alyosha-tas** [comment]
`private static byte[] ReadEmbeddedByteArray(string embedPath) => Asm.GetManifestResourceStream($"BizHawk.Emulation.Cores.Resources.{embedPath}").ReadAllBytes();`

The problem is that this path isn't the same for all resources. Visual Studio (apparently of it's own accord) puts the .bin's in a different place then the .rom's. Can they be forced to all be in the same place?

**Comment by YoshiRulz** [comment]
I'm not sure what you mean about VS moving files, the paths for `GetManifestResourceStream` aren't on the filesystem. They're from a list set at compile-time, each is just the assembly's name concatenated with the path from the `<EmbeddedResource/>`, and it uses `'.'` instead of `'/'`. You can print them all with `Asm.GetManifestResourceNames()` and verify that they match with the archives on disk.

It looks like the Sameboy code I linked to copies the resource from the assembly into a buffer, then decompresses it. Are you sure it's the first step of that which isn't working?

**Comment by alyosha-tas** [comment]
Yeah, all I need to do is change the extensions in the files to .rom instead of .bin and it works.

You can load up BizHawk.Emulation.Cores.dll in a hex editor and see that all the .bin files aren't in there and all the .rom ones are.

**Comment by YoshiRulz** [comment]
```
$> rm -r */bin */obj */*/bin */*/obj && Dist/BuildRelease.sh
$> strings output/BizHawk.Emulation.Cores.dll | grep Resources
Resources
BizHawk.Emulation.Cores.Resources.CPC_BASIC_1.0.ROM.gz
BizHawk.Emulation.Cores.Resources.CPC_BASIC_1.1.ROM.gz
BizHawk.Emulation.Cores.Resources.OS_464.ROM.gz
BizHawk.Emulation.Cores.Resources.CPC_AMSDOS_0.5.ROM.gz
BizHawk.Emulation.Cores.Resources.128.ROM.gz
BizHawk.Emulation.Cores.Resources.CPC_OS_6128.ROM.gz
BizHawk.Emulation.Cores.Resources.48.ROM.gz
BizHawk.Emulation.Cores.Resources.sgb-cart-present.spc.gz
BizHawk.Emulation.Cores.Resources.plus2.rom.gz
BizHawk.Emulation.Cores.Resources.plus2a.rom.gz
BizHawk.Emulation.Cores.Resources.Spectrum3_V4-0_ROM0.bin.gz
BizHawk.Emulation.Cores.Resources.Spectrum3_V4-0_ROM1.bin.gz
BizHawk.Emulation.Cores.Resources.Spectrum3_V4-0_ROM2.bin.gz
BizHawk.Emulation.Cores.Resources.Spectrum3_V4-0_ROM3.bin.gz
BizHawk.Emulation.Cores.Resources.cgb_boot.bin.gz
BizHawk.Emulation.Cores.Resources.dmg_boot.bin.gz
```

Now I'm more confused. I guess if you've fixed it, no need to worry, I just hope it's not a Windows-specific bug in the SDK.

**Comment by alyosha-tas** [comment]
that's weird

in your output folder do you get a folder called 'bin' with this dll in it?
BizHawk.Emulation.Cores.resources.dll

**Comment by YoshiRulz** [comment]
No such folder, and no file anywhere in the output.

**Comment by alyosha-tas** [comment]
Changing file names just avoid inconsistent compiling sounds like something I hear real programmers complain about that I'm glad I never have to deal with.

I think I'll pass on this one.

**Comment by alyosha-tas** [comment]
In dev builds, the BizHawk.Emulation.Cores.resources.dll file can be found in dll -> net48

I don't know if this has any relevance, just thought I'd point this out,

**Comment by adelikat** [comment]
Ok, I fixed it by renaming to .rom, it's really weird that this was necessary, it seems to be an assembly resource loading bug.
