### ISSUE TITLE
DSHawk - Lowest part of touch screen doesn't work

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1904]
This part of thouch screen doesn't get the clicks (under the red line):

![screen](https://user-images.githubusercontent.com/20956021/77833990-adbed880-7141-11ea-9f82-9b58121b3029.png)

**Comment by zeromus** [comment]
This is caused by calibration data that doesn't match the emulator. I'm not sure whether upstream is emulating this in the best possible way, such that it could be fixed, but if you use the gamepad to launch the calibration in the firmware, you will see that you CAN touch lower points. Of course actually using the newly calibrated data requires saving modifications to the firmware file as a delta. Desmume does this in an obtuse way, but it should be done for us with an xor on the total firmware file, and melonds does not actually have to know anything about it. 
As a practical matter, I recommend NOT supporting people @*#(ing around in the firmware for no @*#(@ing good reason, because it's a pointless hassle.

**Comment by Real96** [comment]
i tryed the calibration and it worked, but after rebooting it wasn't saved as you said

**Comment by zeromus** [comment]
Yeah, I'm not in charge of this core, but if I was, I'd mark it as "not supported, not worth the trouble"

**Comment by SuuperW** [comment]
I can use the touchscreen to select buttons at or near the bottom of the screen. (e.g. the little DS icon at the bottom-center in the screenshot you posted)
I also tried with a brand-new config. I can get through the firmware's initial setup with only the touchscreen. Using a new config shouldn't matter though, since MelonDS overwrites the touchscreen calibration settings on boot. (after BizHawk injects your saved settings)

I don't know why you might be having issues with this.

**Comment by zeromus** [comment]
then the calibration information in your firmware is different. there is no standard firmware. if nothing else, the mac address stored in it differs. Everyone is using a different firmware file and the calibration values differ.

**Comment by Real96** [comment]
Don't know it this can be related, but i'm getting an orange question mark when i try to import the firmware.bin. bios7 and bios9 get the green check instead. Can be this also be a problem?

**Comment by SuuperW** [comment]
If there is a green check mark next to the firmware file in the Firmwares dialog, when using a brand-new config, you will have exactly the same firmware file loaded by MelonDS as everybody else, since BizHawk overwrites user settings data before MelonDS ever sees it. (and everything not overwritten is included in the calculated hash)

(side note: MelonDS generates a random MAC address upon boot, so that will be different from person to person after bootup)


@Real96 Yes, if you get an orange question mark your firmware is probably bad.

**Comment by zeromus** [comment]
That **defines** the problem. It means your firmware is different from the one that was arbitrarily chosen. The one that was arbitrarily chosen is the one that has calibration data compatible with melonds. You must find this same arbitrarily chosen firmware if you insist on @#()ing around in the firmware for no @*(#@ing good reason

**Comment by Real96** [comment]
> If there is a green check mark next to the firmware file in the Firmwares dialog, when using a brand-new config, you will have exactly the same firmware file loaded by MelonDS as everybody else, since BizHawk overwrites user settings data before MelonDS ever sees it. (and everything not overwritten is included in the calculated hash)
> 
> (side note: MelonDS generates a random MAC address upon boot, so that will be different from person to person after bootup)
> 
> @Real96 Yes, if you get an orange question mark your firmware is probably bad.

Did you generate it or did you extract the bios from the console?

**Comment by zeromus** [comment]
It was obtained by a process you will have to ask the internet for details on how to replicate.

**Comment by Real96** [comment]
I'm not being able to get the green checks. I also extracted bios+firmware from console but always getting red marks, i have to clicl Set Customization to get the orange check...

**Comment by zeromus** [comment]
The bizhawk devs did not extract bios+firmware from YOUR console, so YOUR files do not match THEIR files.

**Comment by Real96** [comment]
> The bizhawk devs did not extract bios+firmware from YOUR console, so YOUR files do not match THEIR files.

Absolutely! But it is a matter of fact of getting a good firmware.bin anyway
