### ISSUE TITLE
LUA memory leak when using events

### ISSUE THREAD

**Issue by Felk** [TASVideos/BizHawk#1920]
### Summary
Bizhawk seems to leak memory, possibly LUA objects, when code gets executed through an event callback.

### Repro
leaks fast:
```lua
local function game_loop()
    for i=1,1000 do
        joypad.get()
    end
end
event.onframeend(game_loop)
```
does not leak:
```lua
while true do
    for i=1,1000 do
        joypad.get()
    end
    emu.frameadvance()
end
```

### Host env.
- Bizhawk 2.4; Win10 Pro 10.0.18369

a quick diff between two memory snapshots in visual studio suggests that loads of lua objects get created, of which I couldn't find some that don't eventually end up in a reference loop ("Schleife ermittelt" = "loop detected" in the screenshot):

![grafik](https://user-images.githubusercontent.com/1996138/78997039-26f8fb00-7b46-11ea-9cc4-503c45cd160f.png)

**Comment by adelikat** [comment]
Is this with Nlua or LuaInterface?

**Comment by Felk** [comment]
> Is this with Nlua or LuaInterface?

how do I tell? It's whatever is used by default when I load a script in the lua console window

**Comment by adelikat** [comment]
Config -> Customize -> Advanced Tab -> Lua Engine section

**Comment by Felk** [comment]
It's on "Lua+LuaInterface" and even says it has memory leaks. I did not expect memory leaks to be the default 😄

However, changing that to NLua did not change anything. It still leaks memory.

**Comment by whiteted-strats** [comment]
Hopefully this is the same issue. 2.4.0 hangs shortly after I start this script on Goldeneye:

`local function callback()
    
end

event.onmemoryexecute(callback, 0x7f058258)
`

The address is near the end of the main matrix multiplication function so is probably being called quite a lot. Changing to NLua makes no difference, and I have the same issue in 2.2.2

**Comment by adelikat** [comment]
^ This is a different issue, please report separately.

**Comment by adelikat** [comment]
I did some research on this issue and it happens anytime lua calls into a function that returns a table, while in a callback, and even then only if there is not a loop with emu.frameadvance()

just adding
while true do
	emu.frameadvance();
end
to the provided script "fixes" the memory leak.  The reason is the table returned needs to be disposed.  emu.frameadvance() calls _lua.RunScheduledDisposes(); which will clear out any tables in need of disposing.

However, there is no opportunity to dispose if everything was registered with callbacks and no emul.frameadvance.

I'm not sure what the clean fix is either.  We could use ScheduledDisposes anytime a luatable is created, but it will only dispose anything previous to the table being created.  We would be avoiding a memory leak simply by assuming that another table will be created before things get out of hand.
