### ISSUE TITLE
ENG input method added

### ISSUE THREAD

**Issue by lucameat** [TASVideos/BizHawk#1923]
I'm using BizHawk on Windows 10 and I noticed that after opening a Nintendo 64 rom, the english keyboard is added to the input methods.
That is, before I open Super Mario 64, my system tray is like this:
![biz1b](https://user-images.githubusercontent.com/43494463/79047982-2e89d400-7c1a-11ea-80ec-b7b0829710ff.png)

After opening the rom, the system tray is like this:
![biz2b](https://user-images.githubusercontent.com/43494463/79047988-3a759600-7c1a-11ea-8962-34fe3e85b474.png)
My normal keyboard is ITA but, as you can see, the ENG keyboard is added.
When I open roms on all the other platforms this doesn't happen.

**Comment by zeromus** [comment]
use a different graphics plugin besides gliden and see if it fixes it

**Comment by lucameat** [comment]
I have tried Rice, Glide64, Glide64mk2, GlideN64, but nothing changes. I don't know much about it, but it seems to me more a problem related to input than to graphics.

**Comment by zeromus** [comment]
Can you test a new version of the separate mupen emulator, and also a 3, 6, and 9 years old version of mupen to see which of them do the same thing?

**Comment by lucameat** [comment]
Too much work for me. I can very well live with the issue. Thanks anyway.

**Comment by zeromus** [comment]
OK. For the record, this issue affects other people in other programs, and I have not been able to find out why it's happening for anyone else. It seems like it would be relatively easy to understand if one could build an affected software on an affected system and chop it down over and over until the problem disappears. But bizhawk would be harder to do this in than another typical program, for various reasons. So any other open source program that's affected would be a good candidate for solving this, by a programmer who can reproduce the problem on a system. I suggested mupen because the problem must be in mupen's code and a proper version of mupen probably does still have the same problem.
