### ISSUE TITLE
[melonDS] app crashes when trying to open .nds rom

### ISSUE THREAD

**Issue by Real96** [TASVideos/BizHawk#1928]
Last commit (a57d09f) crashes when you try to open any .nds rom (i tryed drag drop or File > Open ROM)
I get always this error: https://pastebin.com/qbmRyNDq

**Comment by SuuperW** [comment]
fixed with commit 7336217
Was caused by a default rendering scale factor of 0. I thought I had code to handle that in the melonDS build, but it apparently only works if scale factor is set to 0 after previously being set properly?

A later version of libmelonDS should have this fixed, but I don't think I'll push a new dll just for this.

**Comment by Real96** [comment]
It still crashes t.t no error this time....
