### ISSUE TITLE
Pokemon Red and Blue

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#1973]
How i can transfer my pokemons from this game to the Pokemon Yellow? It say's "Link connection is currently disabled" (near "Gambatte" core icon)

**Comment by ThunderAxe31** [comment]
1. Tools > Multi-disk Bundler > System > GB
2. Click on "Browse..." in the upper right in order to decide where to save the .xml file
3. Click on the other two "Browse..." button to select the respective ROMs you wish to use
4. Click on "Save and Run"
5. Set your input keys in Config > Controllers...
6. Next time you open BizHawk, execute the .xml file like if it was a ROM file. Don't move or delete the ROMs you used, otherwise you will need to create a new .xml file.

**Comment by medigi** [comment]
This looks like the only way, tried 2 bizhawk's launch at same time but with different roms.
![Снимок](https://user-images.githubusercontent.com/21311432/80916088-42c77980-8d5f-11ea-8659-304edeb2e6e7.PNG)

**Comment by YoshiRulz** [comment]
You must use the Dual*, *3x, and *4x cores (triggered by loading an `.xml` spec as described above). Linking across EmuHawk instances is not planned.

**Comment by hawkiq** [comment]
> 1. Tools > Multi-disk Bundler > System > GB
> 2. Click on "Browse..." in the upper right in order to decide where to save the .xml file
> 3. Click on the other two "Browse..." button to select the respective ROMs you wish to use
> 4. Click on "Save and Run"
> 5. Set your input keys in Config > Controllers...
> 6. Next time you open BizHawk, execute the .xml file like if it was a ROM file. Don't move or delete the ROMs you used, otherwise you will need to create a new .xml file.

So this only on GB not for GBA ?

**Comment by nattthebear** [comment]
> So this only on GB not for GBA ?

Correct
