### ISSUE TITLE
Opening a TAStudio file from `File > Movie > Recent` has problems

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2025]
Opening a movie like this works, but it doesn't immediately open TAStudio (probably should, because you can always export to bk2 if you want to play a movie normally).

Also, it doesn't respect some of the normal rules of playing a movie, probably because it's in TAStudio movie playback mode instead of normal movie playback mode. For instance, `File > Movie > On Movie End` is not respected and the movie continues playing back even if the settings indicate it should be paused.

I suppose TAStudio files could be excluded from the recent menu, but I find it useful to see recent TAStudio files I opened without having to open TAStudio and start a default project first. Still, since opening TAStudio itself is a workaround, perhaps TAStudio files shouldn't be in the standard movies recent list, and only in the TAStudio recent list.

**Comment by adelikat** [comment]
I fixed it so that a .tasproj loaded this way respects the movie end.

It is absolutely intentional that tastudio does not automatically open.  a .tasproj is perfectly capable of operating with the traditional recording method, and this is the way to do so (or to simply watch a movie without having the overhead of tastudio open)
