### ISSUE TITLE
Robopon - Sun Version (GBC) not loading

### ISSUE THREAD

**Issue by medigi** [TASVideos/BizHawk#2065]
Error message: "load error. Failed multiple attempts to load ROM"

**Comment by zeromus** [comment]
use GBHawk. 
@TiKevin83 it's due to gambatte missing HuC3 mapper. If this needs to be added ourselves (I see libretro gambatte has it but i dont know if it's in-house or from upstream) then we can leave this ticket open to add it; otherwise, it's from upstream and we dont need to track it since everything will be updated ,eventually.

**Comment by TiKevin83** [comment]
I can probably add the huc3 mapper over the next few days, it's supported in Gambatte-Speedrun which is mostly the base for bizhawk's gambatte now.

**Comment by nattthebear** [comment]
If one possible core option threw an exception on loading, but another core option will work, but wasn't used, that's a bug in our Romloader

**Comment by zeromus** [comment]
As long as it prints a warning that it chose another core, it sounds fine to me

**Comment by TiKevin83** [comment]
This is fixed in #2091
