### ISSUE TITLE
Gambatte doesn't work with BIOS enabled set to false

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2067]
Load up a game, nothing displays, no sound. Trace logger indicates initial state is wrong.

**Comment by nattthebear** [comment]
So fix it, shithead.

You broke it in the first place.  You know what the fix is.  You have the code.  Go fucking do it.

**Comment by adelikat** [comment]
@nattthebear: this behavior is completely inexcusable.  I don't think a gameboy bios  requirement is a reason for slinging insults.  Grow up.

@alyosha-tas: for some context, we do want the ability to not require a bios for gameboy.  The reason being is that the accuracy difference is academic, and not requiring one worsens the user experience (particularly since no other gameboy emulator requires this).  Whatever changes were made to gambatte that prevent no-bios as a workable option need to be adjusted.

**Comment by nattthebear** [comment]
@adelikat You confirmed directly to me in IRC that:
- Gameboy functioning without BIOS is important part of Bizhawk functionality, and you would like it to be in the product
- You were not even aware that @alyosha-tas had removed that capability
- You wanted the capability to be reinstated immediately

While @zeromus was not quite so wordy, he agreed with the principles.  So between the two of you, those are all of the active leaders of the project, and you're in unanimous agreement.  At what point does it stop being OK for rogue committers to ninja remove features against the wishes of the project owners?  At what point do you start steering the project instead of leaving `master` branch as a cage match?  I'm frustrated, but I have good reason to be.

**Comment by alyosha-tas** [comment]
BIOS requirement came from c6bdae9 when I merged a branch from gifvex that brought our Gambatte core in line with upstream. Old Gambatte core didn't have a BIOS option, and the initial state was the GBC state after write to BIOS disable. (I tried and failed previously to add BIOS, but ultimately removed it.) New Gambatte core only has zero initial state. It's also significantly more involved and includes RTC support, and support for old GB mode. I'm not sure if the initial GB state after BIOS is resolved to the same detail as the GBC one was, it certainly didn't exist previously. I'm also not sure what to do with RTC for no BIOS. Maybe it doesn't matter for casual play. Anyway, this is not just a 'turn it back on' issue (unless you just hack in PC = 0x100 and hope for the best.)

**Comment by nattthebear** [comment]
The commit you linked is a one liner lua change and has nothing to do with this.  RTC always worked in Gambatte, long before anyone had even dumped a bios from a real gameboy.  I just checked [upstream](https://github.com/sinamas/gambatte) and it does not have any bios capability at all (cpu.h and memory.h both have absolutely nothing in them.)  So uhh, anything else you need me to fact check for you?

**Comment by TiKevin83** [comment]
natt, the gambatte core's upstream should be considered gambatte-speedrun at this point, which is where the bios requirement likely comes from.  However, I'm not sure if or why it's strictly required in the BizHawk port, I was planning on looking at the Robopon issue today.

**Comment by TiKevin83** [comment]
I believe Alyosha meant to refer to commit e5ded9b , this merge was done for the accuracy necessary for the Blue NSC TAS to sync.  If BizHawk really needs a no BIOS mode, it could potentially be wired in with a custom setInitialState that mimics the state after the BIOS boots to allow casual play without jeopardizing the accuracy of TASes.

**Comment by nattthebear** [comment]
ad16294

**Comment by ThunderAxe31** [comment]
There are new issues in the latest devbuild (2020-06-16-161533):
1) The SameBoy BIOS doesn't work for any GBC game. Depending on the game, it either freeze or corrupt graphics badly.
2) The SameBoy BIOS is used when playing a movie made with a previous BizHawk version, which leads to desyncs.
3) Using the official BIOS should be enforced for recording any GB and GBC movie, like it used to be before (and it still does for GBA).

**Comment by nattthebear** [comment]
>     1. The SameBoy BIOS doesn't work for any GBC game. Depending on the game, it either freeze or corrupt graphics badly.

Cannot reproduce.  I tried 007: The World Is Not Enough, Elmo's ABCs, and Rayman 2.

>     2. The SameBoy BIOS is used when playing a movie made with a previous BizHawk version, which leads to desyncs.

If you're trying to resync an old movie, you'll need to modify the syncsettings to give you the values you want.

>     3. Using the official BIOS should be enforced for recording any GB and GBC movie, like it used to be before (and it still does for GBA).

This is implemented through the profile system.

**Comment by ThunderAxe31** [comment]
> > 1. The SameBoy BIOS doesn't work for any GBC game. Depending on the game, it either freeze or corrupt graphics badly.
> 
> Cannot reproduce. I tried 007: The World Is Not Enough, Elmo's ABCs, and Rayman 2.

None of them work to me. I downloaded the debuild I mentioned, and I didn't change any setting.

> > 3. Using the official BIOS should be enforced for recording any GB and GBC movie, like it used to be before (and it still does for GBA).
> 
> This is implemented through the profile system.

We still don't want to allow that, regardless of the profile chosen by the user. Even if an user picks a non-TASing profile, that doesn't necessarily mean that they will never decide to make a submittable TAS at some point. It would eventually lead to submissions getting rejected by default just because the author forgot to set the required sync setting. We don't want people to lose their motivation to contribute to the site just because of a misleading feature in the emulator. We already had a [case of submission](http://tasvideos.org/5613S.html) getting rejected just because BizHawk mistakenly used the wrong Saturn BIOS localization for recording a movie, and then that author never TASed that game again.
If you think about it, I'm not asking you to remove a feature. Actually, I'm asking you to implement a more important one on top. Implementing this requirement is in all interests of the user themselves, before than the site. So far, I've never seen anyone complaining for the lack of the ability of recording movies without a BIOS, but on the other hand I can tell in advance that there will be incidents if this doesn't get enforced like before. As much as people may enjoy to have the ability to play a game without having to look around for the required BIOS, I don't think that it would be too much to ask them to do it for recording movies, as since they already got the ROM of the game itself, I don't think that that would be too much trouble for them.

**Comment by YoshiRulz** [comment]
>> GBC doesn't work on 51a83193a
>>
> CNR, 007: The World Is Not Enough works
>
I can load at least that game (SHA1:`DD6E952B730C4BD85F8734156D43A2616B68C053`) on that dev build with a clean config, no firmwares set. There's the SameBoy logo, then some copyright notices and logos, then a nice 007 cinematic and the title screen.

---

>>> Using the official BIOS should be enforced for recording any GB and GBC movie
>>>
>> This is implemented through the profile system.
>>
> We still don't want to allow that, regardless of the profile chosen by the user. Even if an user picks a non-TASing profile, that doesn't necessarily mean that they will never decide to make a submittable TAS at some point. [...] We already had a case of submission getting rejected [...]
> As much as people may enjoy to have the ability to play a game without having to look around for the required BIOS, I don't think that it would be too much to ask them to do it for recording movies, as since they already got the ROM of the game itself, I don't think that that would be too much trouble for them.
>

Input movies are not the same thing as tool-assisted runs. Casual players are free to use the faster cores / HLE BIOS / whatever, but for TASers, the TASVideos submission rules are law (the relevant part being ["only use real BIOSes"](http://tasvideos.org/MovieRules.html#BiosMustBeReal)). I'll leave debating the rules, and whether they discourage submission, to the TASVideos judges among us. (I also disagree with "if someone can dump a game, they can dump the BIOS", even if you take "dumping" to mean something else.)

Putting all that aside, there's a pragmatic reason not to require firmware for movies: it would add complexity to the movie subsystem.

**Comment by ThunderAxe31** [comment]
I've just done more tests, it seems the SameBoy BIOS issues happens only if GBC in GBA is set to False.

Regarding the movie recording matter, I understand that you still don't want to enforce the original BIOS, but would you at least put a warning popup for when an user starts recording without? Pretty please.

**Comment by nattthebear** [comment]
Sure you didn't have that backwards?  Known issue right now that Gambatte + Sameboy bios + GBC in GBA true doesn't work

**Comment by ThunderAxe31** [comment]
Yeah, I got that backwards. I fixed my previous comment, sorry.

**Comment by nattthebear** [comment]
Cool, captured that one here https://github.com/TASVideos/BizHawk/issues/2100

I don't have strong feelings about movies but I'll let the politicians decide what to do

**Comment by vadosnaprimer** [comment]
> Input movies are not the same thing as tool-assisted runs. Casual players are free to use the faster cores / HLE BIOS / whatever, but for TASers, the TASVideos submission rules are law (the relevant part being "only use real BIOSes"). I'll leave debating the rules, and if they discourage submission or not, to the TASVideos judges among us.

You're making it sound like "TASers aren't the only users of bizhawk, therefore TASers are low priority". Even though it sounds silly, I'd be interested in seeing some statistics that may back up either approach. For example, [here's a list](http://tasvideos.org/Movies-TypeB2-TypeBK-Obs.html) of all bizhawk movies that have been published at tasvideos. 983 movies where the user explicitly wants TAS profile, but may not necessarily know
* that it's even a thing
* that it's off by default
* what exactly it affects
* what the consequences may be of accidentally forgetting to turn it on.

Does anyone have a statistically relevant number of non-TAS bizhawk movies where determinsim and accuracy was not desired? If that number is so big that it makes the TAS-related numbers look vanishingly small, mostly an exception, then by all means we should focus on those people primarily. Until someone provides such statistics, **I'd prefer that we default to TAS needs once one decides to record a movie.**

To deconstruct is even further:

> Input movies are not the same thing as tool-assisted runs

How exactly are you measuring the difference here, for bizhawk movies? Because they're absolutely identical to me, and all the basic TAS tools are available in both.

**Comment by ThunderAxe31** [comment]
I have an idea that can make everyone happy. We could make BizHawk to automatically use the GB or GBC BIOS if the file is found in the Firmware folder, otherwise it will silently fall back to using the SameBoy core. How does that sound?

**Comment by filpAM** [comment]
What?

Checking the Gambatte.cs code(lastest git commit) , it already does fallback to Sameboy bios if BIOS disabled..
