### ISSUE TITLE
Could use a bit more space for field names on the controller config

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2078]
Not sure what to do here, because some consoles have lots of tersely named buttons.

![image](https://user-images.githubusercontent.com/1824709/83350927-9d77d500-a30d-11ea-8647-83d864a0b38e.png)

The names of the problematic buttons are "P1 Mode: Set 2-button" and "P1 Mode: Set 6-button"

**Comment by adelikat** [comment]
Not an ideal solution, but I increased the width of the labels to account for the max label size.

Ideally it would calculate the max label size for the column instead of all buttons.  As a result, Saturn keyboard columns are pretty far spaced out when they don't need to be.  But at least everything is readable
