### ISSUE TITLE
Lua scripts stop progressing for cycles at 25 iterations

### ISSUE THREAD

**Issue by ThunderAxe31** [TASVideos/BizHawk#2082]
Happens in both latest release (2.4.2) and latest devbuild (2020-05-31-221337).
Try the executing the following Lua script:
```
for i = 1, 999 do
	console.log(i)
end
```
and you'll get the following output:
```
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
```

**Comment by YoshiRulz** [comment]
This is probably the new flood prevention, intended to affect exception messages in the Lua Console.

**Comment by vadosnaprimer** [comment]
Makes sense to ensure it's actually an exception then. Like by checking the starting string for example?

**Comment by ThunderAxe31** [comment]
I think you should at least implement a warning message, in order to inform the user that output has been limited. Otherwise some people may think that the cycle is not being executed, when the output is used as feedback for debugging a script. That's literally how it happened to me, and why I thought that the cycle was not getting executed beyond the 25th iteration.

**Comment by adelikat** [comment]
Are you sure this is cap related? the cap is 50... https://github.com/TASVideos/BizHawk/blob/master/src/BizHawk.Client.EmuHawk/tools/Lua/LuaConsole.cs#L516

**Comment by YoshiRulz** [comment]
Lowered the cap to 30 and it stopped printing after the 15th.

**Comment by adelikat** [comment]
So to address this issue I did a few things:
1) reduce actual calls to the output box so it is only 1 call per intended command (the examples above were hitting the box twice, hitting the max and costing performance)
2) Since performance is boosted, I bumped the max to 100 (effectively a 4x increase)
3) Put in a warning message when limit has been reached
4) clear the counter when inputting commands into the console window
