### ISSUE TITLE
ffmpeg crashes (screen shot attached)

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2101]
ffmpeg crashes (screen shot attached)

![Capture](https://user-images.githubusercontent.com/18354277/83880966-fc728b00-a70d-11ea-8b05-c51aa698bbcc.JPG)
![Capture2](https://user-images.githubusercontent.com/18354277/83880976-ff6d7b80-a70d-11ea-9f35-37f0d8aea01a.JPG)

**Comment by ChutacoackoPlayz** [comment]
I also found that

**Comment by nattthebear** [comment]
In the latest development releases, we ship a file called "Version.dll".  We must not do that.  We must not ever ship a file with the same name as a well known Windows system dll.  That is the problem here, and removing that file fixes ffmpeg.  Does anyone know enough about the buildscripts to figure out how it got there?

**Comment by jjfmz42015** [comment]
> In the latest development releases, we ship a file called "Version.dll". We must not do that. We must not ever ship a file with the same name as a well known Windows system dll. That is the problem here, and removing that file fixes ffmpeg. Does anyone know enough about the buildscripts to figure out how it got there?

Deleting version worked! Thanks.
