### ISSUE TITLE
Hiccups in turbonyma when rewind is enabled, due to epic >3GB GCs (test in Final Soldier)

### ISSUE THREAD

**Issue by ghost** [TASVideos/BizHawk#2104]
So since I found out about TurboNyma I been playing as my TG16/PCE as I can testing and enjoying.

Today I went to play final soldier. Tested on like 7 builds even latest one. the odd time it jitters vertically almost like a vsyn problem.

Tested on 3 computers all with nothing at all incommon.

the i tested on the latest official mednaffen no jitter ever at all.

if you play one level you will get approx 5 to 7 jitter. very subtle but if you are picky you will notice.

reproducable 100% of the time.

**Comment by jjfmz42015** [comment]
did more testing sure enough in many games where there is alot going on scrolling will seem not smooth at times using TurboNyma.


Here is my tests.

Official Mednafen smooth
Bizhawk with PCEHawk SMooth
Ootake smooth
Magic Engine 1.13 smooth

Bizhawk with TurboNyma and Turbo Turbo Nyma the odd skip.

Best game to test with Final baster as it happens multiple times per level.


Not complaining just reporting.


I dont understand how waterboxing works but this is either memory limit or graphics api I assume.

tested on may systems, on win 7 and 10

big cpu big video card big ram.

**Comment by jjfmz42015** [comment]
narrowed down. its a rewind issue...

**Comment by jjfmz42015** [comment]
disable rewind solved issue

**Comment by YoshiRulz** [comment]
Rewinding with TurboNyma works out-of-the-box as of 03d10cebb, I'd say natt fixed it since you tested it. If you run into more issues with rewinding we can re-open this.

**Comment by zeromus** [comment]
Issue fixed by "disable rewind" is not fixed

**Comment by jjfmz42015** [comment]
I have done more testing. default rewind settings. try this game you will start to notice sticking the odd time per level 100% of the time.

However if I disable use delta compression problem goes away.

Im an IT manager with access to ALOT of hardware.

I tried throwing this at some VERY VERY high end systems. And it still happens.

If there is anything I can do to help rove this or test let me know. 

If you guys can test it out and see what happens.

The strongest system i tested on i9-109000k with 32 gb ram

the weakest system i5-4570 with 8 gb of ram

So I dont think its that my system is too weak.

For me a simple solution I just leave delta off for now.

This happens in other games. Im mentioning final soldier as here it is easy to notice every time.

if you do a full level one play through with it on vs with it off you will notice for sure.


hope what im saying helps, and once again thanks for this emulator!

**Comment by zeromus** [comment]
I doubt anyone knows what you mean by "5 to 7 jitter". Can you please describe it differently, in more detail?

**Comment by jjfmz42015** [comment]
ok, sorry, let me try. this game i recommend testing with is a vertical shooter, when operating properly it scrolls smooth, every couple of minutes it will almost stick, both audio and visual for a second or less. I believe this is occurring when the rewind save is written or dumped. if i take the default value of 128mb rewind and make it lets say 1024mb this can amplify the problem and make it super noticeable.

Im only reporting this as I belive the systems I am using should be strong enough to handle it so im assuming there may be a bug??

**Comment by jjfmz42015** [comment]
other than this the Nyma cores are running beautifully

been testing alot here

**Comment by zeromus** [comment]
by default the rewind is not written or dumped. If it was, it wouldn't happen when the buffer was full, so the buffer size wouldn't matter.

By default, turbonyma shouldnt' even be enabling rewind!!! Due to the state size being larger than small (357KB vs 256KB limit) However, due to a BUG seemingly, (@nattthebear @adelikat  ?) it's getting rewind enabled anyway (initial frame savestate size wrong?)

Anyway, I believe you have changed the rewind options or else as a sysadmin you have installed junkware on all the systems you administer which is monitoring processes and making garbage collection slow or making hot cpus throttle down. I am incredibly skeptical that your analysis on this problem is good. I suggest you keep investigating.

**Comment by jjfmz42015** [comment]
> by default the rewind is not written or dumped. If it was, it wouldn't happen when the buffer was full, so the buffer size wouldn't matter.
> 
> By default, turbonyma shouldnt' even be enabling rewind!!! Due to the state size being larger than small (357KB vs 256KB limit) However, due to a BUG seemingly, (@nattthebear @adelikat ?) it's getting rewind enabled anyway (initial frame savestate size wrong?)
> 
> Anyway, I believe you have changed the rewind options or else as a sysadmin you have installed junkware on all the systems you administer which is monitoring processes and making garbage collection slow or making hot cpus throttle down. I am incredibly skeptical that your analysis on this problem is good. I suggest you keep investigating.

by default i assure you it is enabled

unzip a fresh copy run it enabled

no my friend no junkware. the system im on this second is clean as clean gets. I noticed a issue and reported it.

the system i just tested on now 52 processes, no monitoring apps,

one of the systems i tested on was fresh windows install, drivers, bizhawk pre req install, bizhawk and that is it.

if you guys want test it and see. im not a novice when it comes to this i assure you. 

I ran task manager, processes, cpu usage. it peaks around 23% on the system i did this test on. 23% peak cpu usage shouldn't be enough to cause a cpu to pause and cache.

anyway if there is a way i can help let me know otherwise moving on.

**Comment by zeromus** [comment]
This time, when I actually tested Final Soldier (pause the game and it will scroll AND blink the paused text every frame, so you can see it hang if there's a freeze glitch) the rewind was NOT enabled. So we still have a problem there (not sure why my first test was saving when medium was disabled). Enabling medium savestates made it work, as expected. 

Now, I had a 1024MB buffer and watched emuhawk get up to > 3GB of memory (sometimes over 4GB!) before the GC kicked in. WHETHER OR NOT delta was enabled (this is why I thought jjfmz's investigation made no sense). So we may have a problem with buffer churning in these nyma cores.

I'm sorry I insulted your sysadminning skills. But your analysis is is not skilled: 23% peak CPU usage may come from _completely freezing_ an otherwise 1% CPU usage process (as this emulator core is, even with rewinding and delta) for 1/4 of a second. Nevertheless, the system power is not to blame.

**Comment by jjfmz42015** [comment]
Dont worry im not insulted, i need to work on my communication skills. Another observation. Nyma core seems to do this less using xaudio2 vs direct sound. Dont know if this is coincidental. 3 am here. Will test it more tomorrow. I need to figure out what i can do to help with testing this.

Only reason im noting 23% as it tells me cou should be throttled or paused. However is higher than it should be.

To be honest i plan to test this core inside out if possible.

If there are certain ideas of what i can do to be useful in testing please let me know.

Last but not least thank you guys. I am so happy with these nyma cores already and truly appreciate what you guys do.

**Comment by zeromus** [comment]
If you want to test new sources of GC hiccups, test them isolated from other known sources. For instance, turn OFF rewind then see if changing audio plugin affects hiccup frequency

**Comment by jjfmz42015** [comment]
> If you want to test new sources of GC hiccups, test them isolated from other known sources. For instance, turn OFF rewind then see if changing audio plugin affects hiccup frequency

The reason I initially blame delta Is i simply turned off delta and played final soldier in one sitting from beginning to end using rewind the odd time to cheat getting hit and progress and i didnt experience a single hicup.  To be honest did this twice.

The second i re enabled delta hicups return. Maybe my next test will be play with delta and see cou usage and memory usage in task manager vs lay without and compare?

**Comment by zeromus** [comment]
Re-test rewind and learn how to correlate the memory usage to the lag spikes. See how the memory goes up until it lags and the memory drops back down. Then you will know what to look for in other places.

**Comment by adelikat** [comment]
I don't know why the arguing here @zeromus, this bug is legit
Right now, rewind is basically broken with any nyma cores.  

The only way rewind knows a state is "small", m"medium" or "large" is from the initial state, so it might think a core uses "small" state when it doesn't, thereby enabling it.

Secondly, because states vary in size, the static buffer approach isn't used, so you see the memory churn and the inevitable stutter when it releases memory.  GPGX is another example of a core where this is easy to observe.

All this will be fixed by the next release, but it isn't so easy, and may take some time.

THank you for the bug report jjfmz42015, keep them coming

**Comment by nattthebear** [comment]
I'm going to grab this for now -- I'm working on some ideas in The Lab.

**Comment by jjfmz42015** [comment]
@zeromus is just teaching me so i can help test. Thank you guys

**Comment by nattthebear** [comment]
@adelikat can this be closed now?

**Comment by adelikat** [comment]
With the new rewind system, this problem should be gone now.  I tested and it doesn't have the sudden major garbage collections, and runs smoothly (and faster than the old one).

Closing this issue, feel free to reopen it if you test and find there is an issue.
