### ISSUE TITLE
PSX reported ideal FPS is way off (NTSC)

### ISSUE THREAD

**Issue by nattthebear** [TASVideos/BizHawk#2138]
Nominal NTSC field rate is about 59.54fps.  Many game systems vary from that and there's some tolerance for wrongness in the system, but even things like NES only venture as far as 60.1fps.

Bizhawk's PSX core reports a nominal rate of about 59.3fps, 7 times the error of an NES!  That's simply not believable; many real TVs would have failed to sync to it.  [Mednafen's own interfaces provide a nominal framerate of about 59.94 for this core](https://github.com/TASVideos/mednafen/blob/740d63996fc7cebffd39ee253a29ee434965db21/src/psx/gpu.cpp#L183), but Bizhawk ignores that.  We also have [reports from users ](https://github.com/TASVideos/BizHawk/issues/1398#issuecomment-447577561) that the actual framerate (taken by measuring actual samples dumped per video frame during emulation output) is quite close to 59.94, and not at all like 59.3.

Please fix this so Spikestuff will stop bitching at me about how bad alternate sync dumping is.

**Comment by nattthebear** [comment]
Spoke with the mednafen team on this, and this is their best knowledge for exact NTSC framerate of PS1:

Progresso:
`44100*768/(3412.5*263*65536/103896)`
59.8260456273

Shoelaces:
`44100*768/(3412.5*262.5*65536/103896)`
59.9400000000

**Comment by Spikestuff** [comment]
Over the period of time the method chosen gets away from real hardware and upstream itself (even upstream is wrong).

Watch the clip I'm providing first before going to the images so you know what's being looped: https://youtu.be/JULGQII9Up8

Here's a still frame after the first time round since the clip doesn't make it apparent:
![1loop](https://user-images.githubusercontent.com/12412764/91689101-c88cf180-eba6-11ea-8dc7-999036e62269.png)

Rpeating the same clip 10 times (10mins, 26secs) it should get more noticeable:
![10loops](https://user-images.githubusercontent.com/12412764/91689113-ccb90f00-eba6-11ea-84ed-3e331af0a8b7.png)

And after 100 loops (1hr 44mins) well it's more apparent now. Even mednafen gets away from real hardware.
![100loops](https://user-images.githubusercontent.com/12412764/91689126-d0e52c80-eba6-11ea-94bc-dafc835a3ef7.png)

**Comment by zeromus** [comment]
simply ffprobe the videos dumped by bizhawk and mednafen and make sure the time metrics are the same. if they are, then the videos are the same and your video player is wrong, or bizhawk is missing frames which is quite unlikely. Nobody cares if mednafen timing differs minutely from hardware, since it doesn't and can't promise to be perfect.

**Comment by Spikestuff** [comment]
Yeah my bad on that one @zeromus. Needed audio throttle enabled and basically jumped to conclusions fairly quickly.
