### ISSUE TITLE
Unhandled exception when trying to open TAStudio with a gba rom open

### ISSUE THREAD

**Issue by Liger0** [TASVideos/BizHawk#2147]
[//]: # "This issue description supports Markdown syntax (this is what comments look like). There's a cheatsheet here: https://guides.github.com/features/mastering-markdown/"
[//]: # "You can leave these comments here or delete them. Also, please remember to search for similar issues before writing anything, including in closed issues!"
[//]: # "One more thing: if you're on Linux, please comment on #1430 instead of opening an issue so we don't annoy the other devs."

### Summary
Emulator throws multiple unhandled exception when you try to open TAStudio with a gba rom loaded

### Repro
[//]: # "If you can't figure out the list of steps, delete this section and put 'heisenbug' in the summary somewhere. If a Lua script can cause the bug, you can embed that instead (as simple as possible please)."
1. Load GBA Rom
2. Tools -> TAStudio
3. No Bios warning
4. Unhandled exceptions cascade

### Host env.
[//]: # "List the computers you've found the bug with. If there's a version that doesn't have the bug, please put that in too. Here are some examples:"

- BizHawk dev build pre-2.5 (commit 01e3a6cf4); Win10; AMD

**Comment by RetroEdit** [comment]
I think the issue is that Liger0 didn't have a GBA bios in the firmware folder, and TAStudio handled that really inelegantly in the dev builds. It's not a "cascade" of errors, just two errors.

First the standard missing GBA bios error: `System.InvalidOperationException: A BIOS is required for deterministic recordings!`

And then an unhandled exception: `A core must be able to provide an IStatable service.`

And then a non-functional TAStudio window that's missing the input log will open, and it throws `Object reference not set to an instance of an object` if playback is attempted.

So I'd imagine it's possible mGBA depends on the bios for savestates (not technically, maybe a newer addition), but there's some onus on BizHawk to properly handle the exceptions and not open TAStudio at all, in my opinion.

**Comment by adelikat** [comment]
.bk2 movie recording doesn't handle this well either.  If you go to record a new movie, without a bios, it will leave you with Null emulator, and a recording movie.
