### ISSUE TITLE
Movie Récord RTC games Issue

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#2161]
Hi Friends when you start movie Récord of a game that used the RTC time this not work example boktai, Pokémon Esmerald, it not movie Récord the RTC work Fine There a Way to Enable The RTC inside Movie Record

**Comment by DarkLegend1987** [comment]
That affect all versión of bizhawk 1.13 to 2.4.2

**Comment by RetroEdit** [comment]
Since there are movies that rely heavily on the RTC, e.g. [merrp's Pokemon Emerald](http://tasvideos.org/6616S.html), I'm not sure how it could be broken in all versions. I think you'll need to explain how you know RTC time is broken for this report to be useful to developers.

Also, did you actually test for instance 2.4 and 2.3.2? Maybe it's a regression in 2.4.2 and it just wasn't implemented in the 1.13.

**Comment by DarkLegend1987** [comment]
In 2.4.2 mgba conf. Use Real RTC option enabled RTC start Time choose Today and when im start boktai the game not recognise RTC while im récord movie when im play game this start at nightime instead of daylight

**Comment by zeromus** [comment]
gba > settings > sync settings > RTC initial time
