### ISSUE TITLE
File system windows keep priority even when they're not in focus

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2182]
Whenever BizHawk presents a File Explorer window to save or load a file, it will always be in front. Even if I switch to another unrelated window for a moment (say, a web browser, as I'm using to write this issue), the window remains in front. This behavior is quite annoying; it should only remain in front of the BizHawk window, not take over that portion of the screen.

**Comment by zeromus** [comment]
see a30b89039fd0c32567594a31ec4d63ff2e22755b
why?

**Comment by vadosnaprimer** [comment]
There was some dialog that appeared when autoloading things and it kept hiding behind everything all the time, and you wouldn't even know it's there, because it's not in the task bar. It blocks hawk and you have to constantly dig through your other windows to finally notice that popup and close it.

If there's a way to make it on top of only hawk (at all times tho), I'd like to know. Don't remember what dialog it was anymore tho.
