### ISSUE TITLE
Boktai Trilogy solar gauge control

### ISSUE THREAD

**Issue by DarkLegend1987** [TASVideos/BizHawk#2218]
Hi when play boktai with daylight rtc the solar gauge remain empty and not have button mapped to control example in mgba emu you can map a button to increace and descrease solar gauge level in 2.4.2 the solar gauge remain empty

**Comment by RetroEdit** [comment]
Is the problem that create a control mapping to the daylight sensor in BizHawk isn't possible? Or are you pressing a button to change the daylight sensor with no result in BizHawk?

**Comment by DarkLegend1987** [comment]
No when is daylight light shades are on the floor to charge sunlight and outside and you press tehñhe button to absorb sunlight not work later profk9 create an ips patch to Fix this but the patch has a bug that disable RTC and i dont know how to récord a TAS of Boktai Saga

**Comment by endrift** [comment]
The game is supposedly supported without needing patches. Did you make sure to calibrate it properly? You need to have the solar sensor level be 0 when the game first initializes (or you can recalibrate later in settings).

**Comment by shenef** [comment]
This is a problem with the Solar Sensor Patch, it disables the Solar Sensor completely since otherwise the calibration would fail.
So, as endrift said, use an unpatched ROM.
To use the solar sensor you will have to bind it to an analog input. Unfortunately at the moment the full input range (0-255) is not available through any input method (#2323).
While TAS'ing you can manually input values in the input roll (0-200) or use the auto-hold tool in TAStudio (0-100).

**Comment by YoshiRulz** [comment]
Assuming PEBKAC and closing. Fix for above noted issue re: truncated range (#2323) is merged and will be in 2.5.
