### ISSUE TITLE
TAStudio: Emulation doesn't pause when clicking on the menues 

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2281]
As the title says. In the main BizHawk window emulation pauses when clicking on any of the menu items, but it continues when clicking on TAStudio's.

**Comment by YoshiRulz** [comment]
This behaviour is enabled with `Config.PauseWhenMenuActivated`, which is currently used only by `MainForm`'s window focus handler.

**Comment by adelikat** [comment]
Can not reproduce.

For me, if you have Config -> Customize -> Pause when menu activated = true
Both mainform and tastudio pause if you click a menu item

But if false,
then both do not pause

**Comment by YoshiRulz** [comment]
Read the issue again; the expected behaviour is that *emulation pauses* when *either menubar* is used, not *both windows pause* when the *`MainForm` menubar* is used. The latter doesn't really make sense for `IToolForm`s. As of e8bc7d50d, opening TAStudio's menubar with that setting enabled does not pause emulation.

**Comment by alyosha-tas** [comment]
Seems to work, thanks!
