### ISSUE TITLE
Truncating at frame 0 in TAStudio causes an ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2285]
Truncating at frame 0 to result in a 0-frame movie should be possible (with the cursor still at frame 0, i.e. not having ran through any frames). At the very least, it shouldn't cause an exception.

This was not an issue in 2.4.2.

Specifically, `Invalidate()` in ZWinderStateManger:

https://github.com/TASVideos/BizHawk/blob/6f5028bfcf7178e1f4ade80c3262fa2977a9d466/src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs#L285-L286

Called in the `Truncate` method here:

https://github.com/TASVideos/BizHawk/blob/6f5028bfcf7178e1f4ade80c3262fa2977a9d466/src/BizHawk.Client.Common/movie/tasproj/TasMovie.Editing.cs#L51-L54

`ZWinderStateManager.GetStateClosestToFrame()` also has a similar check:

https://github.com/TASVideos/BizHawk/blob/6f5028bfcf7178e1f4ade80c3262fa2977a9d466/src/BizHawk.Client.Common/movie/tasproj/ZwinderStateManager.cs#L224-L225

**Comment by nattthebear** [comment]
More off-by-one bugs?  🤣 
Remember that when a savestate is for frame N, that means that could be equivalently created by booting a brand new core, calling frame advance N times, and then savestating, so that the associated input log for that savestate has exactly N rows in it.

Or, put another way, the frame 0 savestate has no input log, and so would never have any reason to be invalidated.  Any code that tries to invalidate it is functioning improperly.
