### ISSUE TITLE
How to output lua pixel text to AVI?

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/BizHawk#2314]
Not use **Capture OSD**, because it will output non-pixel font to AVI and keeps window size resolution, I just want it to output native resolution (e.g. NES 256x240) with lua pixel text.
I don't know why screenshot could capture lua pixel text but AVI output couldn't, is there have a resolution to output lua pixel text to AVI?
Version: 2.4.2 stable

**Comment by RetroEdit** [comment]
`File > AVI/WAV > Capture OSD`

**Comment by RetroEdit** [comment]
Capture OSD inherently contains the scale because Lua can draw arbitrary things (keep in mind: non-pixel fonts change with scale). If you want to capture at 1x scale, you have to do `View > Window Size > 1x`.

I suppose we could have an option to try and restrict OSD to scalable components, but really it becomes a good bit of work that's probably not worth it.

**Comment by zeromus** [comment]
`gui.DrawNew("native")`
this isn't a discussion forum. Go to bizhawk forum on tasvideos for simple "how do I use bizhawk" questions

**Comment by RetroEdit** [comment]
This doesn't actually solve Yave Yu's problem as it is presented, because it only changes the Lua output size, not the screenshot size. We could provide an option to scale the OSD down to native even if the emulator window is higher-res. I'm not sure how complicated that would be, but I think my assessment yesterday is wrong. We could certainly provide another dependent option under `Capture OSD` called `Native res`.

Come to think of it, I would actually find that useful in certain cases. Though the easy workaround as I mentioned above is to just have the emulator window at 1x scale.

**Comment by zeromus** [comment]
To answer his question directly, I think there's no particular reason why screenshots work differently from movies other than that it's simply broken.

We need to reorganize it so you can capture either the "emu" or "native" layer (which might should be renamed to match the terminology used for screenshot, which is "raw" and "client" respectively, "native" being a particularly bad choice) and then have capture the OSD only on "client". I don't like your "scaling down" the OSD, and we won't be doing that. If needed (we should think this through clearly and come up with all the options anyone would need) we might have to add these options to the "configure and record" dialog (and we can add a little memo about what's selected to the record menu item: "Record Avi/Wav (Emu layer)" for example. Then you would pick the config option to save the changes. See, we already have "resize video" and "pad" stuff there too, so other sizing and compositing options should be there. I think it would be good if we can fix it so you don't have to go through the codec configuration process again while clicking ok, maybe...

**Comment by RetroEdit** [comment]
In reference to "scaling down" the OSD, I was thinking more along the lines of allowing the option for the whole raw screen to be at native resolution, and then having scaling applied to the whole screen all at once, and not having OSD like text rendered at a higher resolution. This would allow screenshots to be captured at the console's native resolution without requiring the OSD to be scaled down.

I don't actually think screenshots work differently than movies, though I may be mistaken or overlooking something. I think once you check the capture OSD box, it captures the screenshot at whatever scale the emulator window is currently.

**Comment by zeromus** [comment]
I don't like any of these ideas, don't do any of them. 
Capture OSD works differently because it interacts badly with what lua layers are available. None of it works right. Just take my word for it, it's all a mess
