### ISSUE TITLE
No input method allows for full range of solar sensor input

### ISSUE THREAD

**Issue by shenef** [TASVideos/BizHawk#2323]
It appears that no input method allows for the full solar sensor input range of 0 to 255.
- Analog input allows a range of ~80 to 200 (100-200 with default settings)
- TAStudio input roll allows for 0 to 200
- The auto-hold tool in TAStudio allows for 0-100

Manually modifying a .bk2 or .tasproj file, a value of 255 is accepted and handled correctly.
So far i have tested that in Boktai 1. I'll update this issue, with screenshots and how it affects Boktai 2 and 3, soon.

mGBA Core in BizHawk 2.4.2 on Windows 10 (v2004) with a Xbox 360 Controller.

**Comment by RetroEdit** [comment]
It's really odd to me that BizHawk has this restriction, but that it's not present in mGBA standalone (`Tools > Game Pak sensors...`):

![mGBA light sensor config](https://user-images.githubusercontent.com/30182911/91066058-bd731800-e620-11ea-9823-b901d5afe4c5.png)

This suggests to me that this is indeed a BizHawk bug, and not an actual weird restriction on solar sensor hardware or something.

**Comment by nattthebear** [comment]
Not sure (and don't care) what's up with the analog input track, but the 200 limit is specified in code and goes back to 68506d6ea1bd747dc87627e90a926bf08eb55d44.  Presumably it's just wrong.

**Comment by endrift** [comment]
Does this actually matter in-game? I'm pretty sure it just limits it to 8 discrete levels (in Boktai 1) or 10 (in 2 and 3).

**Comment by RetroEdit** [comment]
From my testing, having brightness go up to 256 instead of 200 is not important if the brightness is calibrated properly. However, the default of 100 makes the brightness get calibrated by the game in a way that seems to miss out on the higher values. So perhaps the issue as stated (it not going high enough) is not necessarily the root here.

The incongruity between the input methods is still worth cleaning up.
