### ISSUE TITLE
Important 

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2357]
The file at this link got compromised guys download it and check this is my last post

https://github.com/TASVideos/BizHawk/releases/download/2.5/BizHawk-2.5.0.zip

Its not the same file u guys have. Please download it frsh just tried with my iphone on lte and its also infected

Dont scan the url

Doenload the file and upload to virus total

Please try

**Comment by Sonia-7** [comment]
Ok. I just wanted to say that OP isn't the only one who got this Windows Defender report. I also got it, and had to put the .exe under "allowed threats" to keep it around.

So yeah, seems like something went wrong with the 2.5 release. Saying it now while I still can before this thread also gets locked.

**Comment by jjfmz42015** [comment]
They need to trust me and test how im saying

**Comment by NarryG** [comment]
He is right that if you directly upload the file, and don't do a URL scan, Virustotal throws two hits.
https://www.virustotal.com/gui/file/44b290d8332d0c64307c8f602aedfe683c5739238db219fdcb72e4f361de5187/details

But this is nothing new. If you go through Bizhawk history you'll find plenty of versions flagged as malware. It's usually pissy about the Waterbox binaries because they use weird memory manipulation shenanigans. 

This is just failing heuristics

**Comment by TiKevin83** [comment]
Seconding NarryG's comment, I had the same findings that the URL scan gives different results from uploading the zip, and 2.4.2 gets hit by one of the same heuristics as 2.5.

**Comment by zeromus** [comment]
One hit from microsoft on virustotal doesn't count, and microsoft's quality is not spectacular if it can find malware in the exe but not in the exe in the zip so it doubly doesn't count
