### ISSUE TITLE
glad you guys lock ppl out who try and help.

### ISSUE THREAD

**Issue by jjfmz42015** [TASVideos/BizHawk#2358]
glad you guys lock ppl out who try and help.

thats a very bad bug.

**Comment by YoshiRulz** [comment]
There's a virus warning, we get it. Stop spamming.

**Comment by Spikestuff** [comment]
It's related to Windows 10 ver. 1909.
False positive, not a virus.

You didn't give enough info about your system itself... the important part being OS version.
Update to 2004. The issue was cause by Microsoft.

**Comment by jjfmz42015** [comment]
Im am on 2004.


Im actuall on a fresh install of 2004 using a legit install of 2004 media.

If its a false positive thats fine. But i figure even if false positive the devs would want the windows build to run on the latest build of windows without scaring ppl. Anyway i have no more to say after this. Seems every time i find a bug its a war in here. 

Worst thing this emulator has going for it.

**Comment by RetroEdit** [comment]
When you make comments like "most def is a trojan." ([source](https://github.com/TASVideos/BizHawk/issues/2356#issuecomment-683511245)) and that's all you write, that's not a productive contribution about how BizHawk is being detected as a virus. That's just an assertion.

Please do your best to *read carefully* what we actually write. And explain carefully what you observe so devs can respond to it appropriately. Repeating yourself is not productive for discussion.

The issue is inconsistent. Some people are getting it and some aren't. Spikestuff had it on a previous version of Windows 10, but didn't have it on a computer that was updated to 2004.
