### ISSUE TITLE
My FPS in SMB3

### ISSUE THREAD

**Issue by psd02** [TASVideos/BizHawk#2360]
![Screenshot](https://user-images.githubusercontent.com/49033182/91726369-6a5d1000-eba0-11ea-8125-98850cfae7ab.JPG)

Hi, I don't know why I have 23 FPS in SMB3 whereas yesterday I had more than 40
 FPS so I lokked for why it spanked me that and I did not find so I wait your answer of why it does this to me

**Comment by adelikat** [comment]
Go to Config -> Display, and click the Display Method tab

Which drawing method is checked?

**Comment by psd02** [comment]
the display method is Direct3D9

**Comment by adelikat** [comment]
Sounds like you have a very slow computer.  If you notice in your screenshot at hte bottom, there is the word "NesHawk".  That is the core that was picked to run your SMB3 game.  That is because it is some kind of pirated or non-offiical version.  So the normal "quickNES" core did not pick it because it does not do those non-official version.

QuickNES is very fast (as the name suggests) and is the default for the games it can emulate.  NesHawk is very slow (40fps max on your particular computer it seems), but is highly accurate, it also has support for pirated versions of games where quickNES generally does not handle them.

As for 40fps to 23, I can't tell, but maybe you had some other things open at the time.  There's really nothing we can do here for performance of your computer.
