### ISSUE TITLE
version.dll infected 2.5.1 

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#2404]
1. 2.5.1 got a version.dll, we don't know why
2. 2.5.1 WORKS without version.dll existing
3. i always see litter in my git checkout concerning version stuff

I think the version stuff was you. this needs cleaning up. if not, assign it back to me and ill shitcan it gloriously.

**Comment by YoshiRulz** [comment]
What exactly would you be canning? It's working as intended, some generated files will stick around when bisecting because I also changed `.gitignore` (e5de63ea9). It's a good idea to do something like this when jumping around the history:
https://github.com/TASVideos/BizHawk/blob/afbce436cd5805395ddaa6eecbb91f7b60842347/Dist/CleanupBuildOutputDirs.sh#L2
Unfortunately you have to remember where the projects are in older revisions, but `rm -fr output && git restore output` is always safe.

**Comment by zeromus** [comment]
I would be canning whatever makes a version.dll infect builds. 
looks like the latest code doesn't produce a version.dll anymore.
So there's nothing to do here. 
But from now on, builds on release branches must be made with BuildGithubReleaseBranch.bat (modified if necessary to use a different branch). It is not good to use BuildAndPackage. I am going to rename the scripts so this mistake cant happen again
