### ISSUE TITLE
CGB in GBA should not be the default for the TASing profile

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2415]
In 2.5, There was a commit modifying the TASing profile settings, among which there was a change making CGB-in-GBA the default Game Boy mode in the TASing profile:

> 353ec518c73e690c82f3a6972080999cbfbe6a21
> `tas - gambatte, require bios, CGB in GBA (per tasvideos request)`

There's been several experienced TASers offering feedback in Discord that the CGB-in-GBA should not be the default for the TASing profile. While CGB-in-GBA is required for console-verification, the argument is all game modes are acceptable for submission, so the game mode should be user's choice.

Also considering the real CGB-in-GBA BIOS detection is also relatively recent (also added in 2.5) and most users who have Game Boy BIOSes only have the older BIOSes, this probably shouldn't be the default.

@adelikat In regards to your commit message, I think more users are against CGB-in-GBA being the default than for it.

**Comment by nattthebear** [comment]
> and most users who have Game Boy BIOSes only have the older BIOSes

We know exactly what BIOS real AGB-CGB hardware had, no sense in kicking the can down the road.

**Comment by CasualPokePlayer** [comment]
> 
> 
> > and most users who have Game Boy BIOSes only have the older BIOSes
> We know exactly what BIOS real AGB-CGB hardware had, no sense in kicking the can down the road.

Yes, _because the source code for that BIOS was leaked_. To actually obtain those BIOes, you either have to build off the gb-bootroms repo, that or manually hex edit in the modifications to a normal GBC BIOS to turn it into an AGB CGB BIOS (whether you want to turn it into the "true" BIOS or the old gambatte modifications is your choice). Neither of which should be expected from the user. And to be clear, there is still no known way to actually dump this BIOS, the comment on the gb-bootroms repo indicating they got the code from a dump was just a legal shield for them using leaked source code.

**Comment by nattthebear** [comment]
So you dumped your own CGB bios then?  🤣

**Comment by CasualPokePlayer** [comment]
> So you dumped your own CGB bios then? 🤣

> the comment on the gb-bootroms repo indicating they got the code from a dump was just a legal shield for them using leaked source code.

Don't put words in my mouth. Also, somewhat proves my point, you can just go download the cgb bios off some site without much effort, the agb-cgb bios, you can't. It's nowhere out there. Perhaps given maybe some time it could eventually come to that state, but at the moment it's simply really difficult to obtain the BIOS. All that's out there is just the code for the bios, which either means you're assembling from the gb-bootroms repo or hex editing in the differences.

**Comment by zeromus** [comment]
It won't ever be easy to obtain if we make it easy to work around having to obtain it.

**Comment by nattthebear** [comment]
It's already easy to obtain, some people just have shitty google-fu.  This is not a place to beg for firmware files.

**Comment by RetroEdit** [comment]
This isn't about whether the BIOS is easy to open. That's largely orthogonal. It's about what our default Game Boy configuration should be in TASing mode.

Either way, a BIOS is required, there's no argument there.

**Comment by nattthebear** [comment]
Spoke a bit offline on this one and have a reaffirmed decision:  The TASing profile is simply a reflection of the TASVideos community desires, and can be whatever they want.  We also fully support people making TASes outside the profile, so your freedom to choose is never diminished.

That being said, a short time ago the collective opinion of the TASVideos community was to prefer CGB in GBA as a default, and we can't be handling constant changes to the TASing profile as the wind blows.  There's significant evidence that this new opinion is simply folks who couldn't find a firmware, so they need a cooling off period to find their firmwares.  If the community is still hard set on CGB in CGB in say, November, then open a new issue to get that adjustment made.  (My prediction?  You'll all have managed to find a single 3 kilobyte file by then).

Locking since this was reopened once in bad faith already.

**Comment by adelikat** [comment]
Please leave this open.  And let the tasvideos community discuss this

**Comment by nattthebear** [comment]
@adelikat No, I have no time for an endless parade of discussion on this issue.  It will remain closed.

**Comment by RetroEdit** [comment]
You don't have to participate.

If you don't care, ignore it.

**Comment by adelikat** [comment]
@nattthebear, there's 300+ other tickets you are happily ignoring, why are you picking this one to act unprofessional about?  I've assigned this to me, let me handle it please.

**Comment by nattthebear** [comment]
@adelikat You know very well that I look through the backlog and work on anything in my area of expertise that I can fix.  Are you making accusations just because you don't agree with my decision?

**Comment by nattthebear** [comment]
Against my better judgment, I'm reopening this so the comments can pour in.  I suspect there won't be many.

**Comment by TiKevin83** [comment]
As to the original issue - I would be in favor of having CGB in GBA be the default in large part because that's what Gambatte-Speedrun's accuracy is tuned for.  I don't think having that default makes it any more difficult for users to pick CGB or DMG if they really want to for a submission or casual play.

About the BIOS firmware, CasualPokePlayer and natt are both correct.  I would be on board with implementing an additional fallback patch so that CGB in GBA can be used without the firmware, but it would need to live in the firmware manager instead of internally in libgambatte so that we avoid issues like sending the wrong BIOS hash to bk2s.

**Comment by nattthebear** [comment]
> it would need to live in the firmware manager instead of internally in libgambatte so that we avoid issues like sending the wrong BIOS hash to bk2s.

A good point; I think to move forward with movies accurately depicting the actual situation they were recorded in, they need to have the right hash shown.  (Unrelatedly, this means that gbhawk really should recognize the new firmware)

**Comment by EZGames69** [comment]
How about we just let the game mode default to what the game is meant for?

Have DMG games run in DMG mode by default, and have CGB games run in CGB mode by default.

Most users are not going to be aware that these are settings you can change, and most users don't care about console verification.  It should be up to the user to decide if they want to run their games in GBC in GBA mode.

**Comment by nattthebear** [comment]
> If we want to console verify GB games, then hack a real GB to send inputs into the console.

This is decidedly non-trivial and not many people are working on console replay devices.

**Comment by adelikat** [comment]
After discussing with TASVideos staff, we do NOT want GBC in GBA to be the default, so I have set it to false.  There was discussion of potentially a TasBot profile but those talks didn't decide anything concrete but could become an option if there are further settings where this disagreement might occur.
