### ISSUE TITLE
Savestate framebuffer are loading blurry (Waterbox-specific?)

### ISSUE THREAD

**Issue by RetroEdit** [TASVideos/BizHawk#2434]
Starting in 2.5, I noticed the savestate framebuffer was being loaded blurry.

Cores that I've noticed this in: Uzebox, SNES9x

Cores that don't have this issue: Gambatte, mGBA

I'll attach some screenshots shortly. This probably isn't too difficult to fix; I'd imagine it's just a typo that snuck in somewhere.

## Example

*Donkey Kong Country* (SNES9x)

![DKC - Rareware logo blurry](https://user-images.githubusercontent.com/30182911/94705458-9bac3580-0330-11eb-8694-6525f0e6bb80.png)

**Comment by adelikat** [comment]
They are blurry on purpose on cores with large screenshot buffers.  A low res screenshot is hugely smaller.  If a buffer is too large, it causes states to be very slow.
This is by design, and you can configure it in Config -> Rewind & States -> Low Res Screenshot buffers

**Comment by nattthebear** [comment]
Uzebox has giant screenshot buffers due to some complexities on how it generates an image.  I discussed this in chat at one point and the conclusion was that if it becomes a wildly popular core, it'd be worth adding extra heuristics and detections to it, but as a rarely used curiosity, it's not worth it.

The snes stuff may be a case of being in 2x res mode and not expecting it, and I think the cores have different rules on when 2x wide become 2x in both directions, as a convenience for other things.
