### ISSUE TITLE
DK64 Gloomy Galleon Lighthouse Ship Disappeared

### ISSUE THREAD

**Issue by sehaden540** [TASVideos/BizHawk#2489]
![Noship](https://user-images.githubusercontent.com/70821191/100163939-a506d980-2e6b-11eb-88e6-619756c5fa0c.PNG)
![lighthouse lit](https://user-images.githubusercontent.com/70821191/100163947-aa642400-2e6b-11eb-9607-ec62974378c5.PNG)
![Weird](https://user-images.githubusercontent.com/70821191/100163950-adf7ab00-2e6b-11eb-9de4-331599343b07.PNG)

So I have made it to the Gloomy Galleon world 4 and have had no issues with Bizhawk and the rom to this point. I lit the lighthouse with Donkey and the cutscene played and the boat was there. But after I saved, turned off bizhawk and came back later to continue with other kongs, the ship is gone. Lighthouse is still lit but the ship is just not circling the lighthouse at all. I haven't changed settings and have no other issues with any other games. I also notcied this like never ending area shown in one of the pictures. I have it in another area of this world too but if I swim into it, it loads up the other half of that area where Candys shop and the big cactus is.

**Comment by YoshiRulz** [comment]
If the collision is present but nothing is drawn, this is possibly another instance of faulty OpenGL support on Intel iGPUs (see #1820).

**Comment by Isotarge** [comment]
Ah yes, the the DK64 speedrun/TAS community is well aware of this issue. We call it "Chunk Deload" since it can also happen in other levels, notably Crystal Caves.

It appears to happen more often on "Interpreter" or "Pure Interpreter" mupen64plus core types.

Switching the core type to "DynaRec" (N64 -> Plugins -> Core Type in the BizHawk menu bar) seems to resolve it in most cases, we are still not sure why. We recommend this workaround until someone with the skills puts in the time to upgrade our mupen64plus core in BizHawk, or replaces that core with something more accurate. A man can dream.

This will mean downgrading from BizHawk 2.x to 1.x since the DynaRec option was removed when we moved to 64 bit.

Hope that helps!

**Comment by sehaden540** [comment]
Ahh. Thats a little frustrating but I was able to figure it out. I just converted the game and my save data to Retroarch and everything seems to load up fine in that area for now. Hopefully won't be an issue in Crystal Caves when I get to that point either. Thank you all for your help!
