### ISSUE TITLE
The recording and playing of TAS in GBA and GB are not synchronized

### ISSUE THREAD

**Issue by Tas-player** [TASVideos/BizHawk#2523]
When I record GBA and GB TAS, the content of replaying the game will change, and it will not be the same as the original recording of TAS. For example, a certain level can be completely passed without losing blood, but it will continuously collide with monsters to shed blood when playing. How to solve this problem？

**Comment by alyosha-tas** [comment]
Please test with the dev build, link: https://ci.appveyor.com/api/buildjobs/v88pb4igq6f46kfs/artifacts/BizHawk_Developer-2020-12-15-235444-%23fe5655d1e371bdeb5d8738d9e5291dcaec58559f.zip

Also, please be as specific as possible. 
What game were you playing? 
How were you recording? 
What savestates (if any) did you use?

These issues are very hard to fix without additional details, and there were some issues already fixed since 2.5.2 so with any luck maybe it's already fixed.

**Comment by Tas-player** [comment]
It is to open the TAS editor to record the input, and then play it after completion

**Comment by Tas-player** [comment]
The version you gave me doesn't solve the problem

**Comment by YoshiRulz** [comment]
If this still happens on 2.6.2, please open a new issue *and include more details*.
