### ISSUE TITLE
SG-1000 is not SMS

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#258]
```
What steps will reproduce the problem?
1. Start Recording a Movie file with EmuHawk for a SG-1000 game.  I chose Bomb 
Jack (Japan).
2. Record some input and save it.
3. Playback the Movie.  The platform is marked as "SMS" instead of "SG-1000".  
The playback is fine.

What is the expected output? What do you see instead?
Since SMSHawk is handling both SMS and SG-1000 games, is this an issue?

What version of the product are you using? On what operating system?
1.8.1 r7746
```

Original issue reported on code.google.com by `hegyak` on 29 Aug 2014 at 3:19

**Comment by adelikat** [comment]
We now have an IsSG flag in the header, and tasvideos uses this in its submission parser.  So we have all the information you need to know whether or not a movie is for SG-1000.  The systemId has no requirement to specify all the details of the given hardware it is emulating (for instance, should it report a CD add-on?).  

From a tasvideos admin perpective, I consider the current implementation adequate.  As a user, I have the information I need.  So I consider this issue closed. 

The systemId is still an odd property the way it has evolved.  It seems that every core has precisely one system id, but multiple cores can have the same id.  So that's a thing I guess.

I think sorting out how we want to represent hardware from a core perspective is outside the scope of this bug.
