### ISSUE TITLE
N64 Global Video Resolution leveraging cpu instead of gpu

### ISSUE THREAD

**Issue by retrobenny** [TASVideos/BizHawk#2606]
I am on a pretty beefy desktop computer with a 9900KF and RTX 2060 Super,so this is pretty rough considering the specs.

I just grabbed and tested 2.6 for this problem after seeing it on 2.5.2,if you set N64 Global Video Resolution to something like 1920x1440 regardless of plugin choice,strange results happen such as not only heavily impacting cpu usage while having no difference to gpu utilization,but also capping max cpu usage to around 50% per cpu core in-use and tremendously decreasing performance range.

If I use 320x240 it will let me push cpu usage all the way to 100% on main cores/threads and get a lot faster speeds while either having similar gpu usage to before or slightly more utilization.
Interestingly,if I use GLideN64 and set the native resolution factor to something crazy like 16,it can still hit very fast speeds but the gpu usage goes a great deal higher due to it actually having to work a lot harder with 16x upscaling on GLideN64 itself.
The problem with using that native resolution factor is that the graphics still look extra jagged from the 320x240 setting but admittedly sharper.

I hope that it is possible to fix at least part of this by either making it possible to push to 100% cpu usage with higher frame rates or make global Video Resolution setting actually use the gpu to process it instead of the cpu cores so that higher frame rates can be preserved and so it can also still be pushed to 100% cpu usage if fast forwarding.

The game I tested is Banjo-Tooie.

Extra details;

I also used cheats like 60fps (and "lagfix" test code) to push the limits and also forced 15fps when on 1920x1440 but didn't get much fluctuation in performance,meaning even 15fps only helped a tiny bit.

Codes in 1byte rdram used for testing (set lagfix to 02 via edit to restore value to normal and sixty to 04 for 15fps);

Sixty
07913F 01

lagfix
03F4F2 0D

**Comment by YoshiRulz** [comment]
Either this is upstream's problem and not ours, or it is our problem but we can't fix it.

**Comment by retrobenny** [comment]
How might I even apply such settings since Mupen lacks a proper default UI?
which GUI is mostly considered the standard one for "standalone" to be officially the version tested,or what voodoo magic do I need to type into a batch file to make it apply that video resolution correctly in order to test?

**Comment by zeromus** [comment]
The old, terrible mupen plugin API doesnt have a way to fetch texture data. Only an API that reads it back from the GPU, and wastes CPU time reformatting it into a format we may have to format again (on the cpu) and then forward BACK to the gpu (which may not be running opengl, for the rest of emuhawk). By the way, most of those old plugins even do all THAT in the worst possible way for performance (in fairness, with opengl, there is no possible way to get good performance under any circumstances due to the API being totally archaic). Bizhawk's main concern isn't performance, except possibly when it comes to tasing, which you aren't doing if you're increasing the resolution. So we haven't customized all the plugins (which we COULDNT originally do in every case due to some of them even being closed source) to work less badly, which would also be really hard. 

The situation is a mess and we won't be fixing it except maybe one day in the future if we get fully resynchronized with mupen upstream.

**Comment by retrobenny** [comment]
And yet PJ64 beasts through it just fine,aside from interpreter being a bit more demanding with debugger stuff enabled.

I have seen TAS videos playing back the related TAS file with 4K but I don't remember if any N64 game has any videos at a very high resolution.

After fiddling with a stubborn Mupen64plus config file that refused to generate the plugin selections and other details,I managed to test just the ui-console exe by drag-and-drop of the game with a higher resolution and didn't have the performance impact from the looks of it.

Doesn't help that I cant go beyond 295% speed due to,IMO,bad design.
I lack the prowess to modify the source and compile a build that ~~doesn't suck~~ would have 400% as the max limit.
I can't properly compare 295% to BizHawk's 400% range,that said,it seems to be keeping 88fps out of 30fps with the odd 295% cap on stand-alone Mupen64Plus 2.5.9 .

I even did a last-ditch effort with 5120x3840 general resolution left in an unreasonable size above my screen boundaries with visible frame counter and GLideN64's native resolution factor set to 0 in order to push it enough and it still hits full 250% speed but with higher gpu usage as expected and even sustaining 295% when looking in the direction of Angel Bottles and the boulder and stuff to push gpu further.

So either the issue is with BizHawk or a different particular version of Mupen's core,how can I get that specific core version matching BizHawk's core in order to test it more properly in a stand-alone setting?

**Comment by zeromus** [comment]
The issue is with bizhawk, and mupen, and all the plugins. Your comparison to PJ64 is meaningless. We won't be fixing bizhawk, and mupen, and all the plugins.

**Comment by retrobenny** [comment]
What if I try several versions of Bizhawk and manage to find a version that doesn't have this nasty issue and the earliest version afterward that has it?
Would y'all at least consider looking into it then?

**Comment by zeromus** [comment]
There is no version of bizhawk that has any kind of "nasty issue" that could be fixed, but it is entirely possible you will find a build with some fractions of fps differences due to random things changing over history. Since you won't find a build with a "nasty issue", there will be nothing to investigate and I don't have to answer your question.

Please don't mention anything like "hey why dont you make a d3d9 version for bizhawk" to upstream, as they will mentally translate that to "bizhawk user is being annoying, bizhawk is annoying, did they send this guy over here, I bet they did, man I hate bizhawk those guys are annoying" and besides that it won't help. Even if rice had a d3d option (it doesnt) it wouldn't help because it's too old for it to have been d3d9, there's no way in the plugin API to move the texture directly out of the plugin, and bizhawk doesn't know how to ingest it (because there's nothing that would ever deliver it).

**Comment by retrobenny** [comment]
I already clamored about that GLideN64 backend ports stuff a little before even thinking about BizHawk's N64 stuff such as making the name idea VLideN64 for Vulkan as an example.
I wanted a D3D version of GLideN64 to be made since way earlier on because that would make AMD's GPU processors not be useless on Windows due to bad OpenGL drivers.

Sorry for your trouble,and thank you for your time.

**Comment by retrobenny** [comment]
Out of desperation,I just tested Mupen64Plus 2.0 via cheat engine edits to make a save-state for 60fps and "lagfix" and I can still max it out to 150fps and/or 150VI/s by holding F to fast forward,even barely just below that speed on the ludicrous 5120x3840 resolution,compared to BizHawk's laggy mess (no cpu cores being pushed to 100%) at 2880x2160.
So its definitely likely not Mupen or the plugins but something in between BizHawk.

Its frustrating that ScriptHawk is "scripthawk" in the way of being locked into being a BizHawk exclusive thing where you can only play most N64 randomizers on BizHawk due to relying on the Lua scripting instead of embedding the programming directly into the game via patches,as no other N64 emulator/frontend has Lua scripting to my knowledge.

A solution,if possible,would be to make it actually allow 100% usage between the rendering thread and the emulation thread and/or make it possible to use all 8 threads of my 8 core cpu (hyperthreading is disabled for stability) with 1 of the 7 threads being dedicated to the N64 emulation interpreter core.
A problem is that no core at all is even hitting 100% utilization but instead getting stuck at 50% max across all cores,you would expect at least 1 core out of them all being able to push up to 100% even if others are utilized less.
It would seem that a multi-threaded angrylion OpenGL graphics option would even run faster if it was allowed to use all 8 cores if you could have the option to post-process upscale it in some way which might not even harm accuracy for TASing.

I hate how crappy and useless my otherwise powerful desktop feels from not being able to use higher resolutions on BizHawk without being stuck at 45VI/s and I doubt even a current-gen cpu like AMD 5000 or Intel's current fastest monster could do all that much better.

**Comment by zeromus** [comment]
It's definitely mupen, and the plugins, and the api, and bizhawk. You don't know enough about the issue to make that conclusion. Mupen works in the way the plugins were intended to work, where the whole slop of opengl in the plugins pushed through the frontend window like it's a game software. This is the way the GPU and old-ass opengl is meant to work, and that's not how bizhawk works and it's not what bizhawk is made for. Mupen is made for one thing and one thing only. Bizhawk is running as fast as it can in a single thread, and we're not going to pipeline stuff for your frame-blasting pleasure because it will make it harder to do everything else we do in bizhawk by adding complexity for a feature that's not part of our mandate.

If you want to say "bizhawk is shit and you guys suck" respond to this post with a rocketship and I'll unlock it so you can do that.

**Comment by YoshiRulz** [comment]
You can't add Reactions in locked threads :P

I will concur that you're wasting your time, @retrobenny. There are more fundamental problems with Mupen architecture than performance, many of which Mupen standalone also suffers from. A more productive venture for utilising the GPU would be to compile the Angrylion plugin against our Mupen core fork (see #1872).
