### ISSUE TITLE
PS1 loading cue file error

### ISSUE THREAD

**Issue by Tas-player** [TASVideos/BizHawk#2612]
When I was ready to play Megaman X6, the game could not be loaded normally. By the way, X6 is also a cue file

**Comment by Spikestuff** [comment]
Can you please put in actual information rather than "could not be loaded normally".
You're providing no meaningful information for the devs to actually figure out what your issue is actually about.

Anyways. Mega Man X6 (NTSC 1.0, since region's not even specified either) runs fine:

![image](https://user-images.githubusercontent.com/12412764/107200129-68e71c00-6a4b-11eb-9e3a-3d8815a9fe85.png)
![image](https://user-images.githubusercontent.com/12412764/107200191-7ef4dc80-6a4b-11eb-8c56-e761768e5836.png)

**Comment by YoshiRulz** [comment]
Closing, OP's `.cue` probably had broken filenames.
