### ISSUE TITLE
Feature request: Replace SubNESHawk

### ISSUE THREAD

**Issue by Bangerra** [TASVideos/BizHawk#2614]
In current state, all games is working in 30 fps (half-speed) and sound some kinda slowed down. Also i don't know how much it accurate. So just mentioned it here

Tested briefly on next few games: Adventures of Lolo, StarTropics, Contra, Akumajou Dracula

**Comment by Spikestuff** [comment]
SubNESHawk is only something that's required for the TASing scene [to create movies such as this](http://tasvideos.org/4032M.html) and it has to be slow in order to actually perform correctly for it.

The question back to you is; Why are you using SubNESHawk instead of that actual core NESHawk?
Are you actually utilizing the core to create subinput?

**Comment by Bangerra** [comment]
I didn't that this is for the TASing scenes used, issue can be closed.
