### ISSUE TITLE
(Genesis Plus GX) Opening VDP viewer while 128KB of VRAM is active results in an Invaild Parameter Crash

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2651]
### Summary
If 128KB of VRAM is used in the game, opening VDP viewer results in an Invaild Parameter Crash.

### Repro
1. Find any section where 128KB VRAM is used (more likely when you soft reset TiTAN Overdrive 2 demo)
2. Open VDP Viewer
3. You get this:

### Output
[//]: # "Paste the contents of the error dialog if there is one (try Ctrl+C, it usually works), or paste the output from the Lua Console, or delete this section."
```
System.ArgumentException: Parametr jest nieprawidłowy.
   w System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   w BizHawk.Client.EmuHawk.BmpView.ChangeBitmapSize(Int32 w, Int32 h)
   w BizHawk.Client.EmuHawk.BmpView.ChangeBitmapSize(Size s)
   w BizHawk.Client.EmuHawk.GenVdpViewer.DrawNameTable(VDPNameTable nt, UInt16* vram, Byte* tiles, Int32* pal, BmpView bv)
   w BizHawk.Client.EmuHawk.GenVdpViewer.UpdateBefore()
   w BizHawk.Client.EmuHawk.ToolManager.UpdateToolsBefore()
   w BizHawk.Client.EmuHawk.MainForm.StepRunLoop_Core(Boolean force)
   w BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
   w BizHawk.Client.EmuHawk.Program.SubMain(String[] args)
```
Sorry if it is in Polish, I hope I will be able to translate it soon

### Host env.
- Currently affects every version of BizHawk

**Comment by YoshiRulz** [comment]
"any version of BizHawk" is not helpful

**Comment by zeromus** [comment]
Immediately, this seems to be happening because gpgx_get_vdp_view returns a NTA height of 96 and width of 0x80000000
In more depth, that is happening probably because bg_name_list is getting overflowed and clobbering playfield_shift and playfield_row_mask  due to pretend "128kb" mode. GPGX is not a pretend 128K MD emulator (indeed VDP register 1 does not even seem to look at the top bit to see if 128kb mode is set)

Presumably this demo doesn't work in bizhawk's GPGX at all for this reason and it would be nice if OP had mentioned this before mumbling about a debug tool not working on a rom that doesn't even work.

I'm closing this because it will be fixed if the rom is fixed which will happen if there's an upstream update.
