### ISSUE TITLE
CRAM dot emulation? Genplus-GX

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2664]
It appears that it is possible to emulate CRAM dots. Should it be emulated or not?

**Comment by Spikestuff** [comment]
tl;dr explanation with an image...
They're essentially asking for overscan to be implemented into Genesis emulation (BlastEm showcases this):

![image](https://user-images.githubusercontent.com/12412764/111065399-953ffd80-850d-11eb-9ffd-f76ceab2bf3d.png)

**Comment by nattthebear** [comment]
> They're essentially asking for overscan to be implemented into Genesis emulation

No, that's not what CRAM dots is.  If you update the CRAM during active display (overscan or otherwise), then for a single pixel the VDP will output the color you updated.  It's a bus conflict of some sort.  For many games this means just a few extra visual glitches, sometimes in overscan area, sometimes not.  Demoscene uses this to draw entire images without using sprites or BGs.

As far as I know, this is well outside the scope of what Genplus-GX is capable of, and even if it is potentially possible in that emulator, upstream would have to implement it first.  Closing issue because there's no need to have open an issue to track an upstream thing that will likely never happen.

**Comment by getCursorsExe** [comment]
Well, yeah. As far as I know, this has to be the electron beam emulation. If we use simillar electron beam emulation like BlastEM has, we might get CRAM Dots probably.
