### ISSUE TITLE
New Rewinder Issues (2.5 or newer)

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2666]
Delta compression with new rewinder will cause massive slowdown on Mupen64Plus core (can even slow down to over 10 fps!),
New rewinder has an 1 frame lag, which forces us to press the rewind hotkey twice,
Probably more I can find.
These stuff did not happen with old rewinder, since they were being fixed before.

**Comment by nattthebear** [comment]
> Delta compression with new rewinder will cause massive slowdown on Mupen64Plus core (can even slow down to over 10 fps!),

Compression (not called delta compression anymore, because it's not delta compression anymore) is a speed<->space tradeoff.  It's not ideal for all situations, and it's a different tradeoff than before.  There's no bug here, and if the space saving isn't worth the fps loss for your usecase, don't use it.

> New rewinder has an 1 frame lag, which forces us to press the rewind hotkey twice,

Thanks for reporting this.  I've made a more detailed report of it in #2667 and will track it there.

> Probably more I can find.

How am I supposed to fix these, by divination?  If you can find it, then find it.


Closing as the only actionable issue is being handled elsewhere.

**Comment by getCursorsExe** [comment]
Hovewer, that massive slowdown did not happen with old rewinder, so this is also related to Mupen64Plus.
