### ISSUE TITLE
Chocobo Racing (PS1) Cannot Turn Left or Right During Race

### ISSUE THREAD

**Issue by pholtos** [TASVideos/BizHawk#2669]
### Summary
61BF4956 Chocobo Racing.cue
I don't really use anything special, just the regular bizhawk v2.6.1 with standard cores, etc.

Racer under your control just will not turn. Regardless of keyboard or controller. Left and Right do work on the main menu to change which thing to select.

### Repro
1. Go to any race track in any mode
2. Attempt to go left or right after starting the race.
3. Run into walls since you can't turn.

### Host env.
- Bizhawk 2.6.0 and 2.6.1: Win10 Home; i5-7400

**Comment by Spikestuff** [comment]
User error.

With the game loaded.
PSX > Controller / Memcard Settings.
Change port 1 to Gamepad.
Reboot core after changing the port.

The user is using Dual Analog/Shock but wants to use the d-pad which the game does not support in the racing events with those controllers.

[Evidence using 2.5.2](https://github.com/TASVideos/BizHawk/files/6169196/ChocoEvidence.zip), the core is unchanged so you can load it to 2.6.1 without issue.
It's just because I was too lazy at setting up the controller for the current version of Hawk.
I did double check 2.6.1 for sanity checking and I was able to reproduce the game working without issue.

(Also the way you referred to the game it would be written like [SLUS-00844] Chocobo Racing.)

**Comment by pholtos** [comment]
Yeah that'd be it, thanks. Didn't realize the controller type would matter.

Least if someone else has this problem they'll have the answer somewhere.
