### ISSUE TITLE
Genplus-GX 1 8-pixel strip nametable crashes BizHawk if we open VDP viewer

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2678]
Here's how normal nametables look like:
![image](https://user-images.githubusercontent.com/39802077/112475529-31210300-8d71-11eb-9de0-4ead9ae1fa24.png)
I somehow managed to get 1 8-pixel strip nametable:
![image](https://user-images.githubusercontent.com/39802077/112475841-8b21c880-8d71-11eb-9c95-b0c51bff555b.png)
This one is normal...
![image](https://user-images.githubusercontent.com/39802077/112476119-dd62e980-8d71-11eb-81b7-850b3f488426.png)
...but when we open it while 1 8-pixel strip is active, one of the nametables suddenly break and Bizhawk crashes displaying the same error as #2651:
![image](https://user-images.githubusercontent.com/39802077/112476393-22871b80-8d72-11eb-838f-092739c28b22.png)

**Comment by YoshiRulz** [comment]
Which version? Which rom? Please use the bug report template.

**Comment by getCursorsExe** [comment]
2.6.1
I also found out that this happens on older versions.

**Comment by YoshiRulz** [comment]
Please try a [dev build](https://github.com/TASVideos/BizHawk#development-builds).

**Comment by getCursorsExe** [comment]
Still nothing, I still get the same error.

**Comment by zeromus** [comment]
VERY creative effort to get us to fix the other issue. I am really impressed. Unfortunately it won't work, because GPGX is still not a pretend 128K MD emulator, and the same internal fault is probably wrecking GPGX making this technically an upstream issue. Although if you bugged them about it they would say it's our fault. No emulator is immune to malfunctions from "fuzzing" the way you are doing, especially not one written in C.

**Comment by getCursorsExe** [comment]
Also, if we want to see VDP Registers statuses, why won't there be a VDP Register debugger?

**Comment by zeromus** [comment]
Who said there won't be a VDP register debugger?

**Comment by getCursorsExe** [comment]
Well, let's end this topic for now.
