### ISSUE TITLE
GPGX supports Menacer light gun but not its extra buttons

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#2717]
[wiki](https://bitbucket.org/eke/genesis-plus-gx/src/master/wiki/Features.md) says it supports the Light Phaser, Menacer, and Justifier, but though we can pass any of those in (we use only `SYSTEM_LIGHTPHASER` as of 92241b15c):
https://github.com/TASVideos/BizHawk/blob/771b5397fedc81e720e731788b5f7489e33571d2/src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/LibGPGX.cs#L98-L103
...when we read the devices back to create a `ControllerDefinition`, they're grouped together:
https://github.com/TASVideos/BizHawk/blob/771b5397fedc81e720e731788b5f7489e33571d2/src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/LibGPGX.cs#L117
https://github.com/TASVideos/BizHawk/blob/771b5397fedc81e720e731788b5f7489e33571d2/src/BizHawk.Emulation.Cores/Consoles/Sega/gpgx64/GPGXControlConverter.cs#L209-L214
(The `AddToController` call there adds "Lightgun Trigger" and "Lightgun Start".)

Anyone know if upstream actually emulates the extra buttons? I'm told there were games that used them, including the 6-in-1 bundled with the Menacer, *Body Count*, and *Terminator 2: The Arcade Game*.

This is a regression from 1.x.

**Comment by nattthebear** [comment]
> This is a regression from 1.x.

This seems to be https://github.com/TASVideos/BizHawk/commit/eafa39456f4a03395755b8ba69122655c843e9c3#diff-67f8c4ddc5d24684a4e16eadac418d8850e851aa628f9ffcd7d806f414081db4 and https://github.com/TASVideos/BizHawk/commit/307d85cee056298a6271f6537947296aeaa80a58#diff-67f8c4ddc5d24684a4e16eadac418d8850e851aa628f9ffcd7d806f414081db4 then.

They were lost on the way to 2.x because there was a lot of fighting back then about what we could and couldn't support, and so there were two separate copies of GPGX back then, and the changes only made it into one of them.
