### ISSUE TITLE
Missing description for icons in Firmware Info window

### ISSUE THREAD

**Issue by Masterjun3** [TASVideos/BizHawk#2825]
![image](https://user-images.githubusercontent.com/22375320/123926626-59318b00-d98c-11eb-91d4-8bdef8702773.png)

Most users don't understand what an ice flower icon means.
What's the difference between the thumbs down icon and the exclamation point icon?

It should be explained to the user what these icons mean and if there are other icons that don't apply here.

**Comment by Masterjun3** [comment]
How do I make the tooltip appear?

**Comment by YoshiRulz** [comment]
The tooltips are in the main Firmware config dialog. The ice flower means "acceptable". Though looking at it again, I think the ice flower and checkmark have been accidentally swapped as the latter, "ideal", has the description "COOL: Ideal for TASing [...]" ([source](https://github.com/TASVideos/BizHawk/blob/858faaeb56b2ae8c23bc9708e25dd06d4984385d/src/BizHawk.Client.EmuHawk/config/FirmwaresConfigInfo.cs#L12-L27)). And no-one has noticed because of [an unrelated bug](https://github.com/TASVideos/BizHawk/blob/858faaeb56b2ae8c23bc9708e25dd06d4984385d/src/BizHawk.Emulation.Common/Database/FirmwareDatabase.cs#L48) in the firmware database. The whole thing needs a redesign IMO.

See also #2224.

**Comment by alyosha-tas** [comment]
Tool tips are now visible in the info window (first time I've seen a documentation error in visual studio, default is stated to be true but it is in fact false.)

Not sure if anything else actionable with this.
