### ISSUE TITLE
memory.readbyterange returns 0 indexed lua table

### ISSUE THREAD

**Issue by CasualPokePlayer** [TASVideos/BizHawk#2844]
Noticed in #scripting, lua generally does not like the 0 indexed part and it's typically easier to work with a 1 indexed table (e.g. you can't assign the 0th index on initialization and have to use [0] to assign it). It should be returning a 1 indexed table.

~~Oh and it appears that even with matching inputs in the table there is some difference (revealable via tostring) compared to the table returned in memory.readbyterange which causes comparisions to fail. I don't know what this is, although interestingly it is workaroundable via table.concat it seems (but the 0th index is cut off, so issue above screws that over).~~

**Comment by vadosnaprimer** [comment]
Please post an example that would check the resulting difference you're talking about.

**Comment by CasualPokePlayer** [comment]
For testing I used Prehistorik Man (GB) for this script (script reads out from ROM)
```lua
local a = true
local f = io.open("lol.txt", "wb")
local g = io.open("lol1.txt", "wb")

while true do
	b = memory.readbyterange(0, 2)
	c = { }
	c[0] = 49
	c[1] = 254
        if a then
	f:write(tostring(b))
	g:write(tostring(c))
	f:close()
	g:close()
        a = false
        end
	emu.frameadvance();
end
```

**Comment by alyosha-tas** [comment]
tostring just prints out the memory location of the tables, (just try running that script with different programs open to see the difference.) 

I think there is some misunderstanding here about how lua works. c[0] is not necessarily the first entry of the table, it is the entry associated with the key with (integer) value 0. Both b and c in the above produce correct tables representing memory addresses 0 and 1 in main memory. You just can't do things like `for i,line in ipairs(c) do` because then lua only starts looking for keys of (integer) value starting with 1.

But, it turns out the above is only correct by accident, the problem is that readbyterange is returning incorrect key data if the start address is not zero. In this case it returns initial index zero instead of whatever the base address is, contrary to what the documentation says should happen.

Should be an easy fix.

**Comment by YoshiRulz** [comment]
In this case I think the documentation should be changed, not the behaviour, to keep it consistent with the .NET API.

**Comment by CasualPokePlayer** [comment]
> tostring just prints out the memory location of the tables, (just try running that script with different programs open to see the difference.)

Ah, misunderstood that. Thought that was why equality checks against b and c were failing. Although I guess it might be something else? (or maybe I'm misremembering, idk) 

> I think there is some misunderstanding here about how lua works. c[0] is not necessarily the first entry of the table, it is the entry associated with the key with (integer) value 0. Both b and c in the above produce correct tables representing memory addresses 0 and 1 in main memory. You just can't do things like `for i,line in ipairs(c) do` because then lua only starts looking for keys of (integer) value starting with 1.

I know that, that's why the bug report has the 0 index as the first issue.

**Comment by alyosha-tas** [comment]
Personally, what I would want / expect from this function is a table of [addr,value] pairs (even with an address of zero.)

But I also rarely use lua so don't really care. Any other big lua users want to weigh in? @Zinfidel maybe?

**Comment by Zinfidel** [comment]
For all of my use-cases of `readbyterange`, I immediately assumed that it operated similarly to how more traditional languages work, meaning that it just returned an "array" of values. I actually never even noticed the documentation stating that it was supposed to return key value pairs even though it was right there.

What I've mainly used it for is reading big blobs of structures out of memory (usually matrices) and then parsing out the blobs into my own structures. For vectors in matrices, this is most naturally accomplished by using an indexed loop on the table as if it were an array and just parsing out vectors via offset. So this use case favors the array style.

I do actually like the idea of a function that does this with an output of key/value pairs though, but my expectations are that the "default" function just returns an array. 0- or 1-indexed I don't care.

**Comment by zeromus** [comment]
I would suggest `readbyterange` should work in the most sensible way (an array of bytes) but that `readbyterangetable` or something similar would return the table of pairs. Yeah that breaks what it did before, but in general lua is such a mess we can't let ourselves be hamstrung by backwards compatibility.

**Comment by CasualPokePlayer** [comment]
> For all of my use-cases of `readbyterange`, I immediately assumed that it operated similarly to how more traditional languages work, meaning that it just returned an "array" of values.

Well it actually does work that way effectively (a table with integer indexes is an array in lua).

> I would suggest `readbyterange` should work in the most sensible way (an array of bytes)
Yeah that breaks what it did before

Returning an "array" is essentially current effective behavior, so that doesn't change anything effectively. Only "breaking" that could occur is if it's changed from a 0 indexed array to a 1 indexed array.

**Comment by YoshiRulz** [comment]
`memory.read_bytes_as_array`/`memory.write_bytes_as_array` mirror the .NET API, using "arrays". `memory.read_bytes_as_dict`/`memory.write_bytes_as_dict` use the addresses as keys in the table. The old functions are deprecated without adding a print or otherwise changing their behaviour. I would still like to see real scripts using each of the functions before shipping this.

**Comment by Zinfidel** [comment]
@YoshiRulz 
I updated my Armored Core scripts (https://gist.github.com/Zinfidel/d47287cec638f0f915c3d99bccef3a7d) to use the `memory.read_bytes_as_array` function instead of the deprecated version. I can confirm it is working as expected, though it required some amount of fiddling to fix the off-by-1 errors...

The functions that were changed are the bulk read functions: https://gist.github.com/Zinfidel/d47287cec638f0f915c3d99bccef3a7d#file-ac_core-lua-L114-L147

![image](https://user-images.githubusercontent.com/1929934/128247020-d182df61-c025-433b-960e-7309d7b64c75.png)

**Comment by brunovalads** [comment]
@YoshiRulz 
Confirming:
- Deprecated `readbyterange` still working normally (in my [Super Mario World script](https://github.com/brunovalads/smw-stuff/blob/master/SMW-BizHawk.lua), for example)
- New functions work as intended, as in this example that enables all level and paths in Super Mario World

```lua
local level_setting_flags_addr = 0x1EA2 -- 96 bytes
local event_flags_addr = 0x1F02 -- 15 bytes

local as_array = true -- TOGGLE, if false it will use as_dict

local level_setting_write_table = {}
local event_write_table = {}

if as_array then
    
    -- Write 0xBF to all the level setting flags table
    for i = 1, 96 do
        level_setting_write_table[i] = 0xBF
    end
    mainmemory.write_bytes_as_array(level_setting_flags_addr, level_setting_write_table)
    
    -- Write 0xFF to all event flags table
    for i = 1, 15 do
        event_write_table[i] = 0xFF
    end
    mainmemory.write_bytes_as_array(event_flags_addr, event_write_table)
    
else -- as_dict
    
    -- Write 0xBF to all the level setting flags table
    for i = level_setting_flags_addr, level_setting_flags_addr + 95 do
        level_setting_write_table[i] = 0xBF
    end
    mainmemory.write_bytes_as_dict(level_setting_write_table)
    
    -- Write 0xFF to all event flags table
    for i = event_flags_addr, event_flags_addr + 14 do
        event_write_table[i] = 0xFF
    end
    mainmemory.write_bytes_as_dict(event_write_table)
    
end

-- Reload the overworld
mainmemory.writebyte(0x0100, 0x0B)
```
