### ISSUE TITLE
If BizHawk saves config after #2794 is triggered, you cannot use Open Advanced.

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2848]
If BizHawk saves config after #2794 occurs, you will not be able to use Open Advanced feature at all, and you need to create a brand new config.

**Comment by YoshiRulz** [comment]
I don't think the config is corrupted per se, it's just that the Open Advanced dialog saves the most recent Libretro core to config, and the "requires rom" check is automatically done for the recent core when the dialog is opened. It's the check which causes the original crash (#2794) so it makes sense that it also crashes the next time.

It sucks that there's no way to clear the recent core without opening the dialog, but I'm still going to close this in favour of the other Issue because fixing that will also fix this.
