### ISSUE TITLE
Hex Editor bytes do not update when turboing

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2859]
Turboing is a good feature, but the issue here is that if this is active, then bytes in Hex Editor do not update unless we scroll.

**Comment by zeromus** [comment]
This is because HexEditor.cs does not handle FastUpdateAfter(). It is not clear whether it should. 

I think @adelikat should update the tool form base to add an option which will "always update" or "update when turboing" which will, in the tool base classes, pipe update to fast update BUT WATCH OUT: this may make some windows update twice.  So it won't be quite that simple in practice. But in principle it is really simple: it just changes fast updates to regular update calls

**Comment by adelikat** [comment]
It's intended that they do not updating, because updating is very slow, and by turboing, you want speed.  Not much point is turbo vs fast forward otherwise.

Do you mean, maybe, that when you are done turboing it isn't updating? It is intended that you do get a refresh at the end

**Comment by zeromus** [comment]
I would like to add that if you are watching for bytes to change in hex editor, you may not ever see it happen if you are turboing too fast. I suggest you hack your ini file to set the fast forward speed to a higher value (if that's possible?) so that the existing hex editor window updating will work

**Comment by alyosha-tas** [comment]
I checked and hex editor updates correctly after turboing. As was already suggested, just use fast forward (Tab) instead of turbo (Shift + Tab)
