### ISSUE TITLE
Add mGBA as a Game Boy and Game Boy Color core

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2883]
Well, it is revealed that mGBA happens to emulate Game Boy and Game Boy Color due to backward compability. It also aims for high accuracy. So, will it be a feature? In BizHawk, this is blocked for a very weird reason, even though the upstream supports it.
Just look at this: https://emulation.gametechwiki.com/index.php/MGBA

**Comment by YoshiRulz** [comment]
I think mGBA only emulates "CGB-in-GBA", as we call it, which is already covered by Gambatte (and GBHawk?).

**Comment by CasualPokePlayer** [comment]
> 
> 
> I think mGBA only emulates "CGB-in-GBA", as we call it, which is already covered by Gambatte (and GBHawk?).

No, it cam emulate all GB/GBC/GBC-GBA/HLE SGB. Still, it's not amazing accuracy and existing GB cores beat it out by a long shot.

**Comment by getCursorsExe** [comment]
mGBA also focuses on high accuracy.

**Comment by alyosha-tas** [comment]
I'm just going to close this one, the bar for GB/C emulation is very high, and mGBA simply doesn't meet it.

**Comment by endrift** [comment]
Figured I should chime in on this since it's my core: mGBA focuses on accuracy, yes, but primarily _GBA_ accuracy, leaving GB/C somewhat lackluster in comparison to dedicated GB/C cores. Closing this is the right decision, at least for the foreseeable future.

**Comment by getCursorsExe** [comment]
It doesn't say mGBA is inaccurately emulating GB, so we need to figure out if you are right.

**Comment by Spikestuff** [comment]
Did you seriously just ask if the person behind mGBA is "right"?
Are you actually having a laugh?

[Have you even read a single announcement written by endrift?](https://mgba.io/tag/announcement/)

"It doesn't say mGBA is inaccurately emulating GB"
* Although **secondary to Game Boy Advance support**, mGBA aims to have extremely accurate Game Boy support, **eventually** cycle accurate. - Feburary 2016
* It’s quite slow due to the aim of cycle-accuracy, and still very buggy. - Feburary 2016
* Game Boy support got some pretty serious changes and may be buggy in some cases. - June 2017
* Game Boy audio has been revamped. It may not sound correct in many cases and narrowing down which cases are reliably broken will help fix them. - September 2018

And then insert everything beyond and after fixing specific issues with the GB/C core in mGBA.

GBA is the main focus for mGBA if you didn't get that by now and GB/C comes second and can be considered as "Highly Accurate" but not "Cycle" to what endrift wants comparatively back in 2016.
Then again we already have Gambatte in Hawk, this thread ran its course before it even started.

---

I'm out that was my several cents on the silliest response I've ever read by someone who _isn't_ reading and is also questioning the developer.

Don't pull that card towards anyone here or anywhere else ever again.

**Comment by getCursorsExe** [comment]
Okay, I will shut my mouth. If you want to lock this thread, then just do it.
