### ISSUE TITLE
Gambatte: Make cycle count in Trace Log long instead of int

### ISSUE THREAD

**Issue by alyosha-tas** [TASVideos/BizHawk#2902]
I'm trying to compare trace logs with GBHawk in The World Is Not Enough but the cycle count rolling over is making it difficult.

**Comment by CasualPokePlayer** [comment]
The cycle count is already a long. The reason you are seeing rollovers is because the tracelog grabs the internal cycle count (rather than what you get with emu.totalexecutedcycles()), which is made to max out at 0x80000000 before being reset. The reason this is done is because "disabled_time" events are just events scheduled at 0xFFFFFFFF, which is made to never decrement and thus the cycle count will never reach that point. I don't know what consequences there are to changing these to higher values, other than these would likely have massive performance issues if libgambatte is compiled as 32-bit (relevant for upstream, so it would be a bunch of ugly ifdefs).

**Comment by nattthebear** [comment]
Agreed, we should not adjust that internal cycle count or its usages but instead surface something more useful.

**Comment by alyosha-tas** [comment]
Reopening as the merged fix gives incorrect values, for example here at a vblank the cycle count decreases:

```
2166:  FA 90 C2  LD   A,(#C290h)     A:00 F:80 B:d2 C:ac D:d3 E:0c H:d2 L:ac LY:8f SP:cfda  Cy:986501429
LR35902: PC, opcode, registers (A, F, B, C, D, E, H, L, LY, SP, CY)
0040:  C3 EC CF  JP   #CFECh         A:00 F:80 B:d2 C:ac D:d3 E:0c H:d2 L:ac LY:90 SP:cfd8  Cy:986466334
```

**Comment by CasualPokePlayer** [comment]
> Reopening as the merged fix gives incorrect values, for example here at a vblank the cycle count decreases:
> 
> ```
> 2166:  FA 90 C2  LD   A,(#C290h)     A:00 F:80 B:d2 C:ac D:d3 E:0c H:d2 L:ac LY:8f SP:cfda  Cy:986501429
> LR35902: PC, opcode, registers (A, F, B, C, D, E, H, L, LY, SP, CY)
> 0040:  C3 EC CF  JP   #CFECh         A:00 F:80 B:d2 C:ac D:d3 E:0c H:d2 L:ac LY:90 SP:cfd8  Cy:986466334
> ```
> 
> (The count at vblank is correct, the first line is the incorrect one.)

Is this game using double speed mode by chance? I think that might be problematic with my fix (although, on that note, it would be problematic for memory callbacks too?)

**Comment by CasualPokePlayer** [comment]
On another look, this seems to reveal a deep flaw in memory callbacks in general. Memory callbacks are meant to provide an offset to BizHawk's tracked cycle counter. This works fine when in single speed mode. However, once double speed mode enters into the equation, everything goes wrong. It's not even a single "shift another time if double speed mode" since that will shift the cycles spent in single speed mode too (since gambatte's cycle counter is designed to always go at increments of 4, with speed switching handled with every event rescheduled and several other parts adjusted to use the other speed).

I'm not really sure of a proper solution here. Perhaps doing some voodoo math with endtime too could be needed? It'll be some time before this can be properly fixed.
