### ISSUE TITLE
BizHawk Crashes when we load a savestate in SGB from SGB 2 firmware and vice versa

### ISSUE THREAD

**Issue by getCursorsExe** [TASVideos/BizHawk#2928]
Loading a save state from SGB in SGB 2 firmware and vice versa will instantly crash BizHawk with code -1073741819 (0xc0000005) 'Access violation' (therefore bypassing BizHawk's crash handler).
1. Open any GB ROM in SGB (this crash only happens in BSNESv115+)
2. Load SGB 2 firmware
3. Save state here
4. Now use original SGB firmware
5. Load the save state from SGB 2 firmware
6. BizHawk instantly crashes.

Tested in BizHawk Interim builds.

**Comment by YoshiRulz** [comment]
Loading a savestate made with different sync settings is not supported.

In this case, I believe the crash is because the savestate does not include the state of the core wrapper, which is where the firmware length is stored. The old BSNES has the same wrapper structure so I expect it to behave the same.

**Comment by getCursorsExe** [comment]
I don't think this is intended, this can break all TASes done on SGB firmware when using SGB 2.
