### ISSUE TITLE
Please add MSX 1 and 2 Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#319]
```
This is a Feature Request

I would like EmuHawk to handle MSX 1 and 2 ROMs.  I ask because I like having 
one emulator that does everything.  I am a casual user.  I would like it to 
support Save States/Rewind and Movie Recording.
```

Original issue reported on code.google.com by `hegyak` on 20 Nov 2014 at 12:16

**Comment by adelikat** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen.  They are impractical to sit around in queue.

Plus it goes without saying.  The goal of bizhawk is to emulate all platforms.  A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request.  Cores are added based on the time/effort/practicality of doing so.  And it is on everyone's mind to add all platform support.  So these tickets are kind of pointless.
