### ISSUE TITLE
Adding Pico Core

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#320]
```
Feature Request:
I would like the Sega Pico to be supported in EmuHawk.  This is mostly a 
Genesis but modified for children.  It has no real TAS Potential.


Other notes:
http://segaretro.org/Sega_Pico
```

Original issue reported on code.google.com by `hegyak` on 20 Nov 2014 at 3:27

**Comment by adelikat** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen.  They are impractical to sit around in queue.

Plus it goes without saying.  The goal of bizhawk is to emulate all platforms.  A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request.  Cores are added based on the time/effort/practicality of doing so.  And it is on everyone's mind to add all platform support.  So these tickets are kind of pointless.
