### ISSUE TITLE
SNES - Bishoujo Senshi Sailor Moon Sailor Stars - Fuwafuwa Panic 2 (Japan) (ST) - black screen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#337]
```
Bishoujo Senshi Sailor Moon Sailor Stars - Fuwafuwa Panic 2 (Japan) (ST).zip
when you start it, the screen is black - probably missing in the database?


```

Original issue reported on code.google.com by `longpl...@longplays.org` on 10 Dec 2014 at 5:43

**Comment by hegyak** [comment]
We would need to update the BSNES core to fix this issue.

I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen. They are impractical to sit around in queue.

Plus it goes without saying. The goal of bizhawk is to emulate all platforms. A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request. Cores are added based on the time/effort/practicality of doing so. And it is on everyone's mind to add all platform support. So these tickets are kind of pointless.
