### ISSUE TITLE
Lua error message hangs emulator

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#376]
```


"Warning: Attempted write to # outside the memory size of #"

On accident I've sometimes made for loops that try to read past the memory 
size, this causes the top message to appear over and over, and causes the 
emulator to stop responding to all user input(cant even close it without task 
manager)


What version of the product are you using? On what operating system?
Lastest SVN.


```

Original issue reported on code.google.com by `tribeam....@gmail.com` on 20 Jan 2015 at 8:04

**Comment by vadosnaprimer** [comment]
It just tries to finish the loop before returning controls the the emu. With a shorter loop I can pause it very well.

**Comment by zeromus** [comment]
it isnt safe generally to interact with the gui while running lua scripts. this bug is really about having some kind of emergency timeout facility, or at the very least, the one interaction of stopping a script which has run out of control.

**Comment by adelikat** [comment]
Here's an idea.  What if we threaded the lua console output box when scripts write to it.  That way it doesn't hang up the whole emulator.  It will still spew the error message (the error message being accurate to the situation) but the user can easily fix the script and restart it from the GUI.

**Comment by vadosnaprimer** [comment]
Another thought. This situation always seems to happen when people try to use system bus addresses, and the emu is set to use separated domains by default, or it lacks system bus for a particular core. With lua, defaulting to system bus makes sense, because the game will be reading and writing to/from rom/ram/other domains with no intent to inform us each time the new pointer is to a different domain. The address that contains the pointer remains the same, but the destination changes.

In my scripts, I had to pass domain name right next to the target address, but even that sometimes fails. I'll be switching to system bus where possible, to make all reads valid. Note: memory hooks seem to work on the system bus level right away. For the record, I was doing all this with Genesis.

**Comment by YoshiRulz** [comment]
Still reproducible on 2.3.1 with this code:
```lua
memory.usememorydomain("Z80 RAM")
while true do
	emu.frameadvance()
	for i = 0x2000, 0x3000 do memory.read_u8(i) end
end
```

What about only printing the first n errors, then only printing those and the total error count on the call to `emu.frameadvance()`?

**Comment by vadosnaprimer** [comment]
I like getting like 10 error of the same type and then refusing to print each of them, and instead printing their "collapsed" count once we've actually advanced.
