### ISSUE TITLE
Possible Memory Leak With 'joypad:get'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#378]
```
What steps will reproduce the problem:
Script, more info in the comments: http://pastebin.com/j0XJUruP

What version of the product are you using? On what operating system:
Version: SVN build
Core: Any
Game: Any

Please provide any additional information below:
Unsure if I'm doing something wrong or if this actually is a problem...

```

Original issue reported on code.google.com by `tribeam....@gmail.com` on 21 Jan 2015 at 5:32

**Comment by zeromus** [comment]
paste has been removed. We know we've had problems with lua leaking memory.  We've fixed some of them. Most likely it had nothing specifically to do with joypad:get, even if there was a quick way to repro a bug with the missing script. If users continue to have problems with something in a tight loop and no frameadvance, try invoking a GC from lua.

I'm closing this bug since it was exported and is out of date.
