### ISSUE TITLE
window size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#383]
```
Under View -> Window Size, window sizes > 3 will remain at 3 for me. Then, when 
I select a NES ROM, Japanese ROMs are able to keep size 3, but other 
non-Japanese NES ROMs go down to size 2, the default. In all cases, full screen 
mode works, which is at a higher size. When closing the ROMs which have 
decreased the window size, the blank white noise screen goes back to size 3. 

I'm using BizHawk 1.9.1 on Windows 7, using a Lenovo Thinkpad T540p.


```

Original issue reported on code.google.com by `mikememy...@gmail.com` on 1 Feb 2015 at 11:32

**Comment by zeromus** [comment]
Analysis: this user must be meaning PAL by "non-japanese". By default a PAL nes window ill be bigger. He's able to achieve 3x scaling on NTSC, but it's a close call. So he can't go higher than 3x.   Since PAL is bigger and it's a close call, he can't even nail 3x.

I thought this bug was about the erratic meaning of scaling values in conjunction with pixel aspect ratio locking logic, but it isn't.

Maybe there's a bug with multiple resolutions and bizhawk selecting the wrong monitor resolution to limit the window size with, but there's no evidence of that. Since this was auto-migrated, I'm closing this one.
