### ISSUE TITLE
Choppy Keyboard Control

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#398]
```
Hi I just set up this great emulator.

Unfortunately when using keyboard controls, holding down a key results in a 
brief pause, then continuation of the action.  For example, on Atari 2600 Demon 
attack, if I go to the left side of the screen and press a button to slide 
right, it will move a bit, pause, then continue the motion to the right side of 
the screen.  Is there a way to fix this choppy control?  Thanks!

What steps will reproduce the problem?
1. Run any Atari 2600 game where you can slide left or right across the screen, 
go to one side, and hold left or right to move to the other side
2.
3.

What is the expected output? What do you see instead?
Smooth movement across the screen, but there is a pause then continuation of 
the movement.


What version of the product are you using? On what operating system?
1.91

Please provide any additional information below.

```

Original issue reported on code.google.com by `Todd.Kad...@gmail.com` on 21 Feb 2015 at 4:56

**Comment by alyosha-tas** [comment]
I tested this out and found the folllowing:

-Keyboard control is not at issue. Keyboard inputs are emulated correctly. I tried recording movies form keyboard input and found no errors.

-Emulated frames are correct. On a frame by frame basis, there are no errors, and no emulation errors effecting movement. It appears smooth.

-There **are** some noticable skips in normal play, which are probably what this issue is referring to. But given that each frame is correct, this seems like a video timing issue. Using vsync throttle instead of the default clock throttle seems to mitigate most of it. The length of time between vsyncs on this (and other) A2600 games can be a bit varaible, so this might not be avoidable.

Anyway, it's not a keyboard issue as far as I can tell, so closing.
