### ISSUE TITLE
ZX Spectrum emulation, please

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#412]
```
This is a feature request

https://www.youtube.com/watch?v=s2Z_z974o0s - proof of concept video of Bizhawk 
running ZX Spectrum. This is done through FooN (GBAHawk) 

Currently, ZX Spectrum emulation is done using GBAHawk running FooN, which is 
not only inelegant but is not running full speed and cannot switch tape tracks. 
If only there was a way to add a native ZX-Spectrum core based on Fuse or 
something...

At least no desync was reported.

Running Bizhawk 1.9.1 on Windows 10 Technical Preview 
```

Original issue reported on code.google.com by `Warblefl...@gmail.com` on 20 Mar 2015 at 10:33

Attachments:
- [Screenshot (31).png](https://storage.googleapis.com/google-code-attachments/bizhawk/issue-412/comment-0/Screenshot %2831%29.png)

**Comment by adelikat** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen.  They are impractical to sit around in queue.

Plus it goes without saying.  The goal of bizhawk is to emulate all platforms.  A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request.  Cores are added based on the time/effort/practicality of doing so.  And it is on everyone's mind to add all platform support.  So these tickets are kind of pointless.
