### ISSUE TITLE
Menu display is affected by the emulation speed

### ISSUE THREAD

**Issue by tomzx** [TASVideos/BizHawk#450]
What steps will reproduce the problem?
1. Emulate a game
2. Reduce emulation speed to 6%
3. Open the main window's menu. Notice how the rendering/opening speed is affected by the emulation speed. The menu should not be affected by emulation.

**Comment by zeromus** [comment]
I'll reinterpret your point as "the menu should not be affected by throttling"

The entire process is synchronous. The throttling is a discrete step in the process, as is the checking of windows messages. We would need to change each of our throttle methods to wait in a loop which is capable of checking the messages. This sounds possible.

Your exact wording "the menu should not be affected by emulation" is not possible to achieve anytime in the near future or possibly ever. Since the basic client architecture is synchronous, slow emulation necessarily entails blocking of the user interface or else commands could be used via menu operations which interfere with the emulation currently in progress.

**Comment by adelikat** [comment]
I'm going to close this as a "Won't fix".  It is conceivable that in the far future such things could be resolved.  But in the current architecture it simply isn't going to happen.  This is too unlikely to be worth staying open in the queue
