### ISSUE TITLE
[LUA] File handles are not released

### ISSUE THREAD

**Issue by tomzx** [TASVideos/BizHawk#455]
I'm not sure if this is something we can really do anything about, but if a script opens a file using `io.open` and the emulator is paused, the lua console closed, then the file handle is not released and thus one needs to exit EmuHawk in order to release the file handle.

**Comment by zeromus** [comment]
If the lua console is closed, the vm should be destroyed. I would expect the handle to get GC'd and the file closed.
Elsewhere on the web: "The documentation states that the file is closed when the handle is garbage collected after going out of scope"
Which documentation?
Is the VM destroyed and nulled?
Does the method used for VM destroying actually result in things getting GC'd?

**Comment by Masterjun3** [comment]
> Which documentation?

[The official one.](https://www.lua.org/manual/5.1/manual.html)
> Elsewhere on the web: "The documentation states that the file is closed when the handle is garbage collected after going out of scope"

https://www.lua.org/manual/5.1/manual.html#pdf-file:close
> Does the method used for VM destroying actually result in things getting GC'd?

[Probably?](https://www.lua.org/manual/5.1/manual.html#lua_close)

**Comment by zeromus** [comment]
EmuLuaLibrary's Close() method clobbers the _lua without calling Close() on it.
This is positively wrong.

**Comment by nlburgin** [comment]
This bug is still happening to me on 2.3.2

When I restart a script that uses file IO in "w+" mode, the file doesn't get truncated to a zero-length file like it's supposed to. If I manually delete it, it won't get recreated no matter how many times I restart the script, instead the file writes fail *silently* with no indication anything went wrong until I go to check on the file and it's not there.

It seems like the bug fix didn't work perfectly or else it's regressed since then.

Maybe the lua engine switch from #867 has something to do with it? IDRK.
