### ISSUE TITLE
NES paperboy input not working in quickNES

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#459]

**Comment by adelikat** [comment]
I set QuickNes to throw an exception on this game so it will fallback to NesHawk automatically.  Interestingly the good dump (based on GoodNES 3.14) is the only version I found that input doesn't work.  It is not a high priority now since we work automagic for the user, but leaving this open because it is worth investigating at some point

**Comment by hegyak** [comment]
Paperboy relies on the open bus behavior of controller reads and expects them to return exactly 0x40 or 0x41; 

http://wiki.nesdev.com/w/index.php/Tricky-to-emulate_games
http://wiki.nesdev.com/w/index.php/Standard_controller

**Comment by adelikat** [comment]
Closing this.  Our solution is simply to fallback to NesHawk for paper boy.  Closing this issue.
