### ISSUE TITLE
NeoGeo Pocket/Pocket Color Support

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#473]
Since we are porting cores from Mediafen and the NeoGeo Pocket/Pocket Color is accepted for submissions on TASVideos, I would like to see this get ported into BizHawk at some point in time.

If the core is not "Good enough" due to inaccuracy, I don't mind if it's marked in some way clearly to reflect this.  The minimum features I would like are, Savestates and loading ROMs.

It's a pretty fun little system all in all.  Not a lot of demand for it I bet.  But, it would be nice to have, eventually.

**Comment by Techokami** [comment]
Seconding this request. An alternative to Mednafen's core is NeoPop, which is GPLv2, quite accurate, and has the emulator core separated from the Win32 GUI already. [Relevent link](http://www.zophar.net/ngpocket/neopop.html)

**Comment by adelikat** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen.  They are impractical to sit around in queue.

Plus it goes without saying.  The goal of bizhawk is to emulate all platforms.  A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request.  Cores are added based on the time/effort/practicality of doing so.  And it is on everyone's mind to add all platform support.  So these tickets are kind of pointless.
