### ISSUE TITLE
PSX bios not working

### ISSUE THREAD

**Issue by Nick3252** [TASVideos/BizHawk#474]
Well I am a corrupting guy, and I recently stumbled upon WelshGamer's PSX Bios Corruptions but I'm confused by how he opened it. I just got RTC, opened my SCPH1001.bin and nothing. I tried an ISO that world work in psxfin but that didn't work

**Comment by zeromus** [comment]
You dont open bios bins in an emulator, it's illogical. You put them in the firmware dir and then open a disc image. Theres no guarantee that:
1. your disc image works at all in bizhawk
2. your corruption didnt make the disc image fail to boot
Practice using bizhawk's PSX core before trying to corrupt the bios.
We can't support corruptors. This concludes your support.

**Comment by ZALOMASTER** [comment]
ani con resolve the black screen? i tried all please comment

**Comment by zeromus** [comment]
Do not open bin files. Open cue files.

**Comment by ZALOMASTER** [comment]
I tried bro ....and nothing happenens...
Antivirus off
Firewall off and nothing...

El 25 jun. 2018 18:08, "zeromus" <notifications@github.com> escribió:

Do not open bin files. Open cue files.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TASVideos/BizHawk/issues/474#issuecomment-400111746>,
or mute the thread

**Comment by zeromus** [comment]
Your video is of you opening a bin file. 
You may also need an SBI file for this game.
Why do you think this has anything to do with the bios? In your video you pick the same bios you already had. That was just a waste of time.

**Comment by ZALOMASTER** [comment]
I make another show you ..tried with other BIOS ...i hope works whit other
thanks for your time
