### ISSUE TITLE
Crash when working with TAStudio for a while

### ISSUE THREAD

**Issue by Meerkov** [TASVideos/BizHawk#483]
Full Stack Trace in attachment.

System.InvalidOperationException: Nullable object must have a value.
  at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)

Steps to reproduce:
Open a TAStudio file with several thousand frames.
Have a Lua script open to monitor an area memory each frame (e.g. to render a minimap).
Spend a long time adding a few thousand more frames (e.g. edit slowly, rerecord, etc).

Eventually, an error will appear saying that a fatal error occured, and that EmuHawk has to close. It will ask if you would like to try to save the TAStudio file, and mentions it might not successfully save.

Accept and try to save.
After a few seconds, this
![stacktrace](https://cloud.githubusercontent.com/assets/8139496/9299290/44ceebe8-446f-11e5-825d-adb754649351.png)
 stacktrace pops up.

Reopen EmuHawk.
Reopen game
Reopen TAStudio
Notice the recent file doesn't appear in the recently opened files anymore (?)
Open the file anyway [In this case, the save succeeded, I'm not sure if it sometimes fails.]

**Comment by zeromus** [comment]
That's the error that happened in the first place being shown after the save completes.

This code has been rewritten a lot since the last release. Bug reports from 1.11.1 aren't any use now. I can't promise new interim builds will be any more stable though.

Recently opened files list isnt saved when the program carshes.
