### ISSUE TITLE
GBC Donkey Kong GB: Dinky Kong & Dixie Kong (J) - Improper lag frames

### ISSUE THREAD

**Issue by Weegeechan** [TASVideos/BizHawk#497]
I've come across a problem while trying to TAS this game. When entering the first level of the game while either recording a movie or using TAStudio, the game produces lag frames every 6 frames while standing and even more once you start doing actions. These lag frames are not existent when not using these features of BizHawk.

![](http://puu.sh/k7g0O/9ff7ce064d.png)

**Comment by zeromus** [comment]
Are you sure the spurious lag frames show up outside of tastudio? We've heard other complaints that it seems tastudio only is introducing them

**Comment by Weegeechan** [comment]
The lag frames actually do not exist outside TAStudio and Movie Recording. The first level has no lag frames until played while using these features. I can tell they are fake lag frames too because the game does not freeze or slow down when these are happening. Of course input won't be accepted on these frames as well which makes the game un-TASable on BizHawk currently. Here's another picture to showcase the difference between TAStudio/movie recording and normal gameplay:

![](http://puu.sh/kaATs/26e400205f.png)

Hope that helps! :)

**Comment by zeromus** [comment]
OK, all your info ended up being good. I finally found out what's going on.
There's a GB setting 'equal-length frames'. It defaults to true. In some games, it can result in a kind of desynchronization between bizhawk's 'frames' and the game's input polling. **So easy solution for you is simply to set it to false and then TAS.**
Now, why did you see this only during movie recording? Ah, there's the sneaky bit. The desynchronization in this case only occurs if the game spends extra time at boot-up initializing save ram. That happens every time you start a movie. But it only happens once during normal gaming.
In fact, if you go delete your .saveram and then boot up emuhawk and the donkey kong game and go into the first level, youll see the spurious lag frames! Then simply reboot the core, and the lag frames will be gone (the game has now booted up without initializing saveram, since it was already initialized)

**Comment by Weegeechan** [comment]
Oh, thank you so much! :) This made all the lag frames go away so now I can properly TAS this. Thank you again!
