### ISSUE TITLE
ramsearch column sizes broken

### ISSUE THREAD

**Issue by zeromus** [TASVideos/BizHawk#589]
Since 1.11.5 at least, the column sizes are unstable. they will change when changing platforms somehow (related to memorydomain size -> column size?) and the Changes column will shrink to 0, making it seemingly completely broken. You can recover by trying to resize the 0 width column blindly

CC @SamsaraTAS

**Comment by adelikat** [comment]
Is this ticket really a misunderstanding of the difference between Detailed vs Fast mode?

In fast mode, columns like Changes are not used (and underneath the hood the column is really 0).  Large domains default to fast mode because otherwise they are extremely slow since they need to calculate previous value, changes, etc on millions of values.  

If you want to see changes on a large domain, simply change the mode to detailed after setting the memory domain.

Unless reported otherwise, I'll assume everything is working by design and this is just a UI misunderstanding
