### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by colt05** [TASVideos/BizHawk#590]
Hello.
I am trying to download http://www.redscientist.com/#/rtcorruptormod (RTC). I scan the file with Webroot, and it detects a virus. It seems it has something to do with the ROM loading? Is there a fixed version?
Thanks!

**Comment by zeromus** [comment]
We don't make real-time corruptor mod.
When reporting a virus in a URL, include the URL.
There are no viruses in any files we distribute.
Virus scanners have false positives all the time.
Check it at virustotal.com

**Comment by colt05** [comment]
Virustotal reports a virus. I know you don't make the corrupter mod, but webroot there's a dll in bizhawk  that has the virus.

**Comment by zeromus** [comment]
Virus total doesn't "report a virus", virustotal tells you X out of Y virus scanners report a virus. You still didn't say which URL, you can't even be bothered to say which DLL, and not only did we not make the corruptor mod, we didnt make whichever archive you downloaded (and I dont know which archive it is)

**Comment by vgturtle127** [comment]
@colt05 It should also be noted that Webroot is not the most accurate example of a decent security application. It has been compared against other security solutions before, and it often loses by a pretty wide margin.

Since BizHawk is mostly DLL files, it doesn't surprise me that one of them comes up as a virus, being that an entire emulator can fit in a DLL file. Libretro gets falsely reported all the time.

I would email the Webroot team and tell them they are getting false positives on BizHawk files.

**Comment by zeromus** [comment]
we may have accidentally made some releases with upx'd files. don't expect anybody who false positives upx'd files to ever stop false positiving upx'd files, theyre well aware of it. But the dude doesnt say which files were false positives, so.... i dunno

**Comment by vgturtle127** [comment]
@zeromus Regardless, it isn't something we can solve on our end, so no need for us to worry about it. :smiley:

**Comment by colt05** [comment]
oh ok
