### ISSUE TITLE
TI83Hawk: Better emulation of the ON button

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TASVideos/BizHawk#60]
```
Get better emulation of the ON button for TI83Hawk.
```

Original issue reported on code.google.com by `brandman...@gmail.com` on 12 May 2012 at 7:46

**Comment by alyosha-tas** [comment]
I looked into this a bit while I was rewriting the Z80 core.

Basically, the calculator is in low power mode once turned from 'on' to 'off.' It's still technically running just waiting for an interrupt from the 'on' button. 

When going from actually off, as in batteries removed, to on, the core should start at 0x0000 as with any other Z80 based system. The current state of things, powering up into some strange memory clearing region, is not proper behaviour. 

Probably much of the necessary details to emulate this weren't available when the core was first written, but this issue is really more like 'rewrite the TI-83 core' then just improving how the on button works.

**Comment by alyosha-tas** [comment]
I did what I could to bring this up to speed. It now powers on correctly without the initial PC vector hack.
I also fixed timings in general.
Much more research is needed, but this is good enough for now.

**Comment by adelikat** [comment]
Of all issues on the tracker, this the one I thought was least likely to ever be adressed, heh.

Nice work
