### ISSUE TITLE
BizHawk fails to start because it is unable to compile shader.

### ISSUE THREAD

**Issue by Mtgxyz** [TASVideos/BizHawk#623]
Starting BizHawk fails to start on Windows 7 Home Premium (64 Bit). Prereqs installer has been installed multiple times without any change. My Graphics card is "NVIDIA GeForce GTX 750" and is using the official nvidia driver version 362.0

Here is a backtrace given by BizHawk, It seems from the code that somwhow the vertex shader compiles, but the fragment shader doesn't, for whatever reasons.
I couldn't find out the reason for that by debugging, but here is the stack traceback:
`System.InvalidOperationException: Error compiling shader:  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SlimDX.Utilities.BufferToString(ID3DXBuffer* buffer)
   at SlimDX.Direct3D9.ShaderBytecode.Compile(Byte[] sourceData, Macro[] defines, Include includeFile, String functionName, String profile, ShaderFlags flags, String& errors)
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   --- End of inner exception stack trace ---
   at BizHawk.Bizware.BizwareGL.Drivers.SlimDX.IGL_SlimDX9.CreateFragmentShader(Boolean cg, String source, String entry, Boolean required)
   at BizHawk.Bizware.BizwareGL.GuiRenderer..ctor(IGL owner)
   at BizHawk.Client.EmuHawk.DisplayManager..ctor(PresentationPanel presentationPanel)
   at BizHawk.Client.EmuHawk.MainForm..ctor(String[] args)
   at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)`

**Comment by jnatale11** [comment]
I'm getting the same exact thing...

**Comment by zeromus** [comment]
OMG it used to only be intel cards that did this. Now we have official nvidia drivers violating the d3d spec and returning nulls? Guess its time to fix slimdx. But they're still failing the shader compiling, regardless of whether they crash... ... we have to find out why.

**Comment by Mtgxyz** [comment]
I reinstalled windows, after I got frequent blue screens because of the driver and it works again. (The driver still give me occasional bluescreens). maybe it is some sort of software-driver-hardware issue.

**Comment by zeromus** [comment]
This bug isn't a hardware issue, but your other problems still might be. That's interesting info nonetheless

**Comment by jnatale11** [comment]
Running on the command line with --gdi fixes this in some cases

**Comment by zeromus** [comment]
It should fix it in all cases since it bypasses the initialization of the direct3d. Can you please run the dll I posted?

**Comment by zeromus** [comment]
Some updates on the subject, since this is top google hit for it.
There's bugs in some drivers (intel, I think) which makes it return null strings instead of empty strings. I reported to slimdx, they fixed:

https://github.com/SlimDX/slimdx/commit/e24f1c2c9cee42faac1f6b940e799a09512d3a4a

Users may also get crashes from slimdx due to GetBufferPointer() crashing, itself. But this is a red herring. I believe it crashes because the buffer-> used is garbage, due to the ShaderBytecode::Compile() not initializing it, not checking to see whether it's set by the D3DX call, and the D3DX call malfunctioning. 

In fact, the prime cause of these were ERROR_MODULE_NOT_FOUND caused by microsoft's directx web update MALFUNCTIONING. It seems it randomly fails and doesn't completely install directx.

To combat this, I made a new prerequisite installer v1.4 which installs the needed DLLs as well. This MAY be fixing these users; or maybe another attempt at the web update may be fixing them. I don't have positive confirmation either way.

For future debugging, make sure the latest prereq installer is being run, and try running it a few times.
