### ISSUE TITLE
PCEHawk: Lemmings gives an error

### ISSUE THREAD

**Issue by Reinc01** [TASVideos/BizHawk#665]
I start the game, a prompt to press the Run button appears. I press Run, then the logo appears, then Bizhawk gives an error.
[log.txt](https://github.com/TASVideos/BizHawk/files/355415/log.txt)

**Comment by hegyak** [comment]
I got the same error.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

**Comment by alyosha-tas** [comment]
The error comes from here (line 78 of CDAudio.cs):

//play until the beginning of the next track (?)
EndLBA = Disc.Session1.Tracks[track.Number + 1].LBA;

The problem is that SeekTrack in DiscStructures.cs is returning ses.LeadoutTrack even when no track is found. This being the last track, (track.Number + 1) in the above code is out of bounds.

This case arises when the lba passed to Seek function is greater then the highest possible track value (I think making it an invalid value.) The lba in this case is ~215000 when LeadoutTrack is only ~195000

The solution is to return null instead (line 87 of DiscStructures.cs), then no track is played. This resolves the error and the game plays fine.

However, I am not sure if this solution is correct, or if what is needed is some other way to resolve (track.Number + 1), so I could use some input from someone more knowledgeable before I commit anything
