### ISSUE TITLE
RAM search : 0 keep appearing after deleting it

### ISSUE THREAD

**Issue by Niamek** [TASVideos/BizHawk#685]
So when I search a RAM address, When you delete the 0 that is already present in the specific value space in order to write a new value, a new 0 appears.

->Backspace so you erase the 0
->Type 2

As you can see, you will see 20 instead of 2.

Maybe a better thing to do is to not add it automatically like that, but to add it if no value is entered there and that you stop writing it there.

**Comment by adelikat** [comment]
The fix I applied is a bit of a compromise but more similar to typical UI with boxes that have default values.  Now when you empty the box it will still put in the default zeros, but will highlight the text so that the next key press will over write it.

Now in the use case here, you backspace to erase the 0 and type 2, you end up with 2, not 20

**Comment by Niamek** [comment]
That's a good compromise indeed. Thanks!
