### ISSUE TITLE
Why in the world are you using IPC in the SNES core?

### ISSUE THREAD

**Issue by meepdarknessmeep** [TASVideos/BizHawk#690]
Why are you even using two threads? You are literally making the threads do nothing but idle the times where the other thread is doing stuff. You don't need two threads.

**Comment by SwadicalRag** [comment]
:+1:

**Comment by Velkon** [comment]
![yesplz](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by oplexz** [comment]
👍

**Comment by Techbot121** [comment]
![bigthumb](http://techbot.xyz/ShareX/screenshots/2016/08/27/asdf.png)

**Comment by vadosnaprimer** [comment]
Sorry Mario, Byuu is in the other castle.

**Comment by zeromus** [comment]
libco and .net do not play well together. They're fundamentally incompatible, because .net depends on a proper win32 callstack to fire GC any time C++ calls back into .net, and libco tears up the stack. We tried fixing libco to reconstruct the stack well enough for .net, but failed.

Our bsnes fork calls into .net from c++ for two main reasons: 1) for callbacks such as acquiring input and delivering audio samples (could be worked around by re-engineering insides to buffer whatever's needed); and 2) for lua and trace events (can't be worked around, in principle). Since reason (2) can't be worked around, we didn't bother with reason (1).

We originally solved this whole problem by putting bsnes in _another process entirely_ so that .net and c++ never existed in the same stack. Thus the IPC mechanism was needed.

Later we realized we could move bsnes back into the main bizhawk process if we were very careful to make sure that .net and c++ code never touched the same stack. This entailed using the bulky IPC framework we already had to marshal the calls between c# and c++ without actually directly calling on a foreign stack.  

The performance benefits of moving bsnes back into emuhawk.exe are essentially only a reduction of the bulky IPC overhead.  This would not really be greatly appreciated except in abstruse scenarios. I don't know how much improvement it made for casual gaming, but it certainly did not make anything worse. 

It's possible that the current mechanisms for running the IPC (there are two; if you've used bizhawk more than 3 minutes you may have found the ring buffer option) are not as efficient as could be given the new reality of it running as a thread in the bizhawk process. We haven't re-assessed that since the process->thread move.  

But that finally gets me to the answer to your question. The threads idle because it increased the performance of the communication between the processes, which was running with such direly bad performance that no cost (a wasted CPU core) was too high for any tiny speedup through reduced synchronization overhead.


We're going to have the same problem for MAME (and other) cores in libretro. Maybe we'll come up with a better solution, but don't count on it.
![bigturtle](https://cloud.githubusercontent.com/assets/102701/18027266/10915c38-6c25-11e6-956c-efd6a591c0d7.png)

**Comment by meepdarknessmeep** [comment]
I kind of already removed pipes from my local version and installed luajit to increase the performance. I don't use any pipes or anything and run it in the same core with the main form updating routines - I believe I have even gotten a 2 ms improvement out of it (judging by fps in-game without display on)

**Comment by SwadicalRag** [comment]
does this even support [IPC](https://en.wikipedia.org/wiki/Industrial_PC)?

**Comment by zeromus** [comment]
@meepdarknessmeep  Cool, I look forward to the patches.  But if you did both at once, only you can guess which of the two things you did made the performance impact, since only you know how complex your scripts are.

**Comment by meepdarknessmeep** [comment]
I didn't do both at once - I used luajit to improve the massive slowdown of big lua scripts and included ffi in some of my memory intensive scripts. I later then removed the ipc in the snes c core and c# api and it works flawlessly (as far as I can tell) - but I probably would need some help testing some of the debugging features as I am not sure about all the debugging tools on this program.

**Comment by meepdarknessmeep** [comment]
Also with LuaJit it would potentially cause incompatibilities with some of the other core's api where it would pause coroutine execution from within lua 'cfunctions' as you seem to have included something to allow that. I had to manually remove some lua_yield calls and add it to my lua scripts after calls to stuff like `emu.advanceFrame` so it would work properly. We will have to have a discussion about how - and if - you want to handle that in a breaking change (or hacky fix).

**Comment by vadosnaprimer** [comment]
Bizhawk has a couple of complex scripts to test some things on, but they are for Genesis (would that change anything?). They give huge slowdown due to really frequent calls into the c-side of lua. Could this be helped by your method?

**Comment by zeromus** [comment]
Well, if you removed the serialization of the commands and events into a pipe, then don't bother with debugging or a patch, it's positively wrong.

I contemplated luajit just now insofar as I checked the diffs and didn't see anything weird in lua precisely (the changes were mostly in luainterface) and thought it seemed safe, but you're clearly more up to date on the subject than I am, but it's possible weird changes predated our committing it.  You are right, there is a lot of weirdness going on. Maybe I'm not so sure about this anymore.

**Comment by meepdarknessmeep** [comment]
@vadosnaprimer I would have to manually change the genesis core to remove ipc altogether

@zeromus Removing pipes (ipc) from this served it well.

The reason pipes aren't needed in this core is because it's not doing anything but making one thread wait on another (which is entirely against the concept of threading!)

Here's some example code from what I have done:

```c#

        [DllImport("libsneshawk-32-performance.dll", CallingConvention = CallingConvention.Cdecl)]
        static extern void SetSnesPathRequest(snesPathRequest_t f);

        string snesPathRequest(int slot, string hint)
        {
            string ret = hint;
            if (pathRequest != null)
                hint = pathRequest(slot, hint);
            return hint;
        }


        void ShareSigFunctions()
        {
            SetSnesPathRequest(Keep<snesPathRequest_t>(snesPathRequest));
        }
```

```cpp

typedef const char *(__cdecl *snesPathRequest_t)(int slot, const char *hint);
snesPathRequest_t snesPathRequestManaged;


SNES_EXPORT void SetSnesPathRequest(snesPathRequest_t f)
{
	snesPathRequestManaged = f;
}


char SNES_PATH_REQUEST_TEMP[2048];
const char* snes_path_request(int slot, const char* hint)
{
	strncpy(SNES_PATH_REQUEST_TEMP, snesPathRequestManaged(slot, hint), sizeof(SNES_PATH_REQUEST_TEMP));

	return SNES_PATH_REQUEST_TEMP;
}
```

Also another note - all the libco use for this core is only used for jumping between code - it doesn't stop in the middle of random spots waiting for something else to be done. It's redundant.

**Comment by zeromus** [comment]
I can see you didn't read my explanation. One thread has to wait on another because one thread must complete before the other can resume; and there must be two threads to solve the GC problems.

That specific example you gave could be done that way.. NOW. But
1. It could not have been done that way originally when they were in separate processes
2. It can't be done that way for some other functions

**Comment by meepdarknessmeep** [comment]
That's the complete opposite point of threading. Threads should be independent (mostly) of each other when performing their tasks. What you just described (one thread has to wait on another) can generally be done with one thread. 

In this implementation I made a single thread that can update everything at once (which can also be changed to have one thread for the main ui and one thread for the emulator if you need it to)

I also don't seem to see any gc problems with this new implementation - maybe you could show me once I put it on a pull request?

Also you said "it can't be done ... for some other functions", can you explain which ones those are so I can see what you are talking about?

**Comment by meepdarknessmeep** [comment]
@zeromus ah I see what you mean now. This can be easily prevented by just allowing C# to copy it's string into a pointer passed to the function. Like:
```c#

        void snesPathRequest(int slot, IntPtr hint, int length)
        {
            if (pathRequest != null)
            {
                string ret = pathRequest(slot, Marshal.PtrToStringAuto(hint));
                byte[] outdata = new byte[ret.Length];
                for (int i = 0; i < ret.Length; i++)
                    outdata[i] = (byte)ret[i];

                Marshal.Copy(outdata, 0, hint, length); 
            }
        }
```

and of course adjust all the others accordingly

**Comment by zeromus** [comment]
(I don't see how your last fix solves anything. The basic problem is supposed to be calling into .net from c++)

You're right, this is not the usual point to threading. It's an extremely unusual point. The usual point for threading is to parallelize. The point for threading here is to separate the c# and .net callstacks.

`snes_input_poll`, `snes_video_refresh`, etc. Would be more vulnerable to this problem as they're certainly meant to be called from the midst of emulation.

But I need to think about this more. There's a possibility this problem with two callstacks got punctured and deflated at some point. Check snes_video_refresh for example. See the SETCONTROL call? Just above it, we have what is effectively EVEN MORE parameter marshaling, and then SETCONTROL switches back to another cothread. That's an adequate amount of marshaling and stack management to solve the problem--if it's applied carefully.

If that thread used by SETCONTROL was a bsnes-created cothread, then this would positively be subject to the GC bug (which your users will show you in the form of a mysterious crash).  However, if it's the main thread (and it seems to be in this case--see `co_control = co_active()`) then there's no GC bug.

Since the adequate marshaling and stack management is being done by the callbacks in bsnes, the API from c# to bsnes can become fully normal (compared to other bizhawk cores).

I have to think about this more.

**Comment by meepdarknessmeep** [comment]
I believe you may have not seen this section from a post a few back:
`Also another note - all the libco use for this core is only used for jumping between code - it doesn't stop in the middle of random spots waiting for something else to be done. It's redundant.`

example: your snes_video_refresh code could be changed to:
```cpp
void snes_video_refresh(const uint32_t *data, unsigned width, unsigned height)
{	
	int destOfs = 
		snesVideoRefreshManaged(width, height);
	char* buf = (char*)hMapFilePtr + destOfs;
	int bufsize = 512 * 480 * 4;
	memcpy(buf, data, bufsize);
}
```

since all it does is jump back to control, check `exitType` then `exitCallbackType` and finally pipes it back to the main thread, and jump back to the other coroutine.

**Comment by meepdarknessmeep** [comment]
we should probably stop editing our posts as it is definitely causing confusion amoungst ourselves us :-)

**Comment by zeromus** [comment]
OK, snes_video_refresh was not a good example. As I said early on, that's just stuff that could be buffered. A better example would be for instance debug_op_read(). You can see that's also got SETCONTROL also.

You're wrong about your quote though. Every time SETCONTROL runs, control switches away from the emulation thread and to the control thread until something switches back to the emulation thread (SETEMU). In the case of debug_op_read, a "BRK" type command is executed, which fires the event into the pipe, then ends up going to HANDLEMESSAGES which blocks reading a response from the emulator.

**Comment by meepdarknessmeep** [comment]
I don't exactly understand what makes it different compared to `snes_video_refresh` as you yourself said the multithreading in the code is only for gc purposes - meaning it will all run in the same order even if we remove the piping. 

In the case of `debug_op_read` it would call an `Action` hook in c# which would then pipe more messages in the same order as just calling it straight from c# would do

**Comment by meepdarknessmeep** [comment]
Ah I stand corrected. It would not be the same in the case of callbacks. Maybe we could right some async callbacks instead inside that action hook?

**Comment by meepdarknessmeep** [comment]
It doesn't seem like ReadHook is used anywhere - maybe we could worry about the design we are going to use for that in the future?

**Comment by meepdarknessmeep** [comment]
Sorry for the spam but I am mistaken - I apparently can't do a good grep + reading anymore :-(

**Comment by zeromus** [comment]
ReadHook is used by bsnes! That's where the debug_op_read ends up, by a very torturous path.
Async is NOT acceptable. That's like saying your debug breakpoints should be asynchronous, and allow code to continue executing in the meantime.

**Comment by meepdarknessmeep** [comment]
Ah sorry, meant to say sync. (no clue how i got that mixed up while typing)

How and when does debug_op_read get called?

I can't get it to get called from the debugger or from lua.

**Comment by vadosnaprimer** [comment]
Tracer or Debugger tools I guess.

**Comment by zeromus** [comment]
it's an execute breakpoint. tracer callback is triggered from the exact same point deep inside the cpu

**Comment by meepdarknessmeep** [comment]
Alright since I cannot figure out how to get that to run (the debugger ui confuses me :-( ) I am going to fork this and make a pull request for you guys to maybe test yourself and see if you can find any bugs - (and I will look at how to fix). Is that alright?

**Comment by zeromus** [comment]
The debugger is junk. Most people use this feature through lua.
I look forward to your PR but I may be picky about this. Once I decide this is all safe I may be inclined to purge and rewrite it all myself. But if you did a good job, I guess I wont have to.

**Comment by Velkon** [comment]
![a](https://camo.githubusercontent.com/90439f7805809706369d3d0e129373427ecc7dc3/687474703a2f2f692e696d6775722e636f6d2f303436587459432e706e67)

**Comment by vadosnaprimer** [comment]
@meepdarknessmeep Did I not say "Tracer" enough times?

**Comment by meepdarknessmeep** [comment]
@vadosnaprimer Sorry! I meant the debugger and the Tracer. Neither did anything in my version or the version you guys have on github.

**Comment by vadosnaprimer** [comment]
How are you checking? If you want a dll breakpoint to actually break the EmuHawk execution, you need to add `_asm int 3` to the core code, otherwise EmuHawk will never know when the core enters the tracer callback.

**Comment by zeromus** [comment]
test

**Comment by meepdarknessmeep** [comment]
All future conversations should be at #692
