### ISSUE TITLE
Python3 scripting support

### ISSUE THREAD

**Issue by OctoNezd** [TASVideos/BizHawk#707]
[s]Because lua sucks[/s]

**Comment by hegyak** [comment]
No.

**Comment by kylelyk** [comment]
It's not because we are trying to be mean; I would love scripting support in another language like Python. However, this would be a substantial amount of work. Since these scripts tend to be less than a couple thousand lines, it doesn't really matter how much the language "sucks"; the current scripting language does the job fine and most people with programming experience know that they will have to learn new languages all the time.

**Comment by hegyak** [comment]
The primary issue is that I can't name a SINGLE emulator that uses Python instead of LUA.  And, it's a LOT of work to setup a scripting system for BizHawk.

**Comment by OctoNezd** [comment]
There is only one(vba-linux + vba_wrapper library), but it supports Python2, not Python3
