### ISSUE TITLE
Compling For Linux ?

### ISSUE THREAD

**Issue by DarrenRainey** [TASVideos/BizHawk#715]
I cant seem to find any instructions to compile for linux so does this work on linux or windows only ?

**Comment by hegyak** [comment]
You may want to look at the Mono Branch.  It's for OSX but, it may help you out.

**Comment by vadosnaprimer** [comment]
There's been another guy's journey with bizhawk+linux starting from [this post](http://tasvideos.org/forum/viewtopic.php?p=424946#424946). The next page contains some workarounds, but it still failed in the end. Hopefully, you will get farther.

**Comment by Sappharad** [comment]
Getting it to compile on Linux is the easy part. I've done that multiple times over the past few years. If you're at all familiar with C# you can probably figure it out in a couple of hours.

The problem is once you have it compiling, it's not very stable to run it on Linux. I don't have a dedicated Linux machine so I haven't spent time to figure out why it crashes so often. Good luck with that.

If you want something simpler and potentially easier to start with, check the BizHawk.Client.EtoHawk directory for a replacement UI written in Eto. It's very basic (video and sound work, you can configure controllers too) but there isn't any OpenGL acceleration yet and that's where I left off about 7 months ago. The normal WinForms UI should compile and run though. Keep in mind that many of the cores are native and none of those have been ported. If you want something entirely .NET to test against, try GameGear/MasterSystem or Atari 2600.
