### ISSUE TITLE
[Request] Odyssey 2 Emulator

### ISSUE THREAD

**Issue by Cibomatto2002** [TASVideos/BizHawk#750]
Will we see a Odyssey 2 Emulator in the future? Odyssey 2 was my first console that I had as a kid there was some good memory's of playing games on it. O2EM has his source code up for download.

http://o2em.sourceforge.net/#

**Comment by hegyak** [comment]
I'm going to close tickets like this from now on.

Requests like "Have this entire platform emulated" are huge and will happen when they happen. They are impractical to sit around in queue.

Plus it goes without saying. The goal of bizhawk is to emulate all platforms. A platform isn't lacking in bizhawk becuase nobody requested and no core is added because of a request. Cores are added based on the time/effort/practicality of doing so. And it is on everyone's mind to add all platform support. So these tickets are kind of pointless.

**Comment by alyosha-tas** [comment]
@Cibomatto2002 a odyssey 2 core has been added to the dev build, please test

**Comment by Cibomatto2002** [comment]
Most games I have tried do not work correct here is a video on one of them.

https://www.youtube.com/watch?v=00-5mu2YlV4&feature=youtu.be

here is a video on the same game working correct.

https://www.youtube.com/watch?v=07JtE4pIq8U

**Comment by alyosha-tas** [comment]
I fixed collision detection so the problems you are having should be fixed, please try the dev build.

**Comment by Cibomatto2002** [comment]
Thank you it's ok now. :)

**Comment by alyosha-tas** [comment]
I think this is sufficiently advanced to not be a future core issue anymore, closing.
