### ISSUE TITLE
hex editor out of bounds bug

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#755]
1.11.9.1
Performing certain steps in the hex editor can cause bugs and crashes. This happens:
- with games that have different ROM sizes (same console)
- with games that have different memory domains (different consoles)

Repro steps for the first case (same console, different ROM sizes):
1) Load Kirby & The Amazing Mirror (Beta) (J).gba
open hex editor, select ROM memory domain and scroll down
Select an address
http://imgur.com/oV2x4s6.png

2) Load Mario & Luigi Superstar Saga (U) (Demo) (Kiosk).gba
http://i.imgur.com/y8fOnUy.png

3) Ctrl+C (Copy)--> Exception
Ctrl+F (Find)--> Exception
Ctrl+E (Export) --> Exception 
Freezing seems absent, maybe because Bizhawk thinks freezing ROM addresses is pointless.
Adding to RAM Watch works and displays value FF (in the one case I tried it)
Saving to .txt seems to take the ROM values and then everything after it looks like garbage data... (I can't really say for sure). 

A similar bug like this can also occur if you use completely different ROMs. (such as NES Startropics and GBA Super Mario Ball). The difference is that instead of staying in the ROM memory domain, it would reset to some default memory domain. If you selected an address prior to loading the 2nd ROM and the address then happens to be out of bounds, the same problem would occur. 

I noticed, in this particular case, when the 2nd ROM is Startropics, you can also "freeze" the out of bounds address. I'd rather not try it so I don't know what can happen if you do it.

**Comment by adelikat** [comment]
I can't reproduce any of this on the latest build.  I think these issues have been resolved.

Btw, "Freezing is absent" is intentional.  Every memory domain has the option to be writable.  Some don't because they don't make sense to be written to.  Others aren't simply because it is impractical to implement or simply hasn't been implemented yet.  The hex editor is programmed to handle that by graying out the values and putting "read only" on the memory domain name.
