### ISSUE TITLE
evaluate hashing and headers for a7800

### ISSUE THREAD

**Issue by hegyak** [TASVideos/BizHawk#758]
Open an Atari 7800 ROM.  Any should be fine.

BizHawk's reported Hash doesn't match the ROM's MD5 Hash.  Even manually writing the Hash to the CSV,  doesn't work.  BizHawk may not be reading the Hash correctly.

**Comment by hegyak** [comment]
It should be noted that ROMs with Trimmed Headers (128 Bytes) are invalid/not recognized.  But, ROMs with the header, work just fine.

**Comment by zeromus** [comment]
Please evaluate the lore surrounding no-intro and TOSEC's use of headers in their roms. no-intro recently made everyone's lives miserable by switching to some non-headered roms, and then switching back. if tosec and no-intro are in agreement now, then we should have hashes that follow that. If they're not in agreement, then we need to improvise.

**Comment by hegyak** [comment]
Oh boy...  I really wish these guys would make a decision on what the hell they want their ROM hashes to be.

**Comment by alyosha-tas** [comment]
The hashes in the gameDB are headerless hashes. It is BizHawk's initial check of the ROM that is reporting the md5 of the complete file because the header size (128 bytes) is not recognized.

Both EMU7800 and A7800Hawk check the game DB by first checking if a ROM has a header and then chopping it off if so, then using the revised md5.

I'm not sure there is really anything to do here. Headerless hashes seem more appropriate anyway, and the ROM header can be used for games not in the DB.

Maybe the ROM loader can be made to recognize 128 byte ROM headers so it doesnt throw the warning that contains the unused md5

**Comment by alyosha-tas** [comment]
I updated the rom loader to detect 128 byte A78 headers. The initial check of the ROM will now unambiguously report the headerless ROM hash. If no game is detected, it will return the ROM with header data intact so the core can use it.
