### ISSUE TITLE
TAStudio gets out of ranges

### ISSUE THREAD

**Issue by schas002** [TASVideos/BizHawk#778]
In TAStudio, the input roll fails to render as an `index` of the input roll goes out of range somehow.

```
Parameter name: index
   in System.ThrowHelper.ThrowArgumentOutOfRangeException()
   in BizHawk.Client.EmuHawk.InputRoll.DoBackGroundCallback(PaintEventArgs e, List`1 visibleColumns)
   in BizHawk.Client.EmuHawk.InputRoll.DrawBg(PaintEventArgs e, List`1 visibleColumns)
   in BizHawk.Client.EmuHawk.InputRoll.OnPaint(PaintEventArgs e)
   in System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   in System.Windows.Forms.Control.WmPaint(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   in System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

I experienced the problem on Windows 7 Home Basic 64-bit, BizHawk git-commit-hash `3721e26`, after starting a copy of Pokemon Crystal (paused), trying to open external tools and opening TAStudio on the zeroth frame.

**Comment by schas002** [comment]
@vadosnaprimer  Let's see...

**Comment by schas002** [comment]
(By the way, if I advance a few frames, TAStudio seems to work normally.)

**Comment by schas002** [comment]
It seems to happen only when I tried to open external tools, even if I have the advancement.

**Comment by vadosnaprimer** [comment]
Post the exact repro steps then.

**Comment by schas002** [comment]
Run any game (tested on Pokemon Crystal and Red), move mouse over "External Tools" in Tools menu, get exception. Next, try opening TAStudio. Instead of the awaited input roll, you get two exceptions, the latter of which is the one in issue. Done.

**Comment by vadosnaprimer** [comment]
Fresh unzip? Works fine for me, External Tools -> None, no crashes whatsoever.

**Comment by schas002** [comment]
Not-so-fresh unzip. Russian locale, if that helps.

**Comment by alchemistake** [comment]
I am getting similar error, index out of bounds throw but cause is different on TAStudio.
I can reproduce it consistently, but I have a final tomorrow (College life :/ ) I will add details in few days.

I believe my exception is different from schas002's but I didn't want to corrupt issues page. The effected project file can be opened and played and edited via recording, but there is giant red X instead of columns. The sad part is I tried to open the file on older version (1.8.2) the result is same, thus file is corrupted.

The issue happens when I "play movie" (from files>play.etc.) of the project file and it got past of the latest frame on the project and then, this funky business happens.

**Comment by vadosnaprimer** [comment]
Are these bugs still there in the latest build?

**Comment by schas002** [comment]
Can't check (I lost my PC :sob:), looks like I'll have to close it for now.
