### ISSUE TITLE
Unhandled Exception when hovering over Cores options.

### ISSUE THREAD

**Issue by retrobenny** [TASVideos/BizHawk#781]
Windows 10 laptop on the 1.11.9 release from December via Github download.
If I hover over the SNES droplist,an unhandled exception occurs without crashing.

"Object reference not set to an instance of an object."

Pretty annoying I have to mouse around it to enter N64 plugins,but its even worse for those needing access to that SNES option,I searched a few common words but did not find any similar enough issues.

**Comment by hegyak** [comment]
I think you haven't extracted the archive correctly.  You need to extract all the files along with the folder structure.

**Comment by retrobenny** [comment]
All folders from the zip archive are already in the directory I extracted everything to as-is.
I created a folder simply named "Bizhawk" then dragged the archive with right click to "extract here" via 7zip context.
One thing I notice is that there is no SNES directory in there at all,not even in the archived zip.

While I am here,how do I stop Windows 10's "crashing for no reason" problem whenever exiting it?
Yes,I assume this is mainly due to Windows 10 shenanigans.
The last time,it crashed before I even tried closing it,I was going for the task manager so I could end the process that way,which usually prevents the annoying "has stopped working" messages.
I probably have crash dumps clogging my storage because of these unreasonable crashes.

And yet,when I glitch around with DK64's lua script (Scripthawk by Isotarge) for grabbing random things and warping to various areas,nothing crashes or hangs at all.

**Comment by hegyak** [comment]
Confirmed in 1.11.9 Release.  Developer Build does not have this issue.

**Comment by zeromus** [comment]
Confirmed--so can you post a stacktrace?

**Comment by retrobenny** [comment]
Not familiar with the term,how do I get a stacktrace? Don't have time to try that yet anyway until precisely 16+ hours of this reply at the earliest. Its currently a bit after 10PM for where I am.

**Comment by zeromus** [comment]
That was for hegyak. For you, if you wish, you can just do whatever steps seem obvious to provide more information than the bare minimum

**Comment by shinji257** [comment]
I also get this but it seems after loading one SNES game and hitting the crash that it doesn't happen on subsequent loads.  However I can still reproduce on a fresh extraction so here is the stack trace from the JIT catch.

`See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BizHawk.Client.EmuHawk.MainForm.CoreSNESSubMenu_DropDownOpened(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.DropDown_Opened(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnOpened(EventArgs e)
   at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   at System.Windows.Forms.ToolStripDropDown.Show()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   at System.Windows.Forms.ToolStripDropDownItem.ShowDropDown(Boolean mousePush)
   at System.Windows.Forms.ToolStripMenuItem.OnMenuAutoExpand()
   at System.Windows.Forms.MenuTimer.OnTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
EmuHawk
    Assembly Version: 1.11.9.1
    Win32 Version: 1.11.9.1
    CodeBase: file:///C:/Users/shinj/Desktop/Test/EmuHawk.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
BizHawk.Common
    Assembly Version: 1.11.9.1
    Win32 Version: 1.11.9.1
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Common.dll
----------------------------------------
BizHawk.Client.Common
    Assembly Version: 1.11.9.1
    Win32 Version: 1.11.9.1
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Client.Common.dll
----------------------------------------
BizHawk.Emulation.Common
    Assembly Version: 1.11.9.1
    Win32 Version: 1.11.9.1
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Emulation.Common.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.OpenTK
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Bizware.BizwareGL.OpenTK.dll
----------------------------------------
BizHawk.Bizware.BizwareGL
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Bizware.BizwareGL.dll
----------------------------------------
OpenTK
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.1475.5656
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/OpenTK.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.SlimDX
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Bizware.BizwareGL.SlimDX.dll
----------------------------------------
BizHawk.Bizware.BizwareGL.GdiPlus
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/BizHawk.Bizware.BizwareGL.GdiPlus.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
BizHawk.Emulation.Cores
    Assembly Version: 1.11.9.1
    Win32 Version: 1.11.9.1
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/Bizhawk.Emulation.Cores.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.3.17312
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/Newtonsoft.Json.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SlimDX
    Assembly Version: 4.0.13.43
    Win32 Version: 
    CodeBase: file:///C:/Users/shinj/Desktop/Test/dll/SlimDX.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.2032.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.`

(While typing this compares config.ini instead of just submitting this...)
Found it.  There is some config options I can add to config.ini to avoid the issue up front but it seems that these get initialized on first rom load anyways.  Is it possible these are not getting defaulted internally if missing and hence the exception?

`"CoreSyncSettings": {
    "BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore": {
      "$type": "BizHawk.Emulation.Cores.Nintendo.SNES.LibsnesCore+SnesSyncSettings, BizHawk.Emulation.Cores",
      "Profile": "Performance"
    }
  },`

**Comment by shinji257** [comment]
Update: Confirm bug not present in developer build.  Took a look at the commit history and this has already been addressed.

https://github.com/TASVideos/BizHawk/commit/d305b048fcd5a3e781a2a45abbe8cc77877c48c3
