### ISSUE TITLE
N64 joystick seems to work more like a d-pad

### ISSUE THREAD

**Issue by TheGoatManfan** [TASVideos/BizHawk#787]
I'm using a PS3 controller ran as an 360 one using SPC Service. Using the latest build available.

When using the left stick to move around, rather than using the multiple, joystick directions, it only seems to want to move only strictly up, down, left, or right if I move the stick. Like as if a NES game's D-pad was bound to a stick. It feels very stiff and not like a joystick at all.

I've used both the default controls, and bound it myself. Both have had the same issue.

**Comment by Isotarge** [comment]
Are the controls named: "P1 A Up" "P1 A Down" "P1 A Left" "P1 A Right" bound in your configuration? If so, you should completely unbind those and use the "P1 X Axis" and "P1 Y Axis" controls from the "Analog Controls" tab instead.

A note for BizHawk developers: I see this issue a lot, it might be worth switching the priority so that X and Y axis binds take priority over the boolean versions for N64.

**Comment by hegyak** [comment]
I would say that defaulting the Analog sticks for a controller to relevant analog sick(s) on the Emulated controller is a good idea.

**Comment by TheGoatManfan** [comment]
Yeah, this worked. Thank you so much!

It's a confusing layout, and it'd make more sense for just they keyboard to be bound to the 8-way controls, rather than the joystick being so.
