### ISSUE TITLE
SNES - Wagyan Paradise - Glitchy clouds on Level 5

### ISSUE THREAD

**Issue by danylopez123** [TASVideos/BizHawk#810]
The clouds in the background are teleporting like crazy, captured frame by frame, but sometimes it happens more than 1 frame.

Frame 1
![wagyan paradise japan 2017-02-20 13 23 51](https://cloud.githubusercontent.com/assets/17708894/23125110/830fa1ee-f770-11e6-8255-08a42895ef39.png)

Frame 2
![wagyan paradise japan 2017-02-20 13 23 55](https://cloud.githubusercontent.com/assets/17708894/23125123/8c6de75a-f770-11e6-8a92-f99116214d34.png)

**Comment by zeromus** [comment]
which SNES core are you using; are you TASing or rewinding?

**Comment by danylopez123** [comment]
I cant even rewind, since 1.11.7 it wont let me and im not TASing the game, i used savestates to pass that minigame, the core im using is BSNES (Performance)

**Comment by zeromus** [comment]
You had another bug about rewind, which I solved. You never replied. I'm not sure you ever read it.

I dont understand how to get past the minigame even with savestates.
Can you send a savestate before entering level 5 (while the screen's fading out prior to fading in to enter level 5)?

**Comment by alyosha-tas** [comment]
Just tested this and it is an issue with the performance core. The clouds appear just fine in compatibility core, so that core should be used with this game.

Here is a savestate at the start of level 5 in performance core if you are interested in looking into exactly why it happens:

https://www.dropbox.com/s/kijqsp5oncaogqx/Wagyan%20Paradise%20%28Japan%29.Performance_level5.State?dl=0

**Comment by zeromus** [comment]
Nope. That'll be beyond our pay grade. That's why the compatibility core exists. Thanks for figuring out how to play this game.
