### ISSUE TITLE
Mid values aren't set to dualshock analogs when tastudio autoloads

### ISSUE THREAD

**Issue by vadosnaprimer** [TASVideos/BizHawk#832]
If you set the controller to dualshock for psx, and tastudio to autoload, the initial values for analog controls are set as all zeros instead of FloatRange Mid.

Turning Recording mode on in tastudio fixes it. And if you restart tastudio, mid ranges are also properly used. But if you restart the whole app, all zeros are again there.

**Comment by vadosnaprimer** [comment]
Happens with NESHawk's Zapper as well.

And the  thing I didn't mention is that I completely failed to find the reason for these zeros while debugging what is happening, so I'd love someone else to fix it.

**Comment by alyosha-tas** [comment]
At least for the NES Zapper, the values that appear in TAStudio initially are simply those present at the time you click on 'Tools.' This is apparently remembered somewhere and used in TAStudio as the default.

If you record inputs, or drag and paint different values in the piano roll to create new frames, then close TAStudio, when you re-open it to start a new movie the default values are the last ones you painted with.

In neither case are the default values the Mid values as far as I can see.

If you give me a hint on where to look where TAStudio is setting these things up I can try to debug it.

**Comment by vadosnaprimer** [comment]
OK, I guess zapper isn't related. And for psx, IIRC it's Mid forgetting to set itself somewhere or to get read elsewhere, it's not set by tastudio. It just seems to launch before the Mid value gets read if you autoload it.

**Comment by alyosha-tas** [comment]
It looks like (at least part of) the problem is in LatchInputFromLog() in MovieSession.cs
Adelikat even has a note there about frame 0 stuff in TAstudio.
Seems like input is initially ill defined so it just ignores any floats altogether and repeats the most recent available value.

**Comment by adelikat** [comment]
if (Global.Emulator.Frame == 0) // Hacky
			{
				HandleMovieAfterFrameLoop(); // Frame 0 needs to be handled.
			}

should there be a return after HandleMovieAfterFrameLoop() ?

**Comment by alyosha-tas** [comment]
Alright, I got this one figured out, I just need someone with a bit more familiarity with all the code paths to determine the best implementation.

The problem is in LatchSticky() in BK2ControllerAdapter.cs

It's doing this (which is fine for not frame 0):

`_myFloatControls[name] = Global.AutofireStickyXORAdapter.GetFloat(name);`

For frame zero though it needs to do something like this:
```
var temp = Definition.FloatRanges[i];
_myFloatControls[name] = temp.Mid;
i++;
```

That's pretty much all there is to it. I just don't know the best way to get here from moviesession.cs without breaking anything else.

@vadosnaprimer maybe you can take it from here?

**Comment by vadosnaprimer** [comment]
Don't want to touch it right now, but I might later.

**Comment by alyosha-tas** [comment]
I opened a PR which hopefully addresses this, or at least it can be a starting point. 

At least I think it does everything desired without regressions that I can see.

Needs a lot of testing though.

**Comment by zeromus** [comment]
bleh. The logic for frame 0 in tasing is totally fubar. I got chewed out when I changed it to make sense recently. So I'm not sure I have any input on what makes sense. OK, you want special magic values instead of zero values set (which would make sense for buttons) before the TASing universe has any concept of what's going on? Frankly, I don't want to hear about it. Your general proposition of forcing the float control to mid as a special input=null hack sounds like the very definition of that.

Who's to say what the correct values are for frame 0, anyway? What if someone wants buttons pressed on frame 0? What if someone wants analog values other than mid? This whole subject really annoys me. 

I'll review the PR later and be annoyed

**Comment by vadosnaprimer** [comment]
The principle of picking up mid value has been there for quite a while, and it does work for most cases, and IIRC the concept of mid values itself is even older, and both make sense and work. There was just a couple situations when picking them up was failing.

I tried comparing startup of working scenarios and of broken ones, but all the input chain logic is so insane that I failed. I simply couldn't figure out where exactly they are being picked up for the working cases.

**Comment by alyosha-tas** [comment]
I don’t really care what happens here, I was just interested in sorting out what was going on.

Maybe at the very least we can prevent analog controls bound to the mouse from assuming strange values in TAStudio when it is started from the tools menu.

**Comment by vadosnaprimer** [comment]
I can't reproduce this problem at all, how do you like **that**?

**Comment by alyosha-tas** [comment]
huh? Seems to behave the exact same to me. how exactly are you testing it?

**Comment by vadosnaprimer** [comment]
The way it's written in the OP: set dualshock in psx or zapper in neshawk, set tastudio to autoload, see 0s in the analog controls in tastudio. The thing is, I made tastudio and HUD hide analog values if they are mid, which is default for them. And they derive from mid, they are displayed. So seeing how tastudio keeps displaying 0s means it failed to fetch the defaults. Without autoloading it was working fine, and now it works fine with autoloading as well.
