### ISSUE TITLE
Feature Request: Remember Window Size

### ISSUE THREAD

**Issue by RickardNi** [TASVideos/BizHawk#853]
Switching over from Snes9X to BizHawk has been great, with some minor annoyances that I miss from Snes9X. One of those is the feature to remember the window size.

In Snes9X upon closing the application, the window position and size is saved to the config file. (Optimal would be to have a separate setting where you enter the position and size that it defaults to even if you happen to move/change the window.)

In BizHawk, windows position is saved, but size is not. There seem to be a width/height setting that defaults to -1, but doesn't appear to be used.

The reason why this feature is important is because resizing the window to an exact size is a pain, and that exact size is required since it affects streaming with OBS.

**Comment by zeromus** [comment]
Bizhawk doesnt remember the size because it manages them according to complex logic. It is meaningless to remember a size, since the size is continually recalculated.

To pick whichever size you want, use config > display > use custom size

The MainWidth and MainHeight you see are kind of an accident, theyre meant for MultiHawk.
