### ISSUE TITLE
MSV 2010 dll's not loading

### ISSUE THREAD

**Issue by BrainCheffSteff** [TASVideos/BizHawk#862]
Pre-requisite check failed for Visual C++ 2010 SP1 Runtime even though everything was installed as needed.

Seems to be problem with the libraries themselves not being registered properly on install (regardless of install method)

QUICK FIX:
Fixed by dropping msvcp100.dll and msvcr100.dll into main folder for bizhawk.

**Comment by vadosnaprimer** [comment]
Something wasn't built with /MT?

**Comment by zeromus** [comment]
The prerequisite check is merely an attempt to open the dll. If that doesn't work, it's because the DLLs are broken. This is usually caused by other programs broken installers. By copying the dlls into bizhawk's directory, youve caused it to use those instead. There are some conditions the prerequisite installer can't fix, because microsoft's installers can't fix them. I recommend deleting all msvcp100.dll and msvcr100.dll from your windows system32 and syswow64 directories and running the prerequisite installer again; this should fix it.

**Comment by zeromus** [comment]
I doubt this guy is coming back
