### ISSUE TITLE
Neshawk - Automatic FDS Disk Side Swap

### ISSUE THREAD

**Issue by synnae** [TASVideos/BizHawk#878]
Is it possible to add an option to automatically switch FDS disks? Having to manually "eject > switch > re-insert" is cumbersome and it should not exist on modern NES emulators anymore.

Mesen has this feature as of version 0.9.0 and it works perfectly.

**Comment by zeromus** [comment]
It should exist for a hypothetical FDS game which measures the amount of time taken to swap the disk as an emulation prevention countermeasure; or for a hypothetical game which demands you insert an unrelated disk. Therefore it would need to be subject to a whitelist in the game database or be an option (and whether this would be enabled by default would be subject to politics). Under the circumstances, you should expect this most likely never to happen in bizhawk, given how much of a game specific convenience hack it is, but in principle it's an OK feature request. Still, this is only one step removed from a hack which automatically warps you to world 8 when starting SMB.

For the record, the hacks are in mesen's FDS.cpp in ReadRAM()

**Comment by synnae** [comment]
If automatic swapping is a hack, then what about adding a shortcut key to flip sides? Mesen has it under "Preferences > Shortcut Keys" and in Nintaco it's Shift+B.

**Comment by zeromus** [comment]
Sorry, a game can probably easily detect when something is done instantaneously which could not be done instantaneously in real life and malfunction or call you a cheater. This actually wrecks a lot of CD-based games. Ideally these commands need to be emulated as discrete events with specific time between them; bizhawk implements this for TASing as separate input commands on different frames, due to it's legacy frame-centric view of the world. 

Some (most?) CD emulators will implement cd switching with an implicit delay behind the scenes. This is problematical with bizhawk's frame-centric view of the world and an especially troublesome interaction with its prior implementation using virtual inputs.

I do not anticipate this happening. Sorry, you're using an emulator which has prioritized some other things above casual gaming convenience. I think it's even less likely than copying mesen's instantaneous autodetection hack.

**Comment by synnae** [comment]
Makes sense. I understand your point about frame-centric view and the problems this kind of feature would cause. Thanks for giving me a straight answer.

**Comment by zeromus** [comment]
You know you can bind keyboard keys to buttons though. I dont know what happens if you insert without ejecting but just try binding Console>FDS Insert 0 and Console>FDS Insert 1 and see what happens. Worst case you have to bind eject also to ` and then hit ` 0 or ` 1

**Comment by synnae** [comment]
Apparently you don't need to press eject. Just using Insert 0 / Insert 1 is enough.

I'm not sure how to bind keys to those two commands, though. They're not listed on "Config > Hotkeys", and can only be accessed from "NES > FDS Controls". Doesn't seem like you can't bind keys from there.

**Comment by zeromus** [comment]
Theyre virtual inputs as discussed, bind them through config > controllers > console

**Comment by synnae** [comment]
Thanks! That worked.

**Comment by adelikat** [comment]
I don't support this feature request.
