### ISSUE TITLE
[SGB] Graphical Issues in Mega Man V

### ISSUE THREAD

**Issue by lightgod87** [TASVideos/BizHawk#891]
Good day,

This is an issue I'm reporting with the SGB functionalities in Mega Man V -- when I go to the P-Chip shop, the icons for the items don't appear correctly. I've tested this in 1.13.0 as well and the issue is still there, but I've also checked in VBA and bgb, and that issue doesn't happen in those emulators. It seems like the SGB functionalities have issues. I dunno if it's possible to use another core for this, or if fixing this problem would be a better idea.

Thanks in advance.

**Comment by zeromus** [comment]
to be clear this is art in the GB portion and an issue in the GB emulation

**Comment by alyosha-tas** [comment]
Why was this one closed? The issue does seem to be present

**Comment by zeromus** [comment]
Youd know if you were on IRC, where we discuss strategy

**Comment by Sappharad** [comment]
The reason that zeromus provided on IRC yesterday was that they are going to be switching to a different core for SGB so bugs against the current core won't be applicable anymore.

(Although I don't see any harm in making sure someone verifies this problem against the new core, otherwise it's just going to be reported again.)

**Comment by zeromus** [comment]
All new core, all new bugs, delete bugs on old core en masse.
