### ISSUE TITLE
[TAStudio] A last edited frame Greenzone

### ISSUE THREAD

**Issue by TASeditor** [TASVideos/BizHawk#916]
Save a temporary greenzone for the frame that was last edited. Example: If user edits input on frame 1005, there should be then a greenzone on that frame next time the playback courser runs over that frame. If user then edits another frame, the temporary greenzone gets invalidated.
Good for platforms with analog sticks.

**Comment by zeromus** [comment]
File under "ideas for greenzone management, once someone dedicates a month of their life to unraveling the greenzone management mess"

**Comment by vadosnaprimer** [comment]
This one is particularly easy. Since greenzone invalidation is daily routine, when it occurs, we might tell it to forcibly save the state after the frame it invalidates from. Since it always runs through that frame, it's reliable. And since that frame doesn't always have greenzone, it makes sense to do it.
