### ISSUE TITLE
Building in Visual Studio 2017 for Mac: Undefined reference

### ISSUE THREAD

**Issue by PikalaxALT** [TASVideos/BizHawk#921]
When building the solution in VS Community 2017 on OS X Sierra, C# file Client/BizHawk.Client.EmuHawk/Input/IPCKeyInput.cs is unable to find namespace KeyInput.  Errors are raised at lines 23, 24, and 54 of this file.  Class KeyInput, for reference, is defined in Client/BizHawk.Client.EmuHawk/Input/Keyboard.cs.  Note that the environment variable definition of `WINDOWS` was removed for this build in order to mask an import from a Windows-exclusive library.

When building the solution on a Windows 10 machine with VS Community 2017, no error is raised whether building from HEAD or release.

The full builder output can be found [here](https://pastebin.com/R07xQt8Z).

**Comment by Sappharad** [comment]
The code for macOS was never part of master, it is in the mono-portable branch. But the BizHawk.Client.EmuHawk project is now 64-bit WinForms, and that's not supported by Microsoft on macOS and will never be. This issue cannot be fixed.

Please read the most recent posts in this thread for more information:
http://tasvideos.org/forum/viewtopic.php?t=12659

**Comment by vadosnaprimer** [comment]
@Sappharad I have a plan. I will pull the changes from master to x86 branch that is 1.13.1+, and since it already has C# lua, you might try to make that version of lua work on mac. Also were p4wn3r's linux fixes pulled or not? It could keep the x86 branch alive for a while just for that.

**Comment by Sappharad** [comment]
I have not pulled in p4wn3r's fixes yet. I suppose I could look into that, but that happened around the same time that I knew 64-bit was coming and was still figuring out what to do about it.

Linux doesn't need the x86 branch, WinForms on Linux wasn't built against a deprecated API and works fine on x64. Theoretically I could just merge all of the 2.0 stuff into the portable branch along with those linux changes and get the non-waterbox stuff working again, but once EtoHawk is in a usable state we won't need a separate branch for mono because the actual BizHawk.Emulation.* projects are mostly identical and the only platform specific stuff would not require making stupid changes just to make mono work better.

The only reason to keep the mono branch around might be if p4wn3r wants to continue building the WinForms UI for Linux for features that won't exist in the Eto version yet.

**Comment by vadosnaprimer** [comment]
But x86 seems to still be needed for mac? And probably for some windows users as well. Either way, lua in mono seems to be the main point here.

**Comment by Sappharad** [comment]
You are the only one who has mentioned Lua so far.

**Comment by vadosnaprimer** [comment]
I wouldn't object if you just create the linux only branch. Official linux build with lua is my actual goal, mac appears to be just an option. And if you switch to 2.0 for linux, it might be kept up-to-date with the recent commits with less effort than if we cherry-pick from x64 to x86, so probably someday there appears a helper like @p4wn4r..
