### ISSUE TITLE
GBC games don't detect GBA when Bios is enabled

### ISSUE THREAD

**Issue by Fortranm** [TASVideos/BizHawk#923]
It happens in Wendy: Every Witch Way. Not sure about other games.

**Comment by zeromus** [comment]
Of course not, because a **GBC** bios is part of a **GBC** which is not a GBA. 

Please retitle this issue "boot GBC as GBA + boot w/ GBC bios makes no sense" and we should find some way to say this in the metadata, warn when its done, or make the selection mutually exclusive.

**Comment by Fortranm** [comment]
But doesn't GBA boot GB/C games with GBC bios? Or is it a special Bios?

**Comment by zeromus** [comment]
No, games detect they're running on a GBA by examining clues left behind by the bios at the moment it hands control to the game. Whatever the GBA does leaves clues that say "I'm a GBA". If it ran the GBC bios then the clues would say "I'm a GBC". Maybe it's a 99.9% similar-to-GBC bios that only changes the clues. Maybe it's totally rewritten. Doesn't matter.

**Comment by nattthebear** [comment]
@alyosha-tas Is there a boot rom for the GB that's inside a GBA that we could use here?

**Comment by alyosha-tas** [comment]
I'm not sure, this would be a good question to ask endrift or one of those GBA dev folks.
As far as I can tell from gambatte's code, the only thing the gbaCgbMode flag does is put 1 in CPU register B.
When the ARM7 hands over control to the Z80 once the GBA detects a GBC game, it presumably starts execution at memory address 00, so there must be something there since the game code starts at 0x100. So whatever is running there must set B to 1 by the time it's done. Maybe it's a slightly modified GBC BIOS that is specifically made to do this? That would make sense, maybe it's just not dumped yet?

I can't find a lot of useful info about this aspect of the GBA though.

**Comment by zeromus** [comment]
Judging from the crypticness of the mechanism used to identify the console and the oddness of the GBC bios (seems to have been designed to be the smallest ROM possible) I think it's likely the GBA boots up a modified GBC bios, which has been modified in the minimum possible way (without changing the size any) to set a different flag. Therefore I believe you could just guess the most obvious way to patch the GBC bios to yield the correctly different result, and have a decent chance of having guessed it right.

**Comment by alyosha-tas** [comment]
I gave the code a look, and as far as I can tell there are no trivial changes that would conveniently set B to 1 instead of zero. The code checks B=0 to end it's routine before handing control to the game. The closest thing to usable is an LD C,$26 instruction but that won't help.

I'll put up a feature request in mGBA and see what Endrift has to say, maybe it's easy to dump.

**Comment by alyosha-tas** [comment]
Given recent console verified TASes using pokemon in GBCinGBA mode, and related discussion of how it's done and why it's accurate, I think this can be closed.
