### ISSUE TITLE
Bizhawk 2.1.0 Daffy Duck the Marvin Missions bugs in Pizza Boy core 

### ISSUE THREAD

**Issue by mugg91** [TASVideos/BizHawk#924]
I tried Daffy Duck The Marvin Missions (both the GB and the SGB version) in the new Pizza Boy SGB core.
Sound effects seem wrong, and in the SGB version, the colors seem wrong.
http://imgur.com/zFsrMic

**Comment by vadosnaprimer** [comment]
What's the point of posting the same but in 2 different places?

**Comment by mugg91** [comment]
@vadosnaprimer because zeromus always wants me to open an issue additionally to posting in the bizhawk topic.

**Comment by zeromus** [comment]
No, I want you to open an issue after posting in the bizhawk topic when I say "open an issue", meaning "this is a good issue to open an issue for", as opposed to "this is not a good issue to open an issue for", meaning "don't open an issue". That's different from "always"

**Comment by adelikat** [comment]
"What's the point of posting the same bug in 2 different places?" <- This is a terrible comment and I will ask you not to ever criticize someone here for this again.

The point is that this issue tracker is THE authority on issues.  If you want to maximize the odds of something getting fixed it goes here.  A forum thead is a TERRIBLE place to post a bug because it is easily lost, hard to discuss, and isn't tied to the github project in anyway.  The only point of the thread is to hopefully get some reports that people wouldn't have otherwise bothered to put here.  The INTENT should be that all bugs end up here eventually.

**Comment by vadosnaprimer** [comment]
It was just a question, and it has already been answered :/

**Comment by nattthebear** [comment]
Fixed in master
